/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafaly Antoni
 */
public class Accueil extends javax.swing.JFrame {
     int xMouse,yMouse;
     String strDate;
     int x=130;
     

    /**
     * Creates new form Accueil
     */
    public Accueil() {
         initComponents();
         Date date=new Date();
      DateFormat dateFormat=new SimpleDateFormat("dd/MM/yyyy");
      strDate=dateFormat.format(date);
      txtDat.setText(strDate);
      SousM.setVisible(false); 
     // SousM.add(text1);
     // text1.setVisible(false); 
     miala.setVisible(false);
     adm.setVisible(false);
     adm1.setVisible(false);
     propo.setVisible(false);
     propo1.setVisible(false);
     reduire.setVisible(false);
     reduire1.setVisible(false);
     note.setVisible(false);
     note1.setVisible(false);
     aide.setVisible(false);
     aide1.setVisible(false);
     fer.setVisible(false);
     fer1.setVisible(false);
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adm = new javax.swing.JLabel();
        adm1 = new javax.swing.JLabel();
        fer = new javax.swing.JLabel();
        fer1 = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        note1 = new javax.swing.JLabel();
        propo = new javax.swing.JLabel();
        propo1 = new javax.swing.JLabel();
        aide = new javax.swing.JLabel();
        aide1 = new javax.swing.JLabel();
        reduire = new javax.swing.JLabel();
        reduire1 = new javax.swing.JLabel();
        cadr = new javax.swing.JLabel();
        cadr1 = new javax.swing.JLabel();
        ferm2 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        miala = new javax.swing.JLabel();
        ferm1 = new javax.swing.JLabel();
        SousM = new javax.swing.JLabel();
        barre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 75, 200, 200));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        adm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                admMousePressed(evt);
            }
        });
        getContentPane().add(adm);
        adm.setBounds(50, 43, 140, 17);

        adm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(adm1);
        adm1.setBounds(50, 43, 140, 17);

        fer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferMousePressed(evt);
            }
        });
        getContentPane().add(fer);
        fer.setBounds(50, 173, 140, 17);

        fer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(fer1);
        fer1.setBounds(50, 173, 140, 17);

        note.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noteMouseExited(evt);
            }
        });
        getContentPane().add(note);
        note.setBounds(50, 68, 140, 17);

        note1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(note1);
        note1.setBounds(50, 68, 140, 17);

        propo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                propoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                propoMouseExited(evt);
            }
        });
        getContentPane().add(propo);
        propo.setBounds(50, 95, 140, 17);

        propo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(propo1);
        propo1.setBounds(50, 95, 140, 17);

        aide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aideMouseExited(evt);
            }
        });
        getContentPane().add(aide);
        aide.setBounds(50, 121, 140, 17);

        aide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(aide1);
        aide1.setBounds(50, 121, 140, 17);

        reduire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reduireMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reduireMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reduireMousePressed(evt);
            }
        });
        getContentPane().add(reduire);
        reduire.setBounds(50, 147, 140, 17);

        reduire1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(reduire1);
        reduire1.setBounds(50, 147, 140, 17);

        cadr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadrMousePressed(evt);
            }
        });
        getContentPane().add(cadr);
        cadr.setBounds(150, 330, 169, 197);

        cadr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadr1MousePressed(evt);
            }
        });
        getContentPane().add(cadr1);
        cadr1.setBounds(150, 330, 169, 197);
        getContentPane().add(ferm2);
        ferm2.setBounds(961, 7, 19, 19);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/tirer.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuMouseReleased(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(10, 40, 30, 20);

        miala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/retour.png"))); // NOI18N
        miala.setText("jLabel1");
        miala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mialaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mialaMousePressed(evt);
            }
        });
        getContentPane().add(miala);
        miala.setBounds(10, 40, 30, 20);

        ferm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferm1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferm1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferm1MousePressed(evt);
            }
        });
        getContentPane().add(ferm1);
        ferm1.setBounds(965, 8, 19, 19);

        SousM.setBackground(new java.awt.Color(204, 0, 0));
        SousM.setForeground(new java.awt.Color(204, 0, 0));
        SousM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/sousM.jpg"))); // NOI18N
        SousM.setText("jLabel1");
        getContentPane().add(SousM);
        SousM.setBounds(49, 35, 140, 199);

        barre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barreMouseDragged(evt);
            }
        });
        barre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barreMousePressed(evt);
            }
        });
        getContentPane().add(barre);
        barre.setBounds(0, 0, 50, 600);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 0, 810, 570);

        txtDat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtDat.setForeground(new java.awt.Color(255, 255, 255));
        txtDat.setText("Date");
        getContentPane().add(txtDat);
        txtDat.setBounds(850, 280, 120, 30);

        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(710, 10, 190, 20);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/teste.jpg"))); // NOI18N
        fond.setText("jLabel2");
        fond.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fondMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fondMousePressed(evt);
            }
        });
        getContentPane().add(fond);
        fond.setBounds(0, 0, 1000, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadrMousePressed
        // TODO add your handling code here:
       // JOptionPane.showMessageDialog(this, "okkkkkkk");
        Plannig p=new Plannig();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cadrMousePressed

    private void ferm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferm1MousePressed

    private void barreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
                int y=evt.getYOnScreen();
                this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barreMouseDragged

    private void barreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
           yMouse=evt.getY();
    }//GEN-LAST:event_barreMousePressed

    private void ferm1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseEntered
        // TODO add your handling code here:
         ferm2.setVisible(true);
         fond.add(ferm2);
        ferm2.setIcon(new ImageIcon(getClass().getResource("/sary/ferme1.jpg")));
         ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_ferm1MouseEntered

    private void ferm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseExited
        // TODO add your handling code here:
        ferm2.setVisible(false);
    }//GEN-LAST:event_ferm1MouseExited

    private void cadr1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadr1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadr1MousePressed

    private void cadrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadrMouseEntered
        // TODO add your handling code here:
        cadr1.setVisible(true);
         fond.add(cadr1);
        cadr1.setIcon(new ImageIcon(getClass().getResource("/sary/cadre.png")));
         cadr1.setBounds(150,330,169, 197);
    }//GEN-LAST:event_cadrMouseEntered

    private void cadrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadrMouseExited
        // TODO add your handling code here:
         cadr1.setVisible(false);  
    }//GEN-LAST:event_cadrMouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        BackMod p = new BackMod();
       fond.add(p.fond);
       p.fond.setVisible(true);  
        
    // setVisible(false);
    }//GEN-LAST:event_jLabel5MousePressed

    private void fondMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_fondMouseEntered

    private void mialaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mialaMousePressed
        // TODO add your handling code here:
        SousM.setVisible(false);
         menu.setVisible(true);
         miala.setVisible(false);
         adm.setVisible(false);
     adm1.setVisible(false);
     propo.setVisible(false);
     propo1.setVisible(false);
     reduire.setVisible(false);
     reduire1.setVisible(false);
     note.setVisible(false);
     note1.setVisible(false);
     aide.setVisible(false);
     aide1.setVisible(false);
     fer.setVisible(false);
     fer1.setVisible(false);
    }//GEN-LAST:event_mialaMousePressed

    private void mialaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mialaMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mialaMouseExited

    private void fondMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondMousePressed
        // TODO add your handling code here:
        //SousM.setVisible(false);
    }//GEN-LAST:event_fondMousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        SousM.setVisible(false);
        menu.setVisible(true);
        miala.setVisible(false);
        adm.setVisible(false);
     adm1.setVisible(false);
     propo.setVisible(false);
     propo1.setVisible(false);
     reduire.setVisible(false);
     reduire1.setVisible(false);
     note.setVisible(false);
     note1.setVisible(false);
     aide.setVisible(false);
     aide1.setVisible(false);
     fer.setVisible(false);
     fer1.setVisible(false);
    }//GEN-LAST:event_jLabel3MousePressed

    private void admMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMouseEntered
        // TODO add your handling code here:
        adm1.setVisible(true);
        //adm1.setVisible(true);
    }//GEN-LAST:event_admMouseEntered

    private void admMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMouseExited
        // TODO add your handling code here:
        adm1.setVisible(false);
    }//GEN-LAST:event_admMouseExited

    private void noteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noteMouseEntered
        // TODO add your handling code here:
        note1.setVisible(true);
    }//GEN-LAST:event_noteMouseEntered

    private void noteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noteMouseExited
        // TODO add your handling code here:
        note1.setVisible(false);
    }//GEN-LAST:event_noteMouseExited

    private void propoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propoMouseEntered
        // TODO add your handling code here:
        propo1.setVisible(true);
    }//GEN-LAST:event_propoMouseEntered

    private void propoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propoMouseExited
        // TODO add your handling code here:
        propo1.setVisible(false);
    }//GEN-LAST:event_propoMouseExited

    private void aideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aideMouseEntered
        // TODO add your handling code here:
        aide1.setVisible(true);
    }//GEN-LAST:event_aideMouseEntered

    private void aideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aideMouseExited
        // TODO add your handling code here:
        aide1.setVisible(false);
    }//GEN-LAST:event_aideMouseExited

    private void reduireMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduireMouseEntered
        // TODO add your handling code here:
        reduire1.setVisible(true);
    }//GEN-LAST:event_reduireMouseEntered

    private void reduireMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduireMouseExited
        // TODO add your handling code here:
        reduire1.setVisible(false);
    }//GEN-LAST:event_reduireMouseExited

    private void ferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferMouseEntered
        // TODO add your handling code here:
        fer1.setVisible(true);
    }//GEN-LAST:event_ferMouseEntered

    private void ferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferMouseExited
        // TODO add your handling code here:
        fer1.setVisible(false);
    }//GEN-LAST:event_ferMouseExited

    private void ferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferMousePressed

    private void reduireMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduireMousePressed
        // TODO add your handling code here:
         setState(Accueil.ICONIFIED);
    }//GEN-LAST:event_reduireMousePressed

    private void admMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMousePressed
        // TODO add your handling code here:
         SousM.setVisible(false);
        menu.setVisible(true);
        miala.setVisible(false);
        adm.setVisible(false);
     adm1.setVisible(false);
     propo.setVisible(false);
     propo1.setVisible(false);
     reduire.setVisible(false);
     reduire1.setVisible(false);
     note.setVisible(false);
     note1.setVisible(false);
     aide.setVisible(false);
     aide1.setVisible(false);
     fer.setVisible(false);
     fer1.setVisible(false);
    }//GEN-LAST:event_admMousePressed

    private void menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseReleased

    private void menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMousePressed
        // TODO add your handling code here:
        SousM.setVisible(true);
        menu.setVisible(false);
        miala.setVisible(true);
        //****
        adm.setVisible(true);
        propo.setVisible(true);
        reduire.setVisible(true);
        note.setVisible(true);
        aide.setVisible(true);
        fer.setVisible(true);

    }//GEN-LAST:event_menuMousePressed

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseExited

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        // TODO add your handling code here:

        /*if(x==210){
            sousM.setSize(130, 190);
            Thread th = new Thread();

            @Override
            public void run(){
                try{
                    for(int i=210;i>=0;i--)
                    {
                        Thread.sleep(1);
                        sousM.setSize(130,190);
                    }
                }
                catch(Exception e){}

            };
            th.start();
            x=0;
        }*/
    }//GEN-LAST:event_menuMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SousM;
    private javax.swing.JLabel adm;
    private javax.swing.JLabel adm1;
    private javax.swing.JLabel aide;
    private javax.swing.JLabel aide1;
    private javax.swing.JLabel barre;
    private javax.swing.JLabel cadr;
    private javax.swing.JLabel cadr1;
    private javax.swing.JLabel fer;
    private javax.swing.JLabel fer1;
    private javax.swing.JLabel ferm1;
    private javax.swing.JLabel ferm2;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel miala;
    private javax.swing.JLabel note;
    private javax.swing.JLabel note1;
    private javax.swing.JLabel propo;
    private javax.swing.JLabel propo1;
    private javax.swing.JLabel reduire;
    private javax.swing.JLabel reduire1;
    private javax.swing.JLabel txtDat;
    // End of variables declaration//GEN-END:variables
}
