/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author Snow
 */
public class Accueil_Admin extends javax.swing.JFrame {
int xMouse, yMouse;
/*
     * Creates new form Accueil_Admin
     */
    public Accueil_Admin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LAcalendrier = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        retour1 = new javax.swing.JLabel();
        retour = new javax.swing.JLabel();
        barre = new javax.swing.JLabel();
        ferm1 = new javax.swing.JLabel();
        ferm2 = new javax.swing.JLabel();
        LApersonnel = new javax.swing.JLabel();
        LAstock = new javax.swing.JLabel();
        deconecter = new javax.swing.JLabel();
        Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        LAcalendrier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LAcalendrier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LAcalendrierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LAcalendrierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LAcalendrierMousePressed(evt);
            }
        });
        getContentPane().add(LAcalendrier);
        LAcalendrier.setBounds(180, 330, 120, 130);

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 330, 110, 130);

        retour1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retour1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retour1MousePressed(evt);
            }
        });
        getContentPane().add(retour1);
        retour1.setBounds(10, 10, 30, 20);

        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(10, 10, 30, 0);

        barre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barreMouseDragged(evt);
            }
        });
        barre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barreMousePressed(evt);
            }
        });
        getContentPane().add(barre);
        barre.setBounds(0, 0, 50, 600);

        ferm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferm1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferm1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferm1MousePressed(evt);
            }
        });
        getContentPane().add(ferm1);
        ferm1.setBounds(965, 8, 19, 19);
        getContentPane().add(ferm2);
        ferm2.setBounds(961, 7, 19, 19);

        LApersonnel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LApersonnel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LApersonnelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LApersonnelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LApersonnelMousePressed(evt);
            }
        });
        getContentPane().add(LApersonnel);
        LApersonnel.setBounds(740, 330, 120, 130);

        LAstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LAstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LAstockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LAstockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LAstockMousePressed(evt);
            }
        });
        getContentPane().add(LAstock);
        LAstock.setBounds(460, 330, 120, 130);

        deconecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deconecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deconecterMousePressed(evt);
            }
        });
        getContentPane().add(deconecter);
        deconecter.setBounds(770, 10, 70, 20);

        Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Menu_Admin.jpg"))); // NOI18N
        Fond.setText("jLabel1");
        getContentPane().add(Fond);
        Fond.setBounds(0, 0, 1000, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LAstockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAstockMousePressed
        // TODO add your handling code here:
        AdminStock add1 = new AdminStock();
        add1.setVisible(true);
        this.setVisible(false);
       // ad_st.choixpers();
    }//GEN-LAST:event_LAstockMousePressed

    private void barreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barreMouseDragged

    private void barreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_barreMousePressed

    private void ferm1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseEntered
        // TODO add your handling code here:
        ferm2.setVisible(true);
        Fond.add(ferm2);
        ferm2.setIcon(new ImageIcon(getClass().getResource("/image/ferme.jpg")));
        ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_ferm1MouseEntered

    private void ferm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseExited
        // TODO add your handling code here:
        ferm2.setVisible(false);
    }//GEN-LAST:event_ferm1MouseExited

    private void ferm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferm1MousePressed

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourMousePressed

    private void LApersonnelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LApersonnelMousePressed
        // TODO add your handling code here:
        AdminPers addpers = new AdminPers();
        this.setVisible(false);
        addpers.setVisible(true);
    }//GEN-LAST:event_LApersonnelMousePressed

    private void deconecterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconecterMousePressed
    MessConfirmation mc=new MessConfirmation();
    mc.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_deconecterMousePressed

    private void retour1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retour1MousePressed
        // TODO add your handling code here:
       MessConfirmation mc=new MessConfirmation();
        mc.setVisible(true);
    }//GEN-LAST:event_retour1MousePressed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MousePressed

    private void LAcalendrierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAcalendrierMousePressed
    BackMod bac= new BackMod();
    bac.setVisible(true);
    this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_LAcalendrierMousePressed

    private void LAcalendrierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAcalendrierMouseEntered
       jLabel7.setIcon(new ImageIcon(getClass().getResource("/image/NextBoutonMenu.png")));
       jLabel7.setBounds(189,330,95,95);         
       Fond.add(jLabel7);
      jLabel7.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LAcalendrierMouseEntered

    private void LAstockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAstockMouseEntered
       jLabel7.setIcon(new ImageIcon(getClass().getResource("/image/NextBoutonMenu.png")));
       jLabel7.setBounds(473,330,95,95);         
       Fond.add(jLabel7);
      jLabel7.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LAstockMouseEntered

    private void LApersonnelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LApersonnelMouseEntered
       jLabel7.setIcon(new ImageIcon(getClass().getResource("/image/NextBoutonMenu.png")));
       jLabel7.setBounds(758,330,95,95);         
       Fond.add(jLabel7);
      jLabel7.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LApersonnelMouseEntered

    private void LAcalendrierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAcalendrierMouseExited
    jLabel7.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_LAcalendrierMouseExited

    private void LAstockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAstockMouseExited
    jLabel7.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_LAstockMouseExited

    private void LApersonnelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LApersonnelMouseExited
    jLabel7.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_LApersonnelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil_Admin().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fond;
    private javax.swing.JLabel LAcalendrier;
    private javax.swing.JLabel LApersonnel;
    private javax.swing.JLabel LAstock;
    private javax.swing.JLabel barre;
    public javax.swing.JLabel deconecter;
    private javax.swing.JLabel ferm1;
    private javax.swing.JLabel ferm2;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel retour;
    public javax.swing.JLabel retour1;
    // End of variables declaration//GEN-END:variables
}
