/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;  

/**
 *
 * @author Snow
 */
public class AdminStock3 extends javax.swing.JFrame {

    /**
     * Creates new form AdminStock3
     */
    public AdminStock3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockligne33 = new javax.swing.JLabel();
        stockligne31 = new javax.swing.JLabel();
        stockligne32 = new javax.swing.JLabel();
        Ltexte22 = new javax.swing.JLabel();
        Table3 = new javax.swing.JScrollPane();
        JTable3 = new javax.swing.JTable();
        Tquantite3 = new javax.swing.JTextField();
        Lnom3 = new javax.swing.JLabel();
        Tnom3 = new javax.swing.JTextField();
        Ldate3 = new javax.swing.JLabel();
        Lquantite3 = new javax.swing.JLabel();
        Tpersonnel3 = new javax.swing.JComboBox();
        Lpersonnel3 = new javax.swing.JLabel();
        Bmodifier3 = new javax.swing.JButton();
        Bsupprimer3 = new javax.swing.JButton();
        Bactualiser3 = new javax.swing.JButton();
        Tdate3 = new javax.swing.JTextField();
        Fond_Astock3 = new javax.swing.JLabel();
        Tident3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        stockligne33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        stockligne33.setText("jLabel2");
        getContentPane().add(stockligne33);
        stockligne33.setBounds(700, 150, 230, 2);

        stockligne31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        stockligne31.setText("jLabel2");
        getContentPane().add(stockligne31);
        stockligne31.setBounds(250, 150, 230, 2);

        stockligne32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        stockligne32.setText("jLabel2");
        getContentPane().add(stockligne32);
        stockligne32.setBounds(250, 210, 230, 2);

        Ltexte22.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Ltexte22.setForeground(new java.awt.Color(2, 115, 197));
        Ltexte22.setText("Listes des matériels Inutilisables");
        getContentPane().add(Ltexte22);
        Ltexte22.setBounds(90, 360, 280, 30);

        JTable3.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        JTable3.setForeground(new java.awt.Color(67, 68, 70));
        JTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Date", "Quantié", "Personnel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table3.setViewportView(JTable3);

        getContentPane().add(Table3);
        Table3.setBounds(90, 402, 880, 150);

        Tquantite3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Tquantite3.setForeground(new java.awt.Color(2, 115, 197));
        Tquantite3.setBorder(null);
        getContentPane().add(Tquantite3);
        Tquantite3.setBounds(700, 120, 230, 30);

        Lnom3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lnom3.setForeground(new java.awt.Color(67, 68, 70));
        Lnom3.setText("Nom matériel");
        getContentPane().add(Lnom3);
        Lnom3.setBounds(90, 120, 90, 30);

        Tnom3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Tnom3.setForeground(new java.awt.Color(2, 115, 197));
        Tnom3.setBorder(null);
        Tnom3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Tnom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tnom3ActionPerformed(evt);
            }
        });
        getContentPane().add(Tnom3);
        Tnom3.setBounds(250, 120, 230, 30);

        Ldate3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Ldate3.setForeground(new java.awt.Color(67, 68, 70));
        Ldate3.setText("Date fin de service");
        getContentPane().add(Ldate3);
        Ldate3.setBounds(90, 180, 130, 30);

        Lquantite3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lquantite3.setForeground(new java.awt.Color(67, 68, 70));
        Lquantite3.setText("Quantité");
        getContentPane().add(Lquantite3);
        Lquantite3.setBounds(550, 120, 60, 30);

        Tpersonnel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        Tpersonnel3.setForeground(new java.awt.Color(2, 115, 197));
        Tpersonnel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tpersonnel3ActionPerformed(evt);
            }
        });
        getContentPane().add(Tpersonnel3);
        Tpersonnel3.setBounds(700, 180, 230, 30);

        Lpersonnel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lpersonnel3.setForeground(new java.awt.Color(67, 68, 70));
        Lpersonnel3.setText("Personnel ");
        getContentPane().add(Lpersonnel3);
        Lpersonnel3.setBounds(550, 180, 90, 30);

        Bmodifier3.setBackground(new java.awt.Color(12, 46, 76));
        Bmodifier3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Bmodifier3.setForeground(new java.awt.Color(255, 255, 255));
        Bmodifier3.setText("Modifier");
        Bmodifier3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bmodifier3MousePressed(evt);
            }
        });
        getContentPane().add(Bmodifier3);
        Bmodifier3.setBounds(590, 320, 100, 30);

        Bsupprimer3.setBackground(new java.awt.Color(12, 46, 76));
        Bsupprimer3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Bsupprimer3.setForeground(new java.awt.Color(255, 255, 255));
        Bsupprimer3.setText("Supprimer");
        Bsupprimer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bsupprimer3MousePressed(evt);
            }
        });
        Bsupprimer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsupprimer3ActionPerformed(evt);
            }
        });
        getContentPane().add(Bsupprimer3);
        Bsupprimer3.setBounds(710, 320, 100, 30);

        Bactualiser3.setBackground(new java.awt.Color(12, 46, 76));
        Bactualiser3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Bactualiser3.setForeground(new java.awt.Color(255, 255, 255));
        Bactualiser3.setText("Actualiser");
        Bactualiser3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bactualiser3MousePressed(evt);
            }
        });
        Bactualiser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bactualiser3ActionPerformed(evt);
            }
        });
        getContentPane().add(Bactualiser3);
        Bactualiser3.setBounds(830, 320, 100, 30);

        Tdate3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Tdate3.setForeground(new java.awt.Color(2, 115, 197));
        Tdate3.setBorder(null);
        Tdate3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Tdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tdate3ActionPerformed(evt);
            }
        });
        getContentPane().add(Tdate3);
        Tdate3.setBounds(250, 180, 230, 30);

        Fond_Astock3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Admin_StockV1.jpg"))); // NOI18N
        Fond_Astock3.setText("jLabel1");
        Fond_Astock3.setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(Fond_Astock3);
        Fond_Astock3.setBounds(0, 0, 1000, 600);

        Tident3.setText("jTextField1");
        Tident3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tident3ActionPerformed(evt);
            }
        });
        getContentPane().add(Tident3);
        Tident3.setBounds(480, 260, 59, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tnom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tnom3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tnom3ActionPerformed

    private void Tpersonnel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tpersonnel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tpersonnel3ActionPerformed

    private void Bmodifier3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bmodifier3MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Bmodifier3MousePressed

    private void Bsupprimer3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bsupprimer3MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Bsupprimer3MousePressed

    private void Bsupprimer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsupprimer3ActionPerformed
        //   enregistrer();
        //  Afficher();// TODO add your handling code here:
    }//GEN-LAST:event_Bsupprimer3ActionPerformed

    private void Bactualiser3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bactualiser3MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Bactualiser3MousePressed

    private void Bactualiser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bactualiser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bactualiser3ActionPerformed

    private void Tident3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tident3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tident3ActionPerformed

    private void Tdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tdate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdate3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStock3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStock3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStock3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStock3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStock3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bactualiser3;
    public javax.swing.JButton Bmodifier3;
    public javax.swing.JButton Bsupprimer3;
    private javax.swing.JLabel Fond_Astock3;
    public javax.swing.JTable JTable3;
    public javax.swing.JLabel Ldate3;
    public javax.swing.JLabel Lnom3;
    public javax.swing.JLabel Lpersonnel3;
    public javax.swing.JLabel Lquantite3;
    public javax.swing.JLabel Ltexte22;
    public javax.swing.JScrollPane Table3;
    public javax.swing.JTextField Tdate3;
    public javax.swing.JTextField Tident3;
    public javax.swing.JTextField Tnom3;
    public javax.swing.JComboBox Tpersonnel3;
    public javax.swing.JTextField Tquantite3;
    public javax.swing.JLabel stockligne31;
    public javax.swing.JLabel stockligne32;
    public javax.swing.JLabel stockligne33;
    // End of variables declaration//GEN-END:variables
}
