/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classe.Materiel;
import javax.swing.ImageIcon;
import controler.Database;
import javax.swing.JOptionPane;
/**
 *
 * @author Snow
 */
public class AdminAdmin extends javax.swing.JFrame {
int xMouse, yMouse;
MessErreur m = new MessErreur();
MessVrai m2=new MessVrai();
Database d=new Database();
    /**
     * Creates new form AdminPers
     */
    public AdminAdmin() {
        initComponents();
        Afficher();
    }
    
  public void Afficher(){                       //  passe par Database
      try{
            for(int i=0;i<=d.AfficherPersonnel().size();i++){
                TtableAdminAdmin.setValueAt (d.AfficherPersonnel().get(i).getIdpersonnel(),i,0);  
                TtableAdminAdmin.setValueAt (d.AfficherPersonnel().get(i).getNom(),i,1);
                TtableAdminAdmin.setValueAt (d.AfficherPersonnel().get(i).getCode(),i,2);
                TtableAdminAdmin.setValueAt (d.AfficherPersonnel().get(i).getFonction(),i,3);
                }
        }
        catch (Exception e){
        }
  }
    
  public void Actualiser(){
      Tnomadmin.setText("");
      Tcodeadmin.setText("");
      Tfonctionpers.setText("");
      Afficher();
  }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retour = new javax.swing.JLabel();
        ferm1 = new javax.swing.JLabel();
        ferm2 = new javax.swing.JLabel();
        barre = new javax.swing.JLabel();
        Lnomadmin = new javax.swing.JLabel();
        Lcodeadmin = new javax.swing.JLabel();
        Tcodeadmin = new javax.swing.JTextField();
        Tnomadmin = new javax.swing.JTextField();
        Bajouterpers = new javax.swing.JButton();
        JTableAdminAdmin = new javax.swing.JScrollPane();
        TtableAdminAdmin = new javax.swing.JTable();
        Bactualiser = new javax.swing.JButton();
        Bsupprimerpers1 = new javax.swing.JButton();
        Bmodifierpers = new javax.swing.JButton();
        deconecter = new javax.swing.JLabel();
        Fond_Admin_Pers = new javax.swing.JLabel();
        Lfonctionpers = new javax.swing.JLabel();
        Tfonctionpers = new javax.swing.JTextField();
        Tid_admin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btab2.png"))); // NOI18N
        retour.setText("retour");
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(10, 40, 30, 30);

        ferm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferm1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferm1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferm1MousePressed(evt);
            }
        });
        getContentPane().add(ferm1);
        ferm1.setBounds(965, 8, 19, 19);
        getContentPane().add(ferm2);
        ferm2.setBounds(961, 7, 19, 19);

        barre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barreMouseDragged(evt);
            }
        });
        barre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barreMousePressed(evt);
            }
        });
        getContentPane().add(barre);
        barre.setBounds(0, 0, 50, 600);

        Lnomadmin.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lnomadmin.setForeground(new java.awt.Color(67, 68, 70));
        Lnomadmin.setText("Nom admnistratreur");
        getContentPane().add(Lnomadmin);
        Lnomadmin.setBounds(90, 270, 140, 30);

        Lcodeadmin.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lcodeadmin.setForeground(new java.awt.Color(67, 68, 70));
        Lcodeadmin.setText("Code administrateur");
        getContentPane().add(Lcodeadmin);
        Lcodeadmin.setBounds(90, 320, 130, 30);

        Tcodeadmin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Tcodeadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcodeadminActionPerformed(evt);
            }
        });
        getContentPane().add(Tcodeadmin);
        Tcodeadmin.setBounds(250, 320, 160, 30);

        Tnomadmin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Tnomadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnomadminActionPerformed(evt);
            }
        });
        getContentPane().add(Tnomadmin);
        Tnomadmin.setBounds(250, 270, 160, 30);

        Bajouterpers.setBackground(new java.awt.Color(12, 46, 76));
        Bajouterpers.setForeground(new java.awt.Color(255, 255, 255));
        Bajouterpers.setText("Ajouter");
        Bajouterpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajouterpersActionPerformed(evt);
            }
        });
        getContentPane().add(Bajouterpers);
        Bajouterpers.setBounds(80, 490, 90, 30);

        TtableAdminAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "identifiant", "Nom", "Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TtableAdminAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TtableAdminAdminMouseReleased(evt);
            }
        });
        JTableAdminAdmin.setViewportView(TtableAdminAdmin);

        getContentPane().add(JTableAdminAdmin);
        JTableAdminAdmin.setBounds(490, 260, 480, 260);

        Bactualiser.setBackground(new java.awt.Color(12, 46, 76));
        Bactualiser.setForeground(new java.awt.Color(255, 255, 255));
        Bactualiser.setText("Actualiser");
        Bactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BactualiserActionPerformed(evt);
            }
        });
        getContentPane().add(Bactualiser);
        Bactualiser.setBounds(380, 490, 90, 30);

        Bsupprimerpers1.setBackground(new java.awt.Color(12, 46, 76));
        Bsupprimerpers1.setForeground(new java.awt.Color(255, 255, 255));
        Bsupprimerpers1.setText("Supprimer");
        Bsupprimerpers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsupprimerpers1ActionPerformed(evt);
            }
        });
        getContentPane().add(Bsupprimerpers1);
        Bsupprimerpers1.setBounds(280, 490, 90, 30);

        Bmodifierpers.setBackground(new java.awt.Color(12, 46, 76));
        Bmodifierpers.setForeground(new java.awt.Color(255, 255, 255));
        Bmodifierpers.setText("Modifier");
        Bmodifierpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodifierpersActionPerformed(evt);
            }
        });
        getContentPane().add(Bmodifierpers);
        Bmodifierpers.setBounds(180, 490, 90, 30);

        deconecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deconecterMousePressed(evt);
            }
        });
        getContentPane().add(deconecter);
        deconecter.setBounds(770, 10, 70, 20);

        Fond_Admin_Pers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AdminPers.jpg"))); // NOI18N
        Fond_Admin_Pers.setText("jLabel1");
        getContentPane().add(Fond_Admin_Pers);
        Fond_Admin_Pers.setBounds(0, 0, 1000, 600);

        Lfonctionpers.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lfonctionpers.setForeground(new java.awt.Color(67, 68, 70));
        Lfonctionpers.setText("Fonction personnel");
        getContentPane().add(Lfonctionpers);
        Lfonctionpers.setBounds(90, 380, 120, 30);

        Tfonctionpers.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Tfonctionpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfonctionpersActionPerformed(evt);
            }
        });
        getContentPane().add(Tfonctionpers);
        Tfonctionpers.setBounds(250, 380, 160, 30);

        Tid_admin.setText("jTextField1");
        Tid_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tid_adminActionPerformed(evt);
            }
        });
        getContentPane().add(Tid_admin);
        Tid_admin.setBounds(210, 440, 59, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ferm1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseEntered
        // TODO add your handling code here:
        ferm2.setVisible(true);
        Fond_Admin_Pers.add(ferm2);
        ferm2.setIcon(new ImageIcon(getClass().getResource("/image/ferme.jpg")));
        ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_ferm1MouseEntered

    private void ferm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseExited
        // TODO add your handling code here:
        ferm2.setVisible(false);
    }//GEN-LAST:event_ferm1MouseExited

    private void ferm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferm1MousePressed

    private void barreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barreMouseDragged

    private void barreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_barreMousePressed

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        // TODO add your handling code here:
        Accueil_Admin acadd = new Accueil_Admin();
        acadd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourMousePressed

    private void TcodeadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcodeadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcodeadminActionPerformed

    private void TnomadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnomadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnomadminActionPerformed

    private void BajouterpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajouterpersActionPerformed
    if (Tnomadmin.getText().equals("") ||
        Tcodeadmin.getText().equals("") ||
        Tfonctionpers.getText().equals("") )
         {
             m.setVisible(true);
             m.ErreurTexte.setVisible(true);
             m.ErreurTexte.setText("Remplissez les zones de saisie");
         }
         else
         {
             ///  **************************      ici  ici
             m2.setVisible(true);
             m2.ErreurTexte.setVisible(true);
             m2.ErreurTexte.setText(" Personnel inserer ");
             Materiel m =new Materiel(Tnomadmin.getText(), Tcodeadmin.getText(), Tfonctionpers.getText());
             d.EnregistrerPersonnel(m.getNom(), m.getCode(), m.getFonction());
         }    
                 // TODO add your handling code here:
    }//GEN-LAST:event_BajouterpersActionPerformed

    private void TfonctionpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfonctionpersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfonctionpersActionPerformed

    private void BmodifierpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodifierpersActionPerformed
if (Tnomadmin.getText().equals("") ||
        Tcodeadmin.getText().equals("") ||
        Tfonctionpers.getText().equals("") )
{    
    m.setVisible(true);
        m.ErreurTexte.setVisible(true);
        m.ErreurTexte.setText(" Remplissez les zones de saisie ");             
        }
    else{
        m2.setVisible(true);
         m2.ErreurTexte.setVisible(true);
         m2.ErreurTexte.setText(" Administrateur modifier ");  
    //     Materiel m = new Materiel(Tnomadmin.getText(), Tcodeadmin.getText(), Tfonctionpers.getText());
    //    d.ModifierPersonnel(m.getNom(), m.getCode(), m.getFonction(), Tid_admin.getText());
       // JOptionPane.showMessageDialog(this, "Materiel modifier ");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_BmodifierpersActionPerformed

    private void BactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BactualiserActionPerformed
  Actualiser();
    }//GEN-LAST:event_BactualiserActionPerformed

    private void Tid_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tid_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tid_adminActionPerformed

    private void TtableAdminAdminMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TtableAdminAdminMouseReleased
         Tnomadmin.setText(String.valueOf(TtableAdminAdmin.getValueAt(TtableAdminAdmin.getSelectedRow(),1)));
         Tcodeadmin.setText(String.valueOf(TtableAdminAdmin.getValueAt(TtableAdminAdmin.getSelectedRow(),2)));
     //    Tfonctionpers.setText(String.valueOf(TtableAdminAdmin.getValueAt(TtableAdminAdmin.getSelectedRow(),3)));
         Tid_admin.setText(String.valueOf(TtableAdminAdmin.getValueAt(TtableAdminAdmin.getSelectedRow(),0))); 
         //JOptionPane.showMessageDialog(this,String.valueOf(TtableAdminPers.getValueAt(TtableAdminPers.getSelectedRow(),0)));
// TODO add your handling code here:
    }//GEN-LAST:event_TtableAdminAdminMouseReleased

    private void Bsupprimerpers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsupprimerpers1ActionPerformed
            m2.setVisible(true);
             m2.ErreurTexte.setVisible(true);
             m2.ErreurTexte.setText(" Administrateur supprimer ");
             d.SupprimerPersonnel(Tid_admin.getText());
                 }//GEN-LAST:event_Bsupprimerpers1ActionPerformed

    private void deconecterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconecterMousePressed
        MessConfirmation mc=new MessConfirmation();
        mc.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_deconecterMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bactualiser;
    public javax.swing.JButton Bajouterpers;
    public javax.swing.JButton Bmodifierpers;
    public javax.swing.JButton Bsupprimerpers1;
    private javax.swing.JLabel Fond_Admin_Pers;
    private javax.swing.JScrollPane JTableAdminAdmin;
    public javax.swing.JLabel Lcodeadmin;
    public javax.swing.JLabel Lfonctionpers;
    public javax.swing.JLabel Lnomadmin;
    public javax.swing.JTextField Tcodeadmin;
    public javax.swing.JTextField Tfonctionpers;
    private javax.swing.JTextField Tid_admin;
    public javax.swing.JTextField Tnomadmin;
    private javax.swing.JTable TtableAdminAdmin;
    private javax.swing.JLabel barre;
    public javax.swing.JLabel deconecter;
    private javax.swing.JLabel ferm1;
    private javax.swing.JLabel ferm2;
    public javax.swing.JLabel retour;
    // End of variables declaration//GEN-END:variables
}
