/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classe.Materiel;
import com.caucho.hessian.client.HessianProxyFactory;
import javax.swing.ImageIcon;
import controler.Database;
import controler.IDatabase;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/** 
 *
 * @author Snow
 */
public class AdminPers extends javax.swing.JFrame {
int xMouse, yMouse;
MessErreur m = new MessErreur();
MessVrai m2=new MessVrai();
//Database d=new Database();
    /**
     * Creates new form AdminPers
     */
 private IDatabase d = null;
  static private String hoteDist = "http://DESKTOP-VLD2HGD:8080/appView/rpc";  //DESKTOP-VLD2HGD
	static private IDatabase getConnection(String url)
	{
		try 
		{
			HessianProxyFactory factory = new com.caucho.hessian.client.HessianProxyFactory();
			return (IDatabase)factory.create(IDatabase.class,url); 
		}
		catch(Exception e)
		{
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    return null;
		}
	}
   
public AdminPers() {
        initComponents();
    //    crud = new Database();
        d = getConnection(hoteDist);
        Afficher();
    }
   
  public void Afficher(){                       //  passe par Database
      try{
          TtableAdminPers.setModel(new DefaultTableModel(new String []{"Identifiant","Nom","Code","Fonctions"},d.AfficherPersonnel().size()));
            for(int i=0;i<=d.AfficherPersonnel().size();i++){
                TtableAdminPers.setValueAt (d.AfficherPersonnel().get(i).getIdpersonnel(),i,0);  
                TtableAdminPers.setValueAt (d.AfficherPersonnel().get(i).getNom(),i,1);
                TtableAdminPers.setValueAt (d.AfficherPersonnel().get(i).getCode(),i,2);
                TtableAdminPers.setValueAt (d.AfficherPersonnel().get(i).getFonction(),i,3);
                }
        }
        catch (Exception e){
             JOptionPane.showMessageDialog(null,  e.getMessage());
                   System.out.println(e.getMessage());
        }
  }
    
  public void Actualiser(){
      Tnompers.setText("");
      Tcodepers.setText("");
      Tfonctionpers.setText("");
      Afficher();
  }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ligneBilan = new javax.swing.JLabel();
        ligneBilan1 = new javax.swing.JLabel();
        ligneBilan2 = new javax.swing.JLabel();
        retour = new javax.swing.JLabel();
        barre = new javax.swing.JLabel();
        Lnompers = new javax.swing.JLabel();
        Lcodepers = new javax.swing.JLabel();
        Tcodepers = new javax.swing.JTextField();
        Tnompers = new javax.swing.JTextField();
        Bajouterpers = new javax.swing.JButton();
        JTableAdminPers = new javax.swing.JScrollPane();
        TtableAdminPers = new javax.swing.JTable();
        Lfonctionpers = new javax.swing.JLabel();
        Tfonctionpers = new javax.swing.JTextField();
        Bactualiser = new javax.swing.JButton();
        Bsupprimerpers1 = new javax.swing.JButton();
        Bmodifierpers = new javax.swing.JButton();
        deconecter = new javax.swing.JLabel();
        ferm1 = new javax.swing.JLabel();
        ferm2 = new javax.swing.JLabel();
        Fond_Admin_Pers = new javax.swing.JLabel();
        Tid_personnel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        ligneBilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        ligneBilan.setText("jLabel2");
        getContentPane().add(ligneBilan);
        ligneBilan.setBounds(220, 300, 230, 2);

        ligneBilan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        ligneBilan1.setText("jLabel2");
        getContentPane().add(ligneBilan1);
        ligneBilan1.setBounds(220, 410, 230, 2);

        ligneBilan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        ligneBilan2.setText("jLabel2");
        getContentPane().add(ligneBilan2);
        ligneBilan2.setBounds(220, 350, 230, 2);

        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(10, 10, 30, 20);

        barre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barreMouseDragged(evt);
            }
        });
        barre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barreMousePressed(evt);
            }
        });
        getContentPane().add(barre);
        barre.setBounds(0, 0, 50, 600);

        Lnompers.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lnompers.setForeground(new java.awt.Color(67, 68, 70));
        Lnompers.setText("Nom personnel");
        getContentPane().add(Lnompers);
        Lnompers.setBounds(80, 280, 140, 30);

        Lcodepers.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lcodepers.setForeground(new java.awt.Color(67, 68, 70));
        Lcodepers.setText("Code personnel");
        getContentPane().add(Lcodepers);
        Lcodepers.setBounds(80, 330, 110, 30);

        Tcodepers.setBorder(null);
        Tcodepers.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Tcodepers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcodepersActionPerformed(evt);
            }
        });
        getContentPane().add(Tcodepers);
        Tcodepers.setBounds(220, 320, 230, 30);

        Tnompers.setBorder(null);
        Tnompers.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Tnompers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnompersActionPerformed(evt);
            }
        });
        getContentPane().add(Tnompers);
        Tnompers.setBounds(220, 270, 230, 30);

        Bajouterpers.setBackground(new java.awt.Color(12, 46, 76));
        Bajouterpers.setForeground(new java.awt.Color(255, 255, 255));
        Bajouterpers.setText("Ajouter");
        Bajouterpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajouterpersActionPerformed(evt);
            }
        });
        getContentPane().add(Bajouterpers);
        Bajouterpers.setBounds(80, 490, 90, 30);

        TtableAdminPers.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        TtableAdminPers.setForeground(new java.awt.Color(67, 68, 70));
        TtableAdminPers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "identifiant", "Nom", "Code", "Fonction"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TtableAdminPers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TtableAdminPersMouseReleased(evt);
            }
        });
        JTableAdminPers.setViewportView(TtableAdminPers);

        getContentPane().add(JTableAdminPers);
        JTableAdminPers.setBounds(490, 260, 480, 260);

        Lfonctionpers.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lfonctionpers.setForeground(new java.awt.Color(67, 68, 70));
        Lfonctionpers.setText("Fonction personnel");
        getContentPane().add(Lfonctionpers);
        Lfonctionpers.setBounds(80, 390, 120, 30);

        Tfonctionpers.setBorder(null);
        Tfonctionpers.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Tfonctionpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfonctionpersActionPerformed(evt);
            }
        });
        getContentPane().add(Tfonctionpers);
        Tfonctionpers.setBounds(220, 380, 230, 30);

        Bactualiser.setBackground(new java.awt.Color(12, 46, 76));
        Bactualiser.setForeground(new java.awt.Color(255, 255, 255));
        Bactualiser.setText("Actualiser");
        Bactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BactualiserActionPerformed(evt);
            }
        });
        getContentPane().add(Bactualiser);
        Bactualiser.setBounds(380, 490, 90, 30);

        Bsupprimerpers1.setBackground(new java.awt.Color(12, 46, 76));
        Bsupprimerpers1.setForeground(new java.awt.Color(255, 255, 255));
        Bsupprimerpers1.setText("Supprimer");
        Bsupprimerpers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsupprimerpers1ActionPerformed(evt);
            }
        });
        getContentPane().add(Bsupprimerpers1);
        Bsupprimerpers1.setBounds(280, 490, 90, 30);

        Bmodifierpers.setBackground(new java.awt.Color(12, 46, 76));
        Bmodifierpers.setForeground(new java.awt.Color(255, 255, 255));
        Bmodifierpers.setText("Modifier");
        Bmodifierpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodifierpersActionPerformed(evt);
            }
        });
        getContentPane().add(Bmodifierpers);
        Bmodifierpers.setBounds(180, 490, 90, 30);

        deconecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deconecterMousePressed(evt);
            }
        });
        getContentPane().add(deconecter);
        deconecter.setBounds(770, 10, 70, 20);

        ferm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferm1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferm1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferm1MousePressed(evt);
            }
        });
        getContentPane().add(ferm1);
        ferm1.setBounds(965, 8, 19, 19);
        getContentPane().add(ferm2);
        ferm2.setBounds(961, 7, 19, 19);

        Fond_Admin_Pers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AdminPers.jpg"))); // NOI18N
        Fond_Admin_Pers.setText("jLabel1");
        getContentPane().add(Fond_Admin_Pers);
        Fond_Admin_Pers.setBounds(0, 0, 1000, 600);

        Tid_personnel.setText("jTextField1");
        Tid_personnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tid_personnelActionPerformed(evt);
            }
        });
        getContentPane().add(Tid_personnel);
        Tid_personnel.setBounds(210, 440, 59, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barreMouseDragged

    private void barreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_barreMousePressed

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        // TODO add your handling code here:
        Accueil_Admin acadd = new Accueil_Admin();
        acadd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourMousePressed

    private void TcodepersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcodepersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcodepersActionPerformed

    private void TnompersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnompersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnompersActionPerformed

    private void BajouterpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajouterpersActionPerformed
    if (Tnompers.getText().equals("") ||
        Tcodepers.getText().equals("") ||
        Tfonctionpers.getText().equals("") )
         {
             m.setVisible(true);
             m.ErreurTexte.setVisible(true);
             m.ErreurTexte.setText("Remplissez les zones de saisie");
         }
         else
         {
             ///  **************************      ici  ici
             m2.setVisible(true);
             m2.ErreurTexte.setVisible(true);
             m2.ErreurTexte.setText(" Personnel inserer ");
             Materiel m =new Materiel(Tnompers.getText(), Tcodepers.getText(), Tfonctionpers.getText());
             d.EnregistrerPersonnel(m.getNom(), m.getCode(), m.getFonction());
         }    
                 // TODO add your handling code here:
    }//GEN-LAST:event_BajouterpersActionPerformed

    private void TfonctionpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfonctionpersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfonctionpersActionPerformed

    private void BmodifierpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodifierpersActionPerformed
if (Tnompers.getText().equals("") ||
        Tcodepers.getText().equals("") ||
        Tfonctionpers.getText().equals("") )
{    
    m.setVisible(true);
        m.ErreurTexte.setVisible(true);
        m.ErreurTexte.setText(" Remplissez les zones de saisie ");             
        }
    else{
        m2.setVisible(true);
         m2.ErreurTexte.setVisible(true);
         m2.ErreurTexte.setText(" Personnel modifier ");  
         Materiel m = new Materiel(Tnompers.getText(), Tcodepers.getText(), Tfonctionpers.getText());
        d.ModifierPersonnel(m.getNom(), m.getCode(), m.getFonction(), Tid_personnel.getText());
       // JOptionPane.showMessageDialog(this, "Materiel modifier ");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_BmodifierpersActionPerformed

    private void BactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BactualiserActionPerformed
  Actualiser();
    }//GEN-LAST:event_BactualiserActionPerformed
 
    private void Tid_personnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tid_personnelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tid_personnelActionPerformed

    private void TtableAdminPersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TtableAdminPersMouseReleased
         Tnompers.setText(String.valueOf(TtableAdminPers.getValueAt(TtableAdminPers.getSelectedRow(),1)));
         Tcodepers.setText(String.valueOf(TtableAdminPers.getValueAt(TtableAdminPers.getSelectedRow(),2)));
         Tfonctionpers.setText(String.valueOf(TtableAdminPers.getValueAt(TtableAdminPers.getSelectedRow(),3)));
         Tid_personnel.setText(String.valueOf(TtableAdminPers.getValueAt(TtableAdminPers.getSelectedRow(),0))); 
         //JOptionPane.showMessageDialog(this,String.valueOf(TtableAdminPers.getValueAt(TtableAdminPers.getSelectedRow(),0)));
// TODO add your handling code here:
    }//GEN-LAST:event_TtableAdminPersMouseReleased

    private void Bsupprimerpers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsupprimerpers1ActionPerformed
             m2.setVisible(true);
             m2.ErreurTexte.setVisible(true);
             m2.ErreurTexte.setText(" Personnel supprimer ");
             d.SupprimerPersonnel(Tid_personnel.getText());
                 }//GEN-LAST:event_Bsupprimerpers1ActionPerformed

    private void deconecterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconecterMousePressed
        MessConfirmation mc=new MessConfirmation();
        mc.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_deconecterMousePressed

    private void ferm1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseEntered
        // TODO add your handling code here:
        ferm2.setVisible(true);
        Fond_Stock.add(ferm2);
        ferm2.setIcon(new ImageIcon(getClass().getResource("/image/ferme.jpg")));
        ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_ferm1MouseEntered

    private void ferm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseExited
        // TODO add your handling code here:
        ferm2.setVisible(false);
    }//GEN-LAST:event_ferm1MouseExited

    private void ferm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferm1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bactualiser;
    public javax.swing.JButton Bajouterpers;
    public javax.swing.JButton Bmodifierpers;
    public javax.swing.JButton Bsupprimerpers1;
    private javax.swing.JLabel Fond_Admin_Pers;
    private javax.swing.JScrollPane JTableAdminPers;
    public javax.swing.JLabel Lcodepers;
    public javax.swing.JLabel Lfonctionpers;
    public javax.swing.JLabel Lnompers;
    public javax.swing.JTextField Tcodepers;
    public javax.swing.JTextField Tfonctionpers;
    private javax.swing.JTextField Tid_personnel;
    public javax.swing.JTextField Tnompers;
    private javax.swing.JTable TtableAdminPers;
    private javax.swing.JLabel barre;
    public javax.swing.JLabel deconecter;
    private javax.swing.JLabel ferm1;
    private javax.swing.JLabel ferm2;
    public javax.swing.JLabel ligneBilan;
    public javax.swing.JLabel ligneBilan1;
    public javax.swing.JLabel ligneBilan2;
    public javax.swing.JLabel retour;
    // End of variables declaration//GEN-END:variables
}
