/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *  
 * @author Snow
 */
public class AdminStock2 extends javax.swing.JFrame {
 
    /**
     * Creates new form AdminStock2
     */
    int xMouse, yMouse;
    public AdminStock2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockligne23 = new javax.swing.JLabel();
        stockligne21 = new javax.swing.JLabel();
        stockligne22 = new javax.swing.JLabel();
        Lnom2 = new javax.swing.JLabel();
        Ldate2 = new javax.swing.JLabel();
        Lquantite2 = new javax.swing.JLabel();
        Tnom2 = new javax.swing.JTextField();
        Tquantite2 = new javax.swing.JTextField();
        Lpersonnel2 = new javax.swing.JLabel();
        Tpersonnel2 = new javax.swing.JComboBox();
        Ltexte12 = new javax.swing.JLabel();
        Table2 = new javax.swing.JScrollPane();
        JTable2 = new javax.swing.JTable();
        Lcommentaire2 = new javax.swing.JLabel();
        Tcommentaire22 = new javax.swing.JScrollPane();
        Tcommentaire2 = new javax.swing.JTextPane();
        Bmodifier2 = new javax.swing.JButton();
        Bsupprimer2 = new javax.swing.JButton();
        Bactualiser2 = new javax.swing.JButton();
        Tdate2 = new javax.swing.JTextField();
        Fond_AStock = new javax.swing.JLabel();
        Tident2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        stockligne23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        stockligne23.setText("jLabel2");
        getContentPane().add(stockligne23);
        stockligne23.setBounds(250, 270, 230, 2);

        stockligne21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        stockligne21.setText("jLabel2");
        getContentPane().add(stockligne21);
        stockligne21.setBounds(250, 150, 230, 2);

        stockligne22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        stockligne22.setText("jLabel2");
        getContentPane().add(stockligne22);
        stockligne22.setBounds(250, 210, 230, 2);

        Lnom2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Lnom2.setForeground(new java.awt.Color(67, 68, 70));
        Lnom2.setText("Nom matériel");
        getContentPane().add(Lnom2);
        Lnom2.setBounds(90, 120, 100, 30);

        Ldate2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Ldate2.setForeground(new java.awt.Color(67, 68, 70));
        Ldate2.setText("Date enregistrement");
        getContentPane().add(Ldate2);
        Ldate2.setBounds(90, 180, 140, 30);

        Lquantite2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Lquantite2.setForeground(new java.awt.Color(67, 68, 70));
        Lquantite2.setText("Quantité");
        getContentPane().add(Lquantite2);
        Lquantite2.setBounds(90, 240, 70, 30);

        Tnom2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Tnom2.setForeground(new java.awt.Color(2, 115, 197));
        Tnom2.setBorder(null);
        Tnom2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Tnom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tnom2ActionPerformed(evt);
            }
        });
        getContentPane().add(Tnom2);
        Tnom2.setBounds(250, 120, 230, 30);

        Tquantite2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Tquantite2.setForeground(new java.awt.Color(2, 115, 197));
        Tquantite2.setBorder(null);
        getContentPane().add(Tquantite2);
        Tquantite2.setBounds(250, 240, 230, 30);

        Lpersonnel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Lpersonnel2.setForeground(new java.awt.Color(67, 68, 70));
        Lpersonnel2.setText("Personnel ");
        getContentPane().add(Lpersonnel2);
        Lpersonnel2.setBounds(540, 240, 80, 30);

        Tpersonnel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        Tpersonnel2.setForeground(new java.awt.Color(2, 115, 197));
        Tpersonnel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tpersonnel2ActionPerformed(evt);
            }
        });
        getContentPane().add(Tpersonnel2);
        Tpersonnel2.setBounds(700, 240, 230, 30);

        Ltexte12.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        Ltexte12.setForeground(new java.awt.Color(2, 115, 197));
        Ltexte12.setText("Listes des materiels en utilisation");
        getContentPane().add(Ltexte12);
        Ltexte12.setBounds(90, 360, 280, 30);

        JTable2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        JTable2.setForeground(new java.awt.Color(67, 68, 70));
        JTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Date", "Nombre", "Commentaire", "Personnel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table2.setViewportView(JTable2);

        getContentPane().add(Table2);
        Table2.setBounds(90, 402, 880, 150);

        Lcommentaire2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Lcommentaire2.setForeground(new java.awt.Color(67, 68, 70));
        Lcommentaire2.setText("Commentaire");
        getContentPane().add(Lcommentaire2);
        Lcommentaire2.setBounds(540, 120, 100, 30);

        Tcommentaire2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tcommentaire2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Tcommentaire2.setForeground(new java.awt.Color(2, 115, 197));
        Tcommentaire22.setViewportView(Tcommentaire2);

        getContentPane().add(Tcommentaire22);
        Tcommentaire22.setBounds(700, 120, 230, 90);

        Bmodifier2.setBackground(new java.awt.Color(12, 46, 76));
        Bmodifier2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Bmodifier2.setForeground(new java.awt.Color(255, 255, 255));
        Bmodifier2.setText("Modifier");
        Bmodifier2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bmodifier2MousePressed(evt);
            }
        });
        getContentPane().add(Bmodifier2);
        Bmodifier2.setBounds(590, 320, 100, 30);

        Bsupprimer2.setBackground(new java.awt.Color(12, 46, 76));
        Bsupprimer2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Bsupprimer2.setForeground(new java.awt.Color(255, 255, 255));
        Bsupprimer2.setText("Supprimer");
        Bsupprimer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bsupprimer2MousePressed(evt);
            }
        });
        Bsupprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsupprimer2ActionPerformed(evt);
            }
        });
        getContentPane().add(Bsupprimer2);
        Bsupprimer2.setBounds(710, 320, 100, 30);

        Bactualiser2.setBackground(new java.awt.Color(12, 46, 76));
        Bactualiser2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Bactualiser2.setForeground(new java.awt.Color(255, 255, 255));
        Bactualiser2.setText("Actualiser");
        Bactualiser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bactualiser2MousePressed(evt);
            }
        });
        Bactualiser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bactualiser2ActionPerformed(evt);
            }
        });
        getContentPane().add(Bactualiser2);
        Bactualiser2.setBounds(830, 320, 100, 30);

        Tdate2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Tdate2.setForeground(new java.awt.Color(2, 115, 197));
        Tdate2.setBorder(null);
        Tdate2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Tdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tdate2ActionPerformed(evt);
            }
        });
        getContentPane().add(Tdate2);
        Tdate2.setBounds(250, 180, 230, 30);

        Fond_AStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Admin_StockV1.jpg"))); // NOI18N
        Fond_AStock.setText("jLabel1");
        getContentPane().add(Fond_AStock);
        Fond_AStock.setBounds(0, 0, 1000, 600);

        Tident2.setText("jTextField1");
        getContentPane().add(Tident2);
        Tident2.setBounds(450, 290, 59, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tnom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tnom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tnom2ActionPerformed

    private void Tpersonnel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tpersonnel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tpersonnel2ActionPerformed

    private void Bmodifier2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bmodifier2MousePressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_Bmodifier2MousePressed

    private void Bsupprimer2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bsupprimer2MousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Bsupprimer2MousePressed

    private void Bsupprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsupprimer2ActionPerformed
        //   enregistrer();
        //  Afficher();// TODO add your handling code here:
    }//GEN-LAST:event_Bsupprimer2ActionPerformed

    private void Bactualiser2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bactualiser2MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Bactualiser2MousePressed

    private void Bactualiser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bactualiser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bactualiser2ActionPerformed

    private void Tdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tdate2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStock2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStock2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStock2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStock2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStock2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bactualiser2;
    public javax.swing.JButton Bmodifier2;
    public javax.swing.JButton Bsupprimer2;
    private javax.swing.JLabel Fond_AStock;
    public javax.swing.JTable JTable2;
    public javax.swing.JLabel Lcommentaire2;
    public javax.swing.JLabel Ldate2;
    public javax.swing.JLabel Lnom2;
    public javax.swing.JLabel Lpersonnel2;
    public javax.swing.JLabel Lquantite2;
    public javax.swing.JLabel Ltexte12;
    public javax.swing.JScrollPane Table2;
    public javax.swing.JTextPane Tcommentaire2;
    public javax.swing.JScrollPane Tcommentaire22;
    public javax.swing.JTextField Tdate2;
    public javax.swing.JTextField Tident2;
    public javax.swing.JTextField Tnom2;
    public javax.swing.JComboBox Tpersonnel2;
    public javax.swing.JTextField Tquantite2;
    public javax.swing.JLabel stockligne21;
    public javax.swing.JLabel stockligne22;
    public javax.swing.JLabel stockligne23;
    // End of variables declaration//GEN-END:variables
}
