/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.Database;
import controler.IDatabase;
import classe.Classe;
import com.caucho.hessian.client.HessianProxyFactory;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import java.util.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafaly Antoni
 */
public class BackMod extends javax.swing.JFrame implements MouseListener{
String val,jour,L,M,M1,J,V,S,D,m1,m2,m3,m4,m5,m6;
String colonneTab []={"Journalier"},colonneTabheb []={"Hebdo"},colonneTabMen []={"Travail Mensuel"},colonneTabTri []={"Travail Trimestriel et Semestriel","Type"};
String colonneTab1 []={"Maintenance du Jour"};
String moisTri []={"Janvier","Fevrier","Mars","Avril","Mai","Juin"},MoisTri2 []={"Juillet","Août","Septembre","Octobre","Novembre","Decembre"};
int xMouse,yMouse;
String strMois;
String strDate;
/*Connection connex;
StringBuffer sql;
ResultSet res;
Statement etat;*/
AfficheHeb af=new AfficheHeb();
pageT trimes=new pageT();

 MessErreur mF= new MessErreur();
 MessVrai mV= new MessVrai();

String page;
Back back = new Back();
     private IDatabase crud = null;
  static private String hoteDist = "http://DESKTOP-VLD2HGD:8080/appView/rpc";  //DESKTOP-VLD2HGD
	static private IDatabase getConnection(String url)
	{
		try 
		{
			HessianProxyFactory factory = new com.caucho.hessian.client.HessianProxyFactory();
			return (IDatabase)factory.create(IDatabase.class,url); 
		}
		catch(Exception e)
		{
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    
			return null;
		}
	}
        
     
     public final void JourAfficher(){
     table1.setModel(new DefaultTableModel(colonneTab,crud.compterContact()));
     try{
     for(int i=0;i<=crud.afficheContact("journalier").size();i++){
                 table1.setValueAt(crud.afficheContact("journalier").get(i).getNomJour(), i, 0);
                 
             }}
     catch(Exception e){System.out.println(e.getMessage());}
     
     }
      
   
     
     
     
     //************************constructeur
     public BackMod() {
        crud = getConnection(hoteDist);
        initComponents();
        
        page="journalier";
        //new NoticeWindow("",NPosition.TOP_LEFT);
        Date date=new Date(); 
        DateFormat dateFormat=new SimpleDateFormat("dd/MM/yyyy");
        DateFormat dateFormat2=new SimpleDateFormat("MM");
        strMois = dateFormat2.format(date);
        //JOptionPane.showMessageDialog(null, strMois);
        strDate=dateFormat.format(date);
        jour=date.toString().substring(0, 3);
        Date1.setText(strDate);
       
        Bjour1.setVisible(false);
        heb2.setVisible(false);
        mens1.setVisible(false);
        tri1.setVisible(false);
        sem1.setVisible(false);
        ajoutMission1.setVisible(false);
        //crud = new DataBase();
        //****************************************************************
        JourAfficher();
        //afficheHebdo();
        Tjour.setVisible(false);
        Cjour.setVisible(false);
        Tsem.setVisible(false);
        Csem.setVisible(false);
        Tmois.setVisible(false);
        Cmois.setVisible(false);
        //**** tableau listener
        
        af.HebdoT.addMouseListener(this);
        af.MensT.addMouseListener(this);
        af.TriT.addMouseListener(this);
       
    }
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ligne11 = new javax.swing.JLabel();
        ligne12 = new javax.swing.JLabel();
        ajoutMission = new javax.swing.JLabel();
        ajoutMission1 = new javax.swing.JLabel();
        deconecter = new javax.swing.JLabel();
        retour1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Cjour = new javax.swing.JComboBox();
        Csem = new javax.swing.JComboBox();
        Cmois = new javax.swing.JComboBox();
        Tjour = new javax.swing.JLabel();
        Tsem = new javax.swing.JLabel();
        Tmois = new javax.swing.JLabel();
        Ttype = new javax.swing.JLabel();
        Tnom = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        type = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        equip = new javax.swing.JTextField();
        list1 = new java.awt.List();
        pane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        ferm1 = new javax.swing.JLabel();
        ferm2 = new javax.swing.JLabel();
        barre = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        Date1 = new javax.swing.JLabel();
        heb1 = new javax.swing.JLabel();
        heb2 = new javax.swing.JLabel();
        Bjour = new javax.swing.JLabel();
        Bjour1 = new javax.swing.JLabel();
        mens = new javax.swing.JLabel();
        mens1 = new javax.swing.JLabel();
        tri = new javax.swing.JLabel();
        tri1 = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        sem1 = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();
        retour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        ligne11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        ligne11.setText("jLabel2");
        getContentPane().add(ligne11);
        ligne11.setBounds(250, 360, 240, 2);

        ligne12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        ligne12.setText("jLabel2");
        getContentPane().add(ligne12);
        ligne12.setBounds(720, 360, 240, 2);

        ajoutMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajoutMissionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajoutMissionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajoutMissionMousePressed(evt);
            }
        });
        getContentPane().add(ajoutMission);
        ajoutMission.setBounds(880, 35, 103, 50);

        ajoutMission1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/Fond-ajoutmissions.jpg"))); // NOI18N
        ajoutMission1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajoutMission1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajoutMission1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajoutMission1MousePressed(evt);
            }
        });
        getContentPane().add(ajoutMission1);
        ajoutMission1.setBounds(880, 35, 103, 50);

        deconecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deconecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deconecterMousePressed(evt);
            }
        });
        getContentPane().add(deconecter);
        deconecter.setBounds(770, 10, 70, 20);

        retour1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retour1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retour1MousePressed(evt);
            }
        });
        getContentPane().add(retour1);
        retour1.setBounds(10, 10, 30, 20);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 115, 197));
        jLabel1.setText("Type de travail");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(730, 128, 230, 30);

        Cjour.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        Cjour.setForeground(new java.awt.Color(2, 115, 197));
        Cjour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi" }));
        getContentPane().add(Cjour);
        Cjour.setBounds(250, 420, 240, 30);

        Csem.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        Csem.setForeground(new java.awt.Color(2, 115, 197));
        Csem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semaine 1", "Semaine 2", "Semaine 3", "Semaine 4", "Semaine 5" }));
        getContentPane().add(Csem);
        Csem.setBounds(250, 420, 240, 30);

        Cmois.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        Cmois.setForeground(new java.awt.Color(2, 115, 197));
        getContentPane().add(Cmois);
        Cmois.setBounds(720, 420, 240, 30);

        Tjour.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Tjour.setForeground(new java.awt.Color(67, 68, 70));
        Tjour.setText("Jour");
        getContentPane().add(Tjour);
        Tjour.setBounds(70, 420, 210, 30);

        Tsem.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Tsem.setForeground(new java.awt.Color(67, 68, 70));
        Tsem.setText("Semaine");
        getContentPane().add(Tsem);
        Tsem.setBounds(70, 420, 120, 30);

        Tmois.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Tmois.setForeground(new java.awt.Color(67, 68, 70));
        Tmois.setText("Mois");
        getContentPane().add(Tmois);
        Tmois.setBounds(540, 420, 210, 30);

        Ttype.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Ttype.setForeground(new java.awt.Color(67, 68, 70));
        Ttype.setText("Type de maintenance");
        getContentPane().add(Ttype);
        Ttype.setBounds(540, 330, 210, 30);

        Tnom.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Tnom.setForeground(new java.awt.Color(67, 68, 70));
        Tnom.setText("Nom equipement");
        getContentPane().add(Tnom);
        Tnom.setBounds(70, 330, 210, 30);

        jButton5.setBackground(new java.awt.Color(12, 46, 73));
        jButton5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(249, 249, 249));
        jButton5.setText("Supprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(860, 260, 100, 30);

        jButton3.setBackground(new java.awt.Color(12, 46, 73));
        jButton3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(249, 249, 249));
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(860, 500, 100, 30);

        type.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        type.setForeground(new java.awt.Color(2, 115, 197));
        type.setBorder(null);
        getContentPane().add(type);
        type.setBounds(720, 330, 240, 30);

        jButton2.setBackground(new java.awt.Color(12, 46, 73));
        jButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(249, 249, 249));
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(740, 500, 100, 30);

        equip.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        equip.setForeground(new java.awt.Color(2, 115, 197));
        equip.setBorder(null);
        getContentPane().add(equip);
        equip.setBounds(250, 330, 240, 30);
        getContentPane().add(list1);
        list1.setBounds(730, 160, 230, 90);

        pane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        table1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        table1.setForeground(new java.awt.Color(0, 102, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table1MouseReleased(evt);
            }
        });
        pane1.setViewportView(table1);

        getContentPane().add(pane1);
        pane1.setBounds(70, 140, 640, 110);

        jButton4.setBackground(new java.awt.Color(12, 46, 73));
        jButton4.setForeground(new java.awt.Color(249, 249, 249));
        jButton4.setText("Ajouter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(890, 380, 69, 23);

        ferm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferm1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferm1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferm1MousePressed(evt);
            }
        });
        getContentPane().add(ferm1);
        ferm1.setBounds(965, 8, 19, 19);
        getContentPane().add(ferm2);
        ferm2.setBounds(961, 7, 19, 19);

        barre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barreMouseDragged(evt);
            }
        });
        barre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barreMousePressed(evt);
            }
        });
        getContentPane().add(barre);
        barre.setBounds(0, 0, 50, 600);

        titre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        titre.setForeground(new java.awt.Color(2, 115, 197));
        titre.setText("Modification du maintenance Préventive ");
        getContentPane().add(titre);
        titre.setBounds(70, 94, 480, 40);

        Date1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        Date1.setForeground(new java.awt.Color(2, 115, 197));
        Date1.setText("Date");
        getContentPane().add(Date1);
        Date1.setBounds(560, 100, 210, 30);

        heb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                heb1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                heb1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                heb1MousePressed(evt);
            }
        });
        getContentPane().add(heb1);
        heb1.setBounds(473, 35, 103, 50);

        heb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/hebdo.jpg"))); // NOI18N
        getContentPane().add(heb2);
        heb2.setBounds(473, 35, 103, 50);

        Bjour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BjourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BjourMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BjourMousePressed(evt);
            }
        });
        getContentPane().add(Bjour);
        Bjour.setBounds(371, 35, 103, 50);

        Bjour1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/journalier.jpg"))); // NOI18N
        Bjour1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bjour1MousePressed(evt);
            }
        });
        getContentPane().add(Bjour1);
        Bjour1.setBounds(371, 35, 103, 50);

        mens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mensMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mensMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mensMousePressed(evt);
            }
        });
        getContentPane().add(mens);
        mens.setBounds(575, 35, 103, 50);

        mens1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/mensuel.jpg"))); // NOI18N
        mens1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mens1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mens1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mens1MousePressed(evt);
            }
        });
        getContentPane().add(mens1);
        mens1.setBounds(575, 35, 103, 50);

        tri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                triMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                triMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                triMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                triMouseReleased(evt);
            }
        });
        getContentPane().add(tri);
        tri.setBounds(677, 35, 103, 50);

        tri1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/trimestre.jpg"))); // NOI18N
        tri1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tri1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tri1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tri1MousePressed(evt);
            }
        });
        getContentPane().add(tri1);
        tri1.setBounds(677, 35, 103, 50);

        sem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                semMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                semMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                semMousePressed(evt);
            }
        });
        getContentPane().add(sem);
        sem.setBounds(780, 35, 103, 50);

        sem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/semestre.jpg"))); // NOI18N
        sem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sem1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sem1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sem1MousePressed(evt);
            }
        });
        getContentPane().add(sem1);
        sem1.setBounds(780, 35, 103, 50);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/Admin-Calendrier.jpg"))); // NOI18N
        fond.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fondMousePressed(evt);
            }
        });
        getContentPane().add(fond);
        fond.setBounds(0, 0, 1000, 600);

        retour.setText("jLabel1");
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(4, 80, 40, 100);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barreMouseDragged

    private void barreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_barreMousePressed

    private void table1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseReleased
        // TODO add your handling code here:
        
       if(evt.getSource()==table1){
           list1.removeAll();
          // afficheContact();
           val = String.valueOf(table1.getValueAt(table1.getSelectedRow(), 0));
           equip.setText(val);
           click("journalier", "NomJour", val, "idJour");
           list1.select(0);
          // teste.setText(String.valueOf(table1.getValueAt(table1.getSelectedRow(), 0)));
          
          JourAfficher();
           
       } 
    }//GEN-LAST:event_table1MouseReleased

    private void fondMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fondMousePressed

    private void BjourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BjourMousePressed
        // TODO add your handling code here:
        page="journalier";
        pane1.setVisible(true);
        list1.setVisible(true);
        equip.setText("");
        list1.removeAll();
        //** HEB//
        JourAfficher();
        HebFalse();
        MenFalse();
        //******
         //**************
        SemFalse();
        TrimFalse();
        Tjour.setVisible(false);
        Cjour.setVisible(false);
        Tsem.setVisible(false);
        Csem.setVisible(false);
        Tmois.setVisible(false);
        Cmois.setVisible(false);
        click("journalier", "NomJour", val, "idJour");
      //******************
    }//GEN-LAST:event_BjourMousePressed

    private void Bjour1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bjour1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bjour1MousePressed

    private void BjourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BjourMouseEntered
        // TODO add your handling code here:
        Bjour1.setVisible(true);
//         fond.add(Bjour1);
//        Bjour1.setIcon(new ImageIcon(getClass().getResource("/sary/journalier.jpg")));
         //ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_BjourMouseEntered

    private void BjourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BjourMouseExited
        // TODO add your handling code here:
        Bjour1.setVisible(false);
    }//GEN-LAST:event_BjourMouseExited

    private void heb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heb1MouseEntered
        // TODO add your handling code here:
       heb2.setVisible(true);
//         fond.add( heb2);
  //       heb2.setIcon(new ImageIcon(getClass().getResource("/sary/hebdo.jpg")));
    }//GEN-LAST:event_heb1MouseEntered

    private void heb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heb1MouseExited
        // TODO add your handling code here:
        heb2.setVisible(false);
    }//GEN-LAST:event_heb1MouseExited

    private void heb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heb1MousePressed
        // TODO add your handling code here:
         page = "hebdomadaire";
         JourFalse();
         //**************
         MenFalse();
        equip.setText("");
        list1.removeAll();
        SemFalse();
        TrimFalse();
        
      //******************
        
        //******
        af.HebdoT.setModel(new DefaultTableModel(new String[]{"Equipement","Jour de travail"}, 4));
        af.HebdoT.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        af.HebdoT.setForeground(new java.awt.Color(0, 102, 255));
        
        af.PhebdoT.setVisible(true);
        fond.add(af.PhebdoT);
        pageHebdo();
        Tjour.setVisible(true);
        Cjour.setVisible(true);
        
    }//GEN-LAST:event_heb1MousePressed

    private void mensMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mensMouseEntered
        // TODO add your handling code here:
        mens1.setVisible(true);
//         fond.add( mens1);
//         mens1.setIcon(new ImageIcon(getClass().getResource("/sary/mensuel.jpg")));
    }//GEN-LAST:event_mensMouseEntered

    private void mensMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mensMouseExited
        // TODO add your handling code here:
        mens1.setVisible(false);
    }//GEN-LAST:event_mensMouseExited

    private void mensMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mensMousePressed
        // TODO add your handling code here:
        page = "mensuel";
        equip.setText("");
        list1.removeAll();
        HebFalse();
        JourFalse();
        TrimFalse();
        af.PmensT.setVisible(true);
        fond.add(af.PmensT);
        af.MensT.setModel(new DefaultTableModel(new String[]{"Equipement","Semaine de travail"}, 4));
        af.MensT.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        af.MensT.setForeground(new java.awt.Color(0, 102, 255));
        
        pageMensuel();
        Tsem.setVisible(true);
        Csem.setVisible(true);
        //**************
    }//GEN-LAST:event_mensMousePressed

    private void mens1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mens1MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mens1MouseEntered

    private void mens1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mens1MouseExited
        // TODO add your handling code here:
      
    }//GEN-LAST:event_mens1MouseExited

    private void mens1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mens1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mens1MousePressed

    private void triMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triMouseEntered
        // TODO add your handling code here:
         tri1.setVisible(true);
//         fond.add( tri1);
//         tri1.setIcon(new ImageIcon(getClass().getResource("/sary/trimestre.jpg")));
    }//GEN-LAST:event_triMouseEntered

    private void triMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triMouseExited
        // TODO add your handling code here:
          tri1.setVisible(false);
    }//GEN-LAST:event_triMouseExited

    private void triMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triMousePressed
        // TODO add your handling code here:
        Cmois.removeAll();
        Cmois.setModel(new javax.swing.DefaultComboBoxModel(back.mois1));
        page = "trisem";
        equip.setText("");
        list1.removeAll();
         HebFalse();
         MenFalse();
        //*********affichage*******
        JourFalse();
        //*****************
        af.PtriT.setVisible(true);
         fond.add(af.PtriT);
        af.TriT.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        af.TriT.setForeground(new java.awt.Color(0, 102, 255));
        
        //af.TriT.setModel(new DefaultTableModel(new String[]{"Equipement","Semaine de travail","Mois de travail"}, 4));
        affichePageTrim();
        //SemFalse();
        Tsem.setVisible(true);
        Csem.setVisible(true);
        Tmois.setVisible(true);
        Cmois.setVisible(true);
       
        
    }//GEN-LAST:event_triMousePressed

    private void tri1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tri1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tri1MouseEntered

    private void tri1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tri1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tri1MouseExited

    private void tri1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tri1MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tri1MousePressed

    private void semMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semMouseEntered
        // TODO add your handling code here:
       sem1.setVisible(true);
//         fond.add( sem1);
//         sem1.setIcon(new ImageIcon(getClass().getResource("/sary/semestre.jpg")));
    }//GEN-LAST:event_semMouseEntered

    private void semMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semMouseExited
        // TODO add your handling code here:
        sem1.setVisible(false);
    }//GEN-LAST:event_semMouseExited

    private void semMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semMousePressed
        // TODO add your handling code here:
        Cmois.removeAll();
        Cmois.setModel(new javax.swing.DefaultComboBoxModel(back.mois2));
        page = "trisem2";
        equip.setText("");
        list1.removeAll();
        JourFalse();
        //*********affichage*******
        MenFalse();
        HebFalse();
        //af..setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
//        table1.setForeground(new java.awt.Color(0, 102, 255));
        
        fond.add(af.PtriT);
        af.PtriT.setVisible(true);
        affichePageSem();
        Tsem.setVisible(true);
        Csem.setVisible(true);
        Tmois.setVisible(true);
        Cmois.setVisible(true);
        
        
        //*****************
      
        
    }//GEN-LAST:event_semMousePressed

    private void sem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1MouseEntered

    private void sem1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1MouseExited

    private void sem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1MousePressed

    private void triMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triMouseReleased
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_triMouseReleased

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        // TODO add your handling code here:
        setVisible(false);
        Accueil ac = new Accueil();
        ac.setVisible(true);
    }//GEN-LAST:event_retourMousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, list1.getSelectedIndex());
            if(list1.getSelectedIndex()==-1){
             mF.setVisible(true);
             mF.ErreurTexte.setVisible(true);
             mF.ErreurTexte.setText("Verifier bien liste du type de travail");
             
         //JOptionPane.showMessageDialog(null, "Verifier bien liste du type de travail");
        }
           else{
            try{
            crud.DeleteTaf(list1.getSelectedItem());
            list1.remove(list1.getSelectedItem());
            mV.setVisible(true);
             mV.ErreurTexte.setVisible(true);
             mV.ErreurTexte.setText(" Suppression ");
             
            }
            catch(Exception e){JOptionPane.showMessageDialog(null, e.getMessage()); }
         //JOptionPane.showMessageDialog(null, list1.countItems());   
        
        }
        
        //*********
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(page.equals("journalier")){
             if(type.getText().trim().equals("")){
             mF.setVisible(true);
             mF.ErreurTexte.setVisible(true);
             mF.ErreurTexte.setText(" Champ vide ");
             
                 //JOptionPane.showMessageDialog(null, "Champ vide");
             }else{
            try{
                crud.AddTaf(type.getText(), crud.AddMaxAjout("journalier", "NomJour", val), 0, 0, 0);
            }
            catch(Exception e){System.out.println(e.getMessage());}
             }
             list1.add(type.getText());
        }
        //*************
         if(page.equals("hebdomadaire")){
             if(type.getText().trim().equals("")){
            mF.setVisible(true);
             mF.ErreurTexte.setVisible(true);
             mF.ErreurTexte.setText(" Champ vide ");
                            
//  JOptionPane.showMessageDialog(null, "Champ vide");
             }else{
            try{
                crud.AddTaf(type.getText(), 0, crud.AddMaxAjout("hebdomadaire", "NomHebdo", af.HebdoT.getValueAt(af.HebdoT.getSelectedRow(), 0).toString()), 0, 0);
            }
            catch(Exception e){System.out.println(e.getMessage());}
             }
             list1.add(type.getText());
        }
         //*************
         if(page.equals("mensuel")){
             if(type.getText().trim().equals("")){
             mF.setVisible(true);
             mF.ErreurTexte.setVisible(true);
             mF.ErreurTexte.setText(" Champ vide ");
             
//    JOptionPane.showMessageDialog(null, "Champ vide");
         }else{
            try{
                crud.AddTaf(type.getText(), 0, 0, crud.AddMaxAjout("mensuel", "NomMen", af.MensT.getValueAt(af.MensT.getSelectedRow(), 0).toString()), 0);
            }
            catch(Exception e){System.out.println(e.getMessage());}
             }
             list1.add(type.getText());
        }
         //*************
         if(page.equals("trisem")){
             if(type.getText().trim().equals("")){
             mF.setVisible(true);
             mF.ErreurTexte.setVisible(true);
             mF.ErreurTexte.setText(" Champ vide ");
             //    JOptionPane.showMessageDialog(null, "Champ vide");
             }else{
            try{
                crud.AddTaf(type.getText(), 0, 0, 0, crud.AddMaxAjout("trisem", "NomTri", af.TriT.getValueAt(af.TriT.getSelectedRow(), 0).toString()));
            }
            catch(Exception e){System.out.println(e.getMessage());}
             }
             list1.add(type.getText());
        }
         if(page.equals("trisem2")){
             if(type.getText().trim().equals("")){
             mF.setVisible(true);
             mF.ErreurTexte.setVisible(true);
             mF.ErreurTexte.setText(" Champ vide ");
             
//    JOptionPane.showMessageDialog(null, "Champ vide");
             }else{
            try{
                
                crud.AddTaf(type.getText(), 0, 0, 0, crud.AddMaxAjout("trisem", "NomTri", af.TriT.getValueAt(af.TriT.getSelectedRow(), 0).toString()));
            }
            catch(Exception e){System.out.println(e.getMessage());}
             }
             list1.add(type.getText());
        }
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(page.equals("journalier")){
            deleteList();
            try{
            mV.setVisible(true);
            mV.ErreurTexte.setVisible(true);
            mV.ErreurTexte.setText(" Suppression reussi ");    
            crud.DeleteAll(page, val, "NomJour");
            JourAfficher();
            }
            catch(Exception e){System.out.println(e.getMessage());}
            
        }
        if(page.equals("hebdomadaire")){
            deleteList();
            try{
            mV.setVisible(true);
            mV.ErreurTexte.setVisible(true);
            mV.ErreurTexte.setText(" Suppression reussi ");    
            crud.DeleteAll(page, af.HebdoT.getValueAt(af.HebdoT.getSelectedRow(), 0).toString(), "NomHebdo");
                    pageHebdo();
            }
            catch(Exception e){System.out.println(e.getMessage());} 
        }
        if(page.equals("mensuel")){
            deleteList();
            try{
            mV.setVisible(true);
            mV.ErreurTexte.setVisible(true);
            mV.ErreurTexte.setText(" Suppression reussi ");    
            crud.DeleteAll(page, af.MensT.getValueAt(af.MensT.getSelectedRow(), 0).toString(), "NomMen");
                    pageMensuel();
            }
            catch(Exception e){System.out.println(e.getMessage());} 
        }
        if(page.equals("trisem")){
            deleteList();
            try{
            mV.setVisible(true);
            mV.ErreurTexte.setVisible(true);
            mV.ErreurTexte.setText(" Suppression reussi ");    
                
            crud.DeleteAll(page, af.TriT.getValueAt(af.TriT.getSelectedRow(), 0).toString(), "NomTri");
               affichePageTrim();
            }
            catch(Exception e){System.out.println(e.getMessage());} 
        }
        if(page.equals("trisem2")){
            deleteList();
            try{
            mV.setVisible(true);
            mV.ErreurTexte.setVisible(true);
            mV.ErreurTexte.setText(" Suppression reussi ");    
            crud.DeleteAll("trisem", af.TriT.getValueAt(af.TriT.getSelectedRow(), 0).toString(), "NomTri");
               affichePageSem();
            }
            catch(Exception e){System.out.println(e.getMessage());} 
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(page.equals("journalier")){
            ModifierList();
            JourAfficher();
            if(equip.getText().trim().equals("")){
                   // JOptionPane.showMessageDialog(null, "Verifier le champ");
            mF.setVisible(true);
             mF.ErreurTexte.setVisible(true);
             mF.ErreurTexte.setText(" Verifier le champ ");
             
        }else{
                try{
            //crud.DeleteAll(page, val, "NomJour");
                mV.setVisible(true);
                mV.ErreurTexte.setVisible(true);
                mV.ErreurTexte.setText(" Modification reussi ");
                crud.modifierjour("journalier", val, "NomJour", equip.getText());
                //JourAfficher();
            }
            catch(Exception e){System.out.println(e.getMessage());}
            }
        }
        if(page.equals("hebdomadaire")){
            ModifierList();
            try{
            //crud.DeleteAll(page, val, "NomJour");
                // af.HebdoT.getValueAt(af.HebdoT.getSelectedRow(), 0).toString()
                if(equip.getText().trim().equals("")){
                 mF.setVisible(true);
                 mF.ErreurTexte.setVisible(true);
                 mF.ErreurTexte.setText(" Verifier le champ ");
                
                
                 //   JOptionPane.showMessageDialog(null, "Verifier le champ");
                }else{
                mV.setVisible(true);
                mV.ErreurTexte.setVisible(true);
                mV.ErreurTexte.setText(" Modification reussi ");    
                crud.modifierHeb("hebdomadaire", af.HebdoT.getValueAt(af.HebdoT.getSelectedRow(), 0).toString(), "NomHebdo", "Jour", equip.getText(), Cjour.getSelectedItem().toString());
            pageHebdo();}
            }
            catch(Exception e){System.out.println(e.getMessage());}
            
        }
        if(page.equals("mensuel")){
            ModifierList();
            try{
            //crud.DeleteAll(page, val, "NomJour");
                // af.HebdoT.getValueAt(af.HebdoT.getSelectedRow(), 0).toString()
                if(equip.getText().trim().equals("")){
                    mF.setVisible(true);
                    mF.ErreurTexte.setVisible(true);
                    mF.ErreurTexte.setText(" Champ vide ");
             
                }
                    //JOptionPane.showMessageDialog(null, "Verifier le champ");
                else
                 mV.setVisible(true);
                 mV.ErreurTexte.setVisible(true);
                 mV.ErreurTexte.setText(" Modification reussi ");
                
                crud.modifierHeb("mensuel", af.MensT.getValueAt(af.MensT.getSelectedRow(), 0).toString(), "NomMen", "Semaine", equip.getText(), Csem.getSelectedItem().toString());
            pageMensuel();
            }
            catch(Exception e){System.out.println(e.getMessage());}
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void retour1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retour1MousePressed
        // TODO add your handling code here:
        Accueil_Admin acad = new Accueil_Admin();
        acad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retour1MousePressed

    private void deconecterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconecterMousePressed
        MessConfirmation mc=new MessConfirmation();
        mc.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_deconecterMousePressed

    private void ajoutMissionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMissionMouseEntered
         ajoutMission1.setVisible(true);
//         fond.add( ajoutMission1);
//         ajoutMission1.setIcon(new ImageIcon(getClass().getResource("/sary/Fond-ajoutmissions.jpg")));        // TODO add your handling code here:
    }//GEN-LAST:event_ajoutMissionMouseEntered

    private void ajoutMissionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMissionMouseExited
        ajoutMission1.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_ajoutMissionMouseExited

    private void ajoutMissionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMissionMousePressed
    Back back = new Back();
    back.setVisible(true);
    this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_ajoutMissionMousePressed

    private void ajoutMission1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMission1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ajoutMission1MouseEntered

    private void ajoutMission1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMission1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ajoutMission1MouseExited

    private void ajoutMission1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMission1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajoutMission1MousePressed

    private void ferm1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseEntered
        // TODO add your handling code here:
        ferm2.setVisible(true);
        fond.add(ferm2);
        ferm2.setIcon(new ImageIcon(getClass().getResource("/image/ferme.jpg")));
        ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_ferm1MouseEntered

    private void ferm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseExited
        // TODO add your handling code here:
        ferm2.setVisible(false);
    }//GEN-LAST:event_ferm1MouseExited

    private void ferm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferm1MousePressed
   
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackMod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bjour;
    private javax.swing.JLabel Bjour1;
    private javax.swing.JComboBox Cjour;
    private javax.swing.JComboBox Cmois;
    private javax.swing.JComboBox Csem;
    private javax.swing.JLabel Date1;
    private javax.swing.JLabel Tjour;
    private javax.swing.JLabel Tmois;
    private javax.swing.JLabel Tnom;
    private javax.swing.JLabel Tsem;
    private javax.swing.JLabel Ttype;
    private javax.swing.JLabel ajoutMission;
    private javax.swing.JLabel ajoutMission1;
    private javax.swing.JLabel barre;
    public javax.swing.JLabel deconecter;
    private javax.swing.JTextField equip;
    private javax.swing.JLabel ferm1;
    private javax.swing.JLabel ferm2;
    public javax.swing.JLabel fond;
    private javax.swing.JLabel heb1;
    private javax.swing.JLabel heb2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel ligne11;
    public javax.swing.JLabel ligne12;
    private java.awt.List list1;
    private javax.swing.JLabel mens;
    private javax.swing.JLabel mens1;
    private javax.swing.JScrollPane pane1;
    private javax.swing.JLabel retour;
    public javax.swing.JLabel retour1;
    private javax.swing.JLabel sem;
    private javax.swing.JLabel sem1;
    private javax.swing.JTable table1;
    private javax.swing.JLabel titre;
    private javax.swing.JLabel tri;
    private javax.swing.JLabel tri1;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables

   

    private void afficheMois() {
        if(strMois.equals("01")){
           af.Tmois.setModel(new DefaultTableModel(new String []{"Janvier"},1));
        }
        if(strMois.equals("02"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Février"},1));
        if(strMois.equals("03"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Mars"},1));
        if(strMois.equals("04"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Avril"},1));
        if(strMois.equals("05"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Mai"},1));
        if(strMois.equals("06"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Juin"},1));
        if(strMois.equals("07"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Juillet"},1));
        if(strMois.equals("08"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Août"},1));
        if(strMois.equals("09"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Septembre"},1));
        if(strMois.equals("10"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Octobre"},1));
        if(strMois.equals("11"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Novembre"},1));
        if(strMois.equals("12"))
           af.Tmois.setModel(new DefaultTableModel(new String []{"Decembre"},1));
    }
    // condition pour semaine 5 et semaine 4 du mensuel
    private void conditionMois(){
       
    if(strMois.equals("01") || strMois.equals("04")|| strMois.equals("07")|| strMois.equals("10")){
         af.paneMois.setBounds(114, 135, 608, 20);
         fond.add(af.panes5);
         af.panes5.setVisible(true);
         //eto ni mois
         try{
        af.sem5.setModel(new DefaultTableModel(new String[]{"Semaine 5"},5)); 
        
             for(int i=0;i<=crud.afficheMensuel("Semaine 5").size();i++){
                 af.sem5.setValueAt(crud.afficheMensuel("Semaine 5").get(i).getNomHeb(), i, 0);}}
     catch(Exception e){System.out.println(e.getMessage());}
          
        }
    else{
        af.paneMois.setBounds(114, 135, 485, 40);
        af.panes5.setVisible(false);
        try{
        af.sem4.setModel(new DefaultTableModel(new String[]{"Semaine 4"},5)); 
        
             for(int i=0;i<=crud.afficheMensuelCond().size();i++){
                 af.sem4.setValueAt(crud.afficheMensuelCond().get(i).getNomHeb(), i, 0);}}
     catch(Exception e){System.out.println(e.getMessage());}
    }
    }
    private void TrimFalse(){
        //**************
        
        af.PtriT.setVisible(false);
        Tsem.setVisible(false);
        Csem.setVisible(false);
        Tmois.setVisible(false);
        Cmois.setVisible(false);
    }
    private void SemFalse(){
     trimes.Ptmois.setVisible(false);
        trimes.Ptmois5.setVisible(false);
        trimes.Ptmois12.setVisible(false);
        trimes.Ptmois1.setVisible(false);
        trimes.Ptmois2.setVisible(false);
        trimes.Ptmois3.setVisible(false);
        trimes.Ptmois4.setVisible(false);
        trimes.Ptmois6.setVisible(false);
        trimes.Ptmois7.setVisible(false);
        trimes.Ptmois8.setVisible(false);
        trimes.Ptmois9.setVisible(false);
        trimes.Ptmois10.setVisible(false);
        trimes.Ptmois11.setVisible(false);
        trimes.Ptmois13.setVisible(false);
        trimes.Ptmois14.setVisible(false);
         af.panes5.setVisible(false);
        Tsem.setVisible(false);
        Csem.setVisible(false);
        Tmois.setVisible(false);
        Cmois.setVisible(false);
    }
    private void HebFalse(){
         Tjour.setVisible(false);
        Cjour.setVisible(false);
          af.PhebdoT.setVisible(false);
        //******
       
    }
    private void JourFalse(){
        pane1.setVisible(false);
        
        //list1.setVisible(false);
    }
    private void MenFalse(){
        Tsem.setVisible(false);
        Csem.setVisible(false);
        af.PmensT.setVisible(false);
    }
       public void AfficheTmois() {
        if(strMois.equals("01") || strMois.equals("02") || strMois.equals("03") ){
        trimes.mois1.setModel(new DefaultTableModel(new String[]{"Janvier"},0));
        trimes.mois2.setModel(new DefaultTableModel(new String[]{"Fevrier"},0));
        trimes.mois3.setModel(new DefaultTableModel(new String[]{"Mars"},0));
        }
        if(strMois.equals("04") || strMois.equals("05") || strMois.equals("06") ){
        trimes.mois1.setModel(new DefaultTableModel(new String[]{"Avril"},0));
        trimes.mois2.setModel(new DefaultTableModel(new String[]{"Mai"},0));
        trimes.mois3.setModel(new DefaultTableModel(new String[]{"Juin"},0));
        }
        if(strMois.equals("07") || strMois.equals("08") || strMois.equals("09") ){
        trimes.mois1.setModel(new DefaultTableModel(new String[]{"Juillet"},0));
        trimes.mois2.setModel(new DefaultTableModel(new String[]{"Août"},0));
        trimes.mois3.setModel(new DefaultTableModel(new String[]{"Septembre"},0));
        }
        if(strMois.equals("10") || strMois.equals("11") || strMois.equals("12") ){
        trimes.mois1.setModel(new DefaultTableModel(new String[]{"Octobre"},0));
        trimes.mois2.setModel(new DefaultTableModel(new String[]{"Novembre"},0));
        trimes.mois3.setModel(new DefaultTableModel(new String[]{"Décembre"},0));
        }
        
        //***************
        if(strMois.equals("01")){
         trimes.Pmois.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        }
        if(strMois.equals("02")){
            trimes.Pmois1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
           }
        if(strMois.equals("03"))
          trimes.Pmois2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        if(strMois.equals("04"))
          trimes.Pmois.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        if(strMois.equals("05"))
          trimes.Pmois1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        if(strMois.equals("06"))
          trimes.Pmois2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        if(strMois.equals("07"))
           
        if(strMois.equals("08"))
          
        if(strMois.equals("09"))
           
        if(strMois.equals("10"))
          
        if(strMois.equals("11"))
           
        if(strMois.equals("12"))
          trimes.mois1.setForeground(Color.red); 
            
    }


    private void pageHebdo() {
        try{
         af.HebdoT.setModel(new DefaultTableModel(new String[]{"Equipement","Jour de travail"}, crud.afficheAllHebdo("hebdomadaire").size()));
             for(int i=0;i<=crud.afficheAllHebdo("hebdomadaire").size();i++){
                 af.HebdoT.setValueAt( crud.afficheAllHebdo("hebdomadaire").get(i).getNomHeb(), i, 0);
                 af.HebdoT.setValueAt( crud.afficheAllHebdo("hebdomadaire").get(i).getJour(), i, 1);
             }
        }
     catch(Exception e){System.out.println(e.getMessage());}
        
       
    }
    private void pageMensuel(){
    try{
         af.MensT.setModel(new DefaultTableModel(new String[]{"Equipement","Semaine de travail"}, crud.afficheAllHebdo("mensuel").size()));
             for(int i=0;i<=crud.afficheAllHebdo("mensuel").size();i++){
                 af.MensT.setValueAt( crud.afficheAllHebdo("mensuel").get(i).getNomHeb(), i, 0);
                 af.MensT.setValueAt( crud.afficheAllHebdo("mensuel").get(i).getJour(), i, 1);
             }
        }
     catch(Exception e){System.out.println(e.getMessage());}
    }

    private void affichePageTrim() {
        String table="trisem",type="Trimestre";
        try{System.out.println( crud.afficheAllTrim(table, type).size());
         af.TriT.setModel(new DefaultTableModel(new String[]{"Equipement","Semaine de travail","Mois de travail 2"},  crud.afficheAllTrim(table, type).size()));
             for(int i=0;i<= crud.afficheAllTrim(table, type).size();i++){
                 af.TriT.setValueAt(  crud.afficheAllTrim(table, type).get(i).getNomTri(), i, 0);
                 af.TriT.setValueAt( crud.afficheAllTrim(table, type).get(i).getSemaine(), i, 1);
                 af.TriT.setValueAt( crud.afficheAllTrim(table, type).get(i).getMois(), i, 2);
             }
        }
     catch(Exception e){System.out.println(e.getMessage());}
    }
    private void affichePageSem() {
        String table="trisem",type="Semestre";
        try{System.out.println( crud.afficheAllTrim(table, type).size());
         af.TriT.setModel(new DefaultTableModel(new String[]{"Equipement","Semaine de travail","Mois de travail 2"},  crud.afficheAllTrim(table, type).size()));
             for(int i=0;i<= crud.afficheAllTrim(table, type).size();i++){
                 af.TriT.setValueAt(  crud.afficheAllTrim(table, type).get(i).getNomTri(), i, 0);
                 af.TriT.setValueAt( crud.afficheAllTrim(table, type).get(i).getSemaine(), i, 1);
                 af.TriT.setValueAt( crud.afficheAllTrim(table, type).get(i).getMois(), i, 2);
             }
        }
     catch(Exception e){System.out.println(e.getMessage());}
    }
    private ArrayList<Classe> AfficheNotif(){
        ArrayList<Classe> list = new ArrayList<Classe>();
        Classe data;
        if(strMois.equals("01")||strMois.equals("07")){
            for(int i=0;i<crud.afficheNotif("Mois 1").size();i++){
                data = new Classe(crud.afficheNotif("Mois 1").get(i).getNomTri());
                list.add(data);
            }
        }
        //******
        if(strMois.equals("02")||strMois.equals("08")){
            for(int i=0;i<crud.afficheNotif("Mois 2").size();i++){
                data = new Classe(crud.afficheNotif("Mois 2").get(i).getNomTri());
                list.add(data);
            }
        }
        //******
        if(strMois.equals("03")||strMois.equals("09")){
            for(int i=0;i<crud.afficheNotif("Mois 3").size();i++){
                data = new Classe(crud.afficheNotif("Mois 3").get(i).getNomTri());
                list.add(data);
            }
        }
        //******
        if(strMois.equals("04")||strMois.equals("10")){
            for(int i=0;i<crud.afficheNotif("Mois 4").size();i++){
                data = new Classe(crud.afficheNotif("Mois 4").get(i).getNomTri());
                list.add(data);}
             for(int i=0;i<crud.afficheNotif("Mois 1").size();i++){
                data = new Classe(crud.afficheNotif("Mois 1").get(i).getNomTri());
                list.add(data);
            }
        }
        //******
        if(strMois.equals("05")||strMois.equals("11")){
            for(int i=0;i<crud.afficheNotif("Mois 5").size();i++){
                data = new Classe(crud.afficheNotif("Mois 5").get(i).getNomTri());
                list.add(data);}
             for(int i=0;i<crud.afficheNotif("Mois 2").size();i++){
                data = new Classe(crud.afficheNotif("Mois 2").get(i).getNomTri());
                list.add(data);
            }
        }
        if(strMois.equals("06")||strMois.equals("12")){
            for(int i=0;i<crud.afficheNotif("Mois 6").size();i++){
                data = new Classe(crud.afficheNotif("Mois 6").get(i).getNomTri());
                list.add(data);}
             for(int i=0;i<crud.afficheNotif("Mois 3").size();i++){
                data = new Classe(crud.afficheNotif("Mois 3").get(i).getNomTri());
                list.add(data);
            }
        }
        for(int i=0;i<crud.afficheMensuel().size();i++){
                data = new Classe(crud.afficheMensuel().get(i).getNomHeb());
                list.add(data);
        }
        return list;
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
      if(e.getSource()==af.HebdoT){
          equip.setText(String.valueOf(af.HebdoT.getValueAt(af.HebdoT.getSelectedRow(), 0)));
          Cjour.setSelectedItem(af.HebdoT.getValueAt(af.HebdoT.getSelectedRow(), 1).toString());
          list1.removeAll();
          click("hebdomadaire", "NomHebdo", af.HebdoT.getValueAt(af.HebdoT.getSelectedRow(), 0).toString(), "idHebdo");
          list1.select(0);
      }
      if(e.getSource()==af.MensT){
          equip.setText(String.valueOf(af.MensT.getValueAt(af.MensT.getSelectedRow(), 0)));
          Csem.setSelectedItem(af.MensT.getValueAt(af.MensT.getSelectedRow(), 1).toString());
          list1.removeAll();
          click("mensuel", "NomMen", af.MensT.getValueAt(af.MensT.getSelectedRow(), 0).toString(), "IdMen");
          list1.select(0);
      }
      if(e.getSource()==af.TriT){
          equip.setText(String.valueOf(af.TriT.getValueAt(af.TriT.getSelectedRow(), 0)));
          Csem.setSelectedItem(af.TriT.getValueAt(af.TriT.getSelectedRow(), 1).toString());
          Cmois.setSelectedItem(af.TriT.getValueAt(af.TriT.getSelectedRow(), 2).toString());
          list1.removeAll();
          click("trisem", "NomTri", af.TriT.getValueAt(af.TriT.getSelectedRow(), 0).toString(), "IdTri");
          list1.select(0);
      }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }
private void click(String table, String nomC, String condition, String id){
 try{
 for(int i = 0; i<=crud.compter2(table, nomC, condition, id).size();i++){
     list1.add(crud.compter2(table, nomC, condition, id).get(i).getNomJour());
 }
 }
 catch(Exception e){}
}

    private void deleteList() {
        for(int i = 0;i<list1.countItems();i++)
            {
                list1.select(i);
                crud.DeleteTaf(list1.getSelectedItem());
            }
        list1.removeAll();
    }

    private void ModifierList() {
        if(list1.getSelectedItem()==null){
            mF.setVisible(true);
             mF.ErreurTexte.setVisible(true);
             mF.ErreurTexte.setText(" Liste du type vide ");
            //JOptionPane.showMessageDialog(this, "Liste du type vide");
           
        }
        else{
            if(type.getText().trim().equals("")){
                mF.setVisible(true);
             mF.ErreurTexte.setVisible(true);
             mF.ErreurTexte.setText(" Liste du type vide ");
                //JOptionPane.showMessageDialog(this, "Champ du type vide");
            }   else{
                try{
            crud.modifierjour("taf", list1.getSelectedItem(), "NomTaf",type.getText());}
            catch(Exception e){JOptionPane.showMessageDialog(null, e.getMessage());}}   }
    }

    
}
