/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.Database;
import controler.IDatabase;
import com.caucho.hessian.client.HessianProxyFactory;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.print.PrinterException;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/** 
 *
 * @author Rafaly Antoni
 */
public class Livre extends javax.swing.JFrame {

    //IDataBase crud = new DataBase();  
    String page = "journalier";
    int xMouse, yMouse;
   String teste[]={"Date","Heure","semaine Prevue","Periodicite","Equipement","Type","Observation","Acteur"};
 
 String teste2[]={"Date","Heure","semaine Prevue","Périodicite","Equipement","Type","Observation","Acteur"};
    /**
     * Creates new form Livre
     */
  private IDatabase crud = null;
  static private String hoteDist = "http://DESKTOP-VLD2HGD:8080/appView/rpc";  //DESKTOP-VLD2HGD
	static private IDatabase getConnection(String url)
	{
		try 
		{
			HessianProxyFactory factory = new com.caucho.hessian.client.HessianProxyFactory();
			return (IDatabase)factory.create(IDatabase.class,url); 
		}
		catch(Exception e)
		{
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    
			return null;
		}
	}
     
    public Livre() {
        initComponents();
        crud = getConnection(hoteDist);
        setIconImage(new ImageIcon(getClass().getResource("/Sary/index.png")).getImage());
        /* select NomPers,periodicite,NomJour,NomTaf,observation,semainePrevue,heure,date from personnes inner join acteur inner join pv inner join taf inner join journalier on personnes.IdPers=acteur.IdPers and acteur.IdPv=pv.IdPv and pv.IdTaf=taf.IdTaf and taf.IdJour=journalier.idJour;
         */
       LivreAfficher("journalier","NomJour","idJour");
       //combo.removeAll();
       combo.setModel(new javax.swing.DefaultComboBoxModel(teste2));  
       
        Bjour1.setVisible(false);
        heb2.setVisible(false);
        mens1.setVisible(false);
        tri1.setVisible(false);
        sem1.setVisible(false);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retour1 = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        cherche = new javax.swing.JTextField();
        Bjour = new javax.swing.JLabel();
        Bjour1 = new javax.swing.JLabel();
        heb1 = new javax.swing.JLabel();
        heb2 = new javax.swing.JLabel();
        mens = new javax.swing.JLabel();
        mens1 = new javax.swing.JLabel();
        tri = new javax.swing.JLabel();
        tri1 = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        sem1 = new javax.swing.JLabel();
        barre = new javax.swing.JLabel();
        ferm2 = new javax.swing.JLabel();
        ferm1 = new javax.swing.JLabel();
        Badmin = new javax.swing.JLabel();
        NextAdmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        retour1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retour1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retour1MousePressed(evt);
            }
        });
        getContentPane().add(retour1);
        retour1.setBounds(10, 10, 30, 20);

        line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/Line.jpg"))); // NOI18N
        line.setText("jLabel2");
        getContentPane().add(line);
        line.setBounds(370, 140, 280, 2);

        combo.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        getContentPane().add(combo);
        combo.setBounds(150, 110, 190, 30);

        jButton3.setBackground(new java.awt.Color(8, 32, 56));
        jButton3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Recherche");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(680, 100, 150, 40);

        cherche.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        cherche.setForeground(new java.awt.Color(2, 115, 197));
        cherche.setBorder(null);
        getContentPane().add(cherche);
        cherche.setBounds(370, 110, 280, 40);

        Bjour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BjourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BjourMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BjourMousePressed(evt);
            }
        });
        getContentPane().add(Bjour);
        Bjour.setBounds(473, 35, 100, 50);

        Bjour1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/journalier.jpg"))); // NOI18N
        Bjour1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bjour1MousePressed(evt);
            }
        });
        getContentPane().add(Bjour1);
        Bjour1.setBounds(473, 35, 103, 50);

        heb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                heb1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                heb1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                heb1MousePressed(evt);
            }
        });
        getContentPane().add(heb1);
        heb1.setBounds(579, 35, 100, 50);

        heb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/hebdo.jpg"))); // NOI18N
        getContentPane().add(heb2);
        heb2.setBounds(577, 35, 100, 50);

        mens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mensMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mensMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mensMousePressed(evt);
            }
        });
        getContentPane().add(mens);
        mens.setBounds(678, 35, 100, 50);

        mens1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/mensuel.jpg"))); // NOI18N
        mens1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mens1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mens1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mens1MousePressed(evt);
            }
        });
        getContentPane().add(mens1);
        mens1.setBounds(678, 35, 100, 50);

        tri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                triMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                triMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                triMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                triMouseReleased(evt);
            }
        });
        getContentPane().add(tri);
        tri.setBounds(780, 35, 100, 50);

        tri1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/trimestre.jpg"))); // NOI18N
        tri1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tri1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tri1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tri1MousePressed(evt);
            }
        });
        getContentPane().add(tri1);
        tri1.setBounds(780, 35, 100, 50);

        sem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                semMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                semMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                semMousePressed(evt);
            }
        });
        getContentPane().add(sem);
        sem.setBounds(883, 35, 100, 50);

        sem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/semestre.jpg"))); // NOI18N
        sem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sem1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sem1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sem1MousePressed(evt);
            }
        });
        getContentPane().add(sem1);
        sem1.setBounds(883, 35, 103, 50);

        barre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barreMouseDragged(evt);
            }
        });
        barre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barreMousePressed(evt);
            }
        });
        getContentPane().add(barre);
        barre.setBounds(0, 0, 50, 600);
        getContentPane().add(ferm2);
        ferm2.setBounds(961, 7, 19, 19);

        ferm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferm1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferm1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferm1MousePressed(evt);
            }
        });
        getContentPane().add(ferm1);
        ferm1.setBounds(965, 8, 19, 19);

        Badmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Badmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BadminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BadminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BadminMousePressed(evt);
            }
        });
        getContentPane().add(Badmin);
        Badmin.setBounds(730, 10, 130, 20);

        NextAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NextAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NextAdminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NextAdminMousePressed(evt);
            }
        });
        getContentPane().add(NextAdmin);
        NextAdmin.setBounds(360, 0, 140, 35);

        table.setForeground(new java.awt.Color(0, 102, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Heure", "Semaines", "Périodicité", "Equipement", "Type", "Observation", "Acteurs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(27);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(50);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(50);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(5).setPreferredWidth(70);
            table.getColumnModel().getColumn(6).setResizable(false);
            table.getColumnModel().getColumn(6).setPreferredWidth(300);
            table.getColumnModel().getColumn(7).setPreferredWidth(70);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 170, 920, 270);

        jButton1.setBackground(new java.awt.Color(8, 32, 56));
        jButton1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Export Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(720, 510, 110, 40);

        jButton2.setBackground(new java.awt.Color(8, 32, 56));
        jButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Export pdf");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(840, 510, 110, 40);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/Fond-MANEX-Livre.jpg"))); // NOI18N
        getContentPane().add(fond);
        fond.setBounds(0, 0, 1000, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PDFExporter(table, "Livre de MIRE ");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //XSSFWorkbook excelJtableExporter = null;
        JFileChooser excelFileChooser = new JFileChooser();
        excelFileChooser.setDialogTitle("Save as");
        //FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        //excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showSaveDialog(this);
        
        
        if (excelChooser == JFileChooser.APPROVE_OPTION) {

          
               XSSFWorkbook excelJtableExporter = new XSSFWorkbook();
                XSSFSheet excelSheet = excelJtableExporter.createSheet("JTable Sheet");
                for (int i = 0; i < table.getRowCount()+1; i++) {
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for (int j = 0; j < table.getColumnCount(); j++) {
                        XSSFCell excelCell = excelRow.createCell(j);
                        if(i==0){
                            
                         excelCell.setCellValue(teste2[j].toUpperCase());
                        
                        }
                        else{
                            try{
                        excelCell.setCellValue(table.getValueAt(i, j).toString());
                      
                            }
                        catch(Exception e){}
                        }
                    }
                }
                FileOutputStream excelFou;
                BufferedOutputStream excelBOU;
                try{
                excelFou = new FileOutputStream(excelFileChooser.getSelectedFile() + ".xlsx");
                excelBOU = new BufferedOutputStream(excelFou);
                excelJtableExporter.write(excelBOU);
                excelBOU.close();
                excelJtableExporter.close();
                JOptionPane.showMessageDialog(null, "succes");
                }
                catch(Exception e){JOptionPane.showMessageDialog(null, e.getMessage());}
             
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ferm1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseEntered
        // TODO add your handling code here:
        ferm2.setVisible(true);
        fond.add(ferm2);
        ferm2.setIcon(new ImageIcon(getClass().getResource("/sary/ferme1.jpg")));
        ferm2.setBounds(961, 3, 30, 30);
    }//GEN-LAST:event_ferm1MouseEntered

    private void ferm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseExited
        // TODO add your handling code here:
        ferm2.setVisible(false);
    }//GEN-LAST:event_ferm1MouseExited

    private void ferm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferm1MousePressed

    private void barreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barreMouseDragged

    private void barreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barreMousePressed

    private void BjourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BjourMouseEntered
        // TODO add your handling code here:
        Bjour1.setVisible(true);
      //  fond.add(Bjour1);
      //  Bjour1.setIcon(new ImageIcon(getClass().getResource("/sary/journalier.jpg")));
        //ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_BjourMouseEntered

    private void BjourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BjourMouseExited
        // TODO add your handling code here:
        Bjour1.setVisible(false);
    }//GEN-LAST:event_BjourMouseExited

    private void BjourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BjourMousePressed
        
        // TODO add your handling code here:
        page = "journalier";
        for(int i =0 ;i<table.getRowCount();i++){
            for(int j =0 ;j<table.getColumnCount();j++){
        table.setValueAt("", i, j);
            }
        }
         LivreAfficher("journalier","NomJour","idJour");
        //******************
    }//GEN-LAST:event_BjourMousePressed

    private void Bjour1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bjour1MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Bjour1MousePressed

    private void heb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heb1MouseEntered
        // TODO add your handling code here:
        heb2.setVisible(true);
//        fond.add( heb2);
  //      heb2.setIcon(new ImageIcon(getClass().getResource("/sary/hebdo.jpg")));
    }//GEN-LAST:event_heb1MouseEntered

    private void heb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heb1MouseExited
        // TODO add your handling code here:
        heb2.setVisible(false);
    }//GEN-LAST:event_heb1MouseExited

    private void heb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heb1MousePressed
        // TODO add your handling code here:
        page = "hebdomadaire";
        for(int i =0 ;i<table.getRowCount();i++){
            for(int j =0 ;j<table.getColumnCount();j++){
        table.setValueAt("", i, j);
            }
        }
        LivreAfficher("hebdomadaire", "NomHebdo", "idHebdo");
        

    }//GEN-LAST:event_heb1MousePressed

    private void mensMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mensMouseEntered
        // TODO add your handling code here:
        mens1.setVisible(true);
//        fond.add( mens1);
//        mens1.setIcon(new ImageIcon(getClass().getResource("/sary/mensuel.jpg")));
    }//GEN-LAST:event_mensMouseEntered

    private void mensMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mensMouseExited
        // TODO add your handling code here:
        mens1.setVisible(false);
    }//GEN-LAST:event_mensMouseExited

    private void mensMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mensMousePressed
        // TODO add your handling code here:
        page = "mensuel";
        for(int i =0 ;i<table.getRowCount();i++){
            for(int j =0 ;j<table.getColumnCount();j++){
        table.setValueAt("", i, j);
            }
        }
        LivreAfficher("mensuel", "NomMen", "IdMen");
    }//GEN-LAST:event_mensMousePressed

    private void mens1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mens1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_mens1MouseEntered

    private void mens1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mens1MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_mens1MouseExited

    private void mens1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mens1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mens1MousePressed

    private void triMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triMouseEntered
        // TODO add your handling code here:
        tri1.setVisible(true);
//        fond.add( tri1);
//        tri1.setIcon(new ImageIcon(getClass().getResource("/sary/trimestre.jpg")));
    }//GEN-LAST:event_triMouseEntered

    private void triMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triMouseExited
        // TODO add your handling code here:
        tri1.setVisible(false);
    }//GEN-LAST:event_triMouseExited

    private void triMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triMousePressed
        // TODO add your handling code here:
        page = "trisem";
           for(int i =0 ;i<table.getRowCount();i++){
            for(int j =0 ;j<table.getColumnCount();j++){
        table.setValueAt("", i, j);
            }
        }
            LivreAfficher("trisem", "NomTri", "IdTri");

    }//GEN-LAST:event_triMousePressed

    private void triMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_triMouseReleased

    private void tri1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tri1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tri1MouseEntered

    private void tri1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tri1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tri1MouseExited

    private void tri1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tri1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tri1MousePressed

    private void semMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semMouseEntered
        // TODO add your handling code here:
        sem1.setVisible(true);
//        fond.add( sem1);
//        sem1.setIcon(new ImageIcon(getClass().getResource("/sary/semestre.jpg")));
    }//GEN-LAST:event_semMouseEntered

    private void semMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semMouseExited
        // TODO add your handling code here:
       
        sem1.setVisible(false);
    }//GEN-LAST:event_semMouseExited

    private void semMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semMousePressed
        // TODO add your handling code here:
         page = "trisem";
       
    }//GEN-LAST:event_semMousePressed

    private void sem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1MouseEntered

    private void sem1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1MouseExited

    private void sem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1MousePressed

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //**********
       
            if(page.equals("journalier")){
                 if(combo.getSelectedItem().equals("Equipement"))
                    LivreAfficherRech(page, "NomJour", "idJour","NomJour",cherche.getText());
                 if(combo.getSelectedItem().equals("Date")||combo.getSelectedItem().equals("Heure")||combo.getSelectedItem().equals("Observation"))
                    LivreAfficherRech(page, "NomJour", "idJour",combo.getSelectedItem().toString().toLowerCase(),cherche.getText());
                 if(combo.getSelectedItem().equals("Périodicite"))
                    LivreAfficherRech(page, "NomJour", "idJour","periodicite",cherche.getText());
                 if(combo.getSelectedItem().equals("Type"))
                    LivreAfficherRech(page, "NomJour", "idJour","NomTaf",cherche.getText());
                 if(combo.getSelectedItem().equals("Acteur"))
                    LivreAfficherRech(page, "NomJour", "idJour","NomPers",cherche.getText());
            }
            if(page.equals("trisem")){
                 if(combo.getSelectedItem().equals("Equipement"))
                    LivreAfficherRech(page, "NomTri", "IdTri","NomTri",cherche.getText());
                 if(combo.getSelectedItem().equals("Date")||combo.getSelectedItem().equals("Heure")||combo.getSelectedItem().equals("Observation"))
                    LivreAfficherRech(page, "NomTri", "IdTri",combo.getSelectedItem().toString().toLowerCase(),cherche.getText());
                 if(combo.getSelectedItem().equals("Périodicite"))
                    LivreAfficherRech(page, "NomTri", "IdTri","periodicite",cherche.getText());
                 if(combo.getSelectedItem().equals("Type"))
                    LivreAfficherRech(page, "NomTri", "IdTri","NomTaf",cherche.getText());
                 if(combo.getSelectedItem().equals("Acteur"))
                    LivreAfficherRech(page, "NomTri", "IdTri","NomPers",cherche.getText());
            }
            if(page.equals("hebdomadaire")){
                 if(combo.getSelectedItem().equals("Equipement"))
                    LivreAfficherRech(page, "NomHebdo", "IdHebdo","NomHebdo",cherche.getText());
                 if(combo.getSelectedItem().equals("Date")||combo.getSelectedItem().equals("Heure")||combo.getSelectedItem().equals("Observation"))
                    LivreAfficherRech(page, "NomHebdo", "IdHebdo",combo.getSelectedItem().toString().toLowerCase(),cherche.getText());
                 if(combo.getSelectedItem().equals("Périodicite"))
                    LivreAfficherRech(page, "NomHebdo", "IdHebdo","periodicite",cherche.getText());
                 if(combo.getSelectedItem().equals("Type"))
                    LivreAfficherRech(page, "NomHebdo", "IdHebdo","NomTaf",cherche.getText());
                 if(combo.getSelectedItem().equals("Acteur"))
                    LivreAfficherRech(page, "NomHebdo", "IdHebdo","NomPers",cherche.getText());
            }
            if(page.equals("mensuel")){
                 if(combo.getSelectedItem().equals("Equipement"))
                    LivreAfficherRech(page, "NomMen", "IdMen","NomMen",cherche.getText());
                 if(combo.getSelectedItem().equals("Date")||combo.getSelectedItem().equals("Heure")||combo.getSelectedItem().equals("Observation"))
                    LivreAfficherRech(page, "NomMen", "IdMen",combo.getSelectedItem().toString().toLowerCase(),cherche.getText());
                 if(combo.getSelectedItem().equals("Périodicite"))
                    LivreAfficherRech(page, "NomMen", "IdMen","periodicite",cherche.getText());
                 if(combo.getSelectedItem().equals("Type"))
                    LivreAfficherRech(page, "NomMen", "IdMen","NomTaf",cherche.getText());
                 if(combo.getSelectedItem().equals("Acteur"))
                    LivreAfficherRech(page, "NomMen", "IdMen","NomPers",cherche.getText());
            }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void retour1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retour1MousePressed
        // TODO add your handling code here:
        Menu ac = new Menu();
        ac.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retour1MousePressed

    private void BadminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BadminMouseEntered
        NextAdmin.setIcon(new ImageIcon(getClass().getResource("/image/admin2.jpg")));
        NextAdmin.setBounds(727,0,140,35);
        fond.add(NextAdmin);
        NextAdmin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BadminMouseEntered

    private void BadminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BadminMouseExited
        NextAdmin.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BadminMouseExited

    private void BadminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BadminMousePressed
        TestAdmin testadmin= new TestAdmin();
        testadmin.setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_BadminMousePressed

    private void NextAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NextAdminMouseEntered

    private void NextAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextAdminMouseExited
        //    NextAdmin.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_NextAdminMouseExited

    private void NextAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextAdminMousePressed

    }//GEN-LAST:event_NextAdminMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Livre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Badmin;
    private javax.swing.JLabel Bjour;
    private javax.swing.JLabel Bjour1;
    private javax.swing.JLabel NextAdmin;
    private javax.swing.JLabel barre;
    private javax.swing.JTextField cherche;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel ferm1;
    private javax.swing.JLabel ferm2;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel heb1;
    private javax.swing.JLabel heb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel line;
    private javax.swing.JLabel mens;
    private javax.swing.JLabel mens1;
    public javax.swing.JLabel retour1;
    private javax.swing.JLabel sem;
    private javax.swing.JLabel sem1;
    private javax.swing.JTable table;
    private javax.swing.JLabel tri;
    private javax.swing.JLabel tri1;
    // End of variables declaration//GEN-END:variables

    private void LivreAfficher(String table, String nom, String id) {
         try {
             this.table.setModel(new DefaultTableModel(new String[]{"Date","Heure","Semaines","Périodicite","Equipement","Type","Observation","Acteur"}, crud.afficheLivre(table, nom, id).size()));
            for (int i = 0; i <= crud.afficheLivre(table, nom, id).size(); i++) {
                this.table.setValueAt(crud.afficheLivre(table, nom, id).get(i).getDat(), i, 0);
                this.table.setValueAt(crud.afficheLivre(table, nom, id).get(i).getheur(), i, 1);
                this.table.setValueAt(crud.afficheLivre(table, nom, id).get(i).getSemain2(), i, 2);
                this.table.setValueAt(crud.afficheLivre(table, nom, id).get(i).getPeriod(), i, 3);
                this.table.setValueAt(crud.afficheLivre(table, nom, id).get(i).getEquipemnt(), i, 4);
                this.table.setValueAt(crud.afficheLivre(table, nom, id).get(i).getType2(), i, 5);
                this.table.setValueAt(crud.afficheLivre(table, nom, id).get(i).getObs(), i, 6);
                this.table.setValueAt(crud.afficheLivre(table, nom, id).get(i).getActeur(), i, 7);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    private void LivreAfficherRech(String table, String nom,String id ,String cond,String text) {
         try {
             this.table.setModel(new DefaultTableModel(new String[]{"Date","Heure","Semaines","Périodicite","Equipement","Type","Observation","Acteur"}, crud.afficheLivreRech(table, nom, id,cond,text).size()));
            for (int i = 0; i <= crud.afficheLivreRech(table, nom, id,cond,text).size(); i++) {
                this.table.setValueAt(crud.afficheLivreRech(table, nom, id,cond,text).get(i).getDat(), i, 0);
                this.table.setValueAt(crud.afficheLivreRech(table, nom, id,cond,text).get(i).getheur(), i, 1);
                this.table.setValueAt(crud.afficheLivreRech(table, nom, id,cond,text).get(i).getSemain2(), i, 2);
                this.table.setValueAt(crud.afficheLivreRech(table, nom, id,cond,text).get(i).getPeriod(), i, 3);
                this.table.setValueAt(crud.afficheLivreRech(table, nom, id,cond,text).get(i).getEquipemnt(), i, 4);
                this.table.setValueAt(crud.afficheLivreRech(table, nom, id,cond,text).get(i).getType2(), i, 5);
                this.table.setValueAt(crud.afficheLivreRech(table, nom, id,cond,text).get(i).getObs(), i, 6);
                this.table.setValueAt(crud.afficheLivreRech(table, nom, id,cond,text).get(i).getActeur(), i, 7);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void PDFExporter(JTable table2, String Titre) {
        try {
            MessageFormat m1 = new MessageFormat(Titre);
            MessageFormat m2 = new MessageFormat("Signature");
            table2.print(JTable.PrintMode.FIT_WIDTH, m1, m2);
            
            
            
            
        } catch (PrinterException ex) {
            ex.printStackTrace();
        }
    }
}
