/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Snow
 */
public class Menu extends javax.swing.JFrame {
int xMouse, yMouse;
//Aide aide=new Aide();
    /**
     * Creates new form Menu
     */
    public Menu() {
       initComponents();
       Bcalendrier1.setVisible(false);
       Bstock1.setVisible(false);
       Blivre1.setVisible(false);
       jLabel5.setVisible(false);
       SousM.setVisible(false);
       miala.setVisible(false);
     adm.setVisible(false);
     adm1.setVisible(false);
     propo.setVisible(false);
     propo1.setVisible(false); 
     reduire.setVisible(false);
     reduire1.setVisible(false);
     note.setVisible(false);
     note1.setVisible(false);
     aide.setVisible(false);
     aide1.setVisible(false);
     fer.setVisible(false);
     fer1.setVisible(false);
     jLabel6.setVisible(false);
     jLabel8.setVisible(false);
     jLabel9.setVisible(false);
     
   //    Badmin.addMouseListener(this);
       // jLabel1.add(jLabel3);
     //  jLabel3.setVisible(true);
     //   jLabel3.setIcon(new ImageIcon(getClass().getResource("/image/labo.gif")));
    
  //     jLabel1.add(jLabel2);
  //     jLabel2.setVisible(true);
  //      jLabel2.setIcon(new ImageIcon(getClass().getResource("/image/chemistry.gif")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FbuttonT1 = new javax.swing.JLabel();
        FbuttonT = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Aide1 = new javax.swing.JLabel();
        Aide2 = new javax.swing.JLabel();
        Aide3 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        miala = new javax.swing.JLabel();
        Bbaide = new javax.swing.JLabel();
        BcompteRendue = new javax.swing.JLabel();
        NextAdmin = new javax.swing.JLabel();
        Badmin = new javax.swing.JLabel();
        barre = new javax.swing.JLabel();
        ferm1 = new javax.swing.JLabel();
        ferm2 = new javax.swing.JLabel();
        Bstock = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Bcalendrier = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adm = new javax.swing.JLabel();
        adm1 = new javax.swing.JLabel();
        fer = new javax.swing.JLabel();
        fer1 = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        note1 = new javax.swing.JLabel();
        propo = new javax.swing.JLabel();
        propo1 = new javax.swing.JLabel();
        aide = new javax.swing.JLabel();
        aide1 = new javax.swing.JLabel();
        reduire = new javax.swing.JLabel();
        reduire1 = new javax.swing.JLabel();
        cadr = new javax.swing.JLabel();
        cadr1 = new javax.swing.JLabel();
        ferm3 = new javax.swing.JLabel();
        ferm4 = new javax.swing.JLabel();
        SousM = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Bretour = new javax.swing.JLabel();
        Aide = new javax.swing.JLabel();
        Baide = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Blivre1 = new javax.swing.JLabel();
        Bcalendrier1 = new javax.swing.JLabel();
        Bstock1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(FbuttonT1);
        FbuttonT1.setBounds(830, 580, 16, 16);

        FbuttonT.setText("jLabel2");
        getContentPane().add(FbuttonT);
        FbuttonT.setBounds(830, 580, 16, 16);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btab1.png"))); // NOI18N
        jLabel9.setText("jLabel8");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(740, 50, 16, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btab1.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(690, 50, 16, 16);

        Aide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Aide-calendrier.jpg"))); // NOI18N
        Aide1.setText("jLabel4");
        getContentPane().add(Aide1);
        Aide1.setBounds(20, 620, 952, 534);

        Aide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Aide-stock.jpg"))); // NOI18N
        Aide2.setText("jLabel4");
        getContentPane().add(Aide2);
        Aide2.setBounds(20, 620, 952, 534);

        Aide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fond-Propos.jpg"))); // NOI18N
        Aide3.setText("jLabel4");
        getContentPane().add(Aide3);
        Aide3.setBounds(20, 620, 952, 534);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/tirer.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuMouseReleased(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(10, 40, 30, 20);

        miala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/retour.png"))); // NOI18N
        miala.setText("jLabel1");
        miala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mialaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mialaMousePressed(evt);
            }
        });
        getContentPane().add(miala);
        miala.setBounds(10, 40, 30, 20);

        Bbaide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bbaide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BbaideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BbaideMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BbaideMousePressed(evt);
            }
        });
        getContentPane().add(Bbaide);
        Bbaide.setBounds(750, 330, 110, 130);

        BcompteRendue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BcompteRendue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BcompteRendueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BcompteRendueMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BcompteRendueMousePressed(evt);
            }
        });
        getContentPane().add(BcompteRendue);
        BcompteRendue.setBounds(550, 330, 110, 130);

        NextAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NextAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NextAdminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NextAdminMousePressed(evt);
            }
        });
        getContentPane().add(NextAdmin);
        NextAdmin.setBounds(360, 0, 140, 35);

        Badmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Badmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BadminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BadminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BadminMousePressed(evt);
            }
        });
        getContentPane().add(Badmin);
        Badmin.setBounds(730, 10, 130, 20);

        barre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barreMouseDragged(evt);
            }
        });
        barre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barreMousePressed(evt);
            }
        });
        getContentPane().add(barre);
        barre.setBounds(0, 0, 50, 600);

        ferm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferm1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferm1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferm1MousePressed(evt);
            }
        });
        getContentPane().add(ferm1);
        ferm1.setBounds(965, 8, 19, 19);
        getContentPane().add(ferm2);
        ferm2.setBounds(961, 7, 19, 19);

        Bstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BstockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BstockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BstockMousePressed(evt);
            }
        });
        getContentPane().add(Bstock);
        Bstock.setBounds(370, 330, 110, 130);

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 330, 110, 130);

        Bcalendrier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bcalendrier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BcalendrierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BcalendrierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BcalendrierMousePressed(evt);
            }
        });
        getContentPane().add(Bcalendrier);
        Bcalendrier.setBounds(180, 330, 110, 130);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 0, 810, 570);

        adm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                admMousePressed(evt);
            }
        });
        getContentPane().add(adm);
        adm.setBounds(50, 50, 140, 17);

        adm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(adm1);
        adm1.setBounds(50, 50, 140, 17);

        fer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferMousePressed(evt);
            }
        });
        getContentPane().add(fer);
        fer.setBounds(50, 180, 140, 17);

        fer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(fer1);
        fer1.setBounds(50, 180, 140, 17);

        note.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                noteMousePressed(evt);
            }
        });
        getContentPane().add(note);
        note.setBounds(50, 73, 140, 17);

        note1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(note1);
        note1.setBounds(50, 73, 140, 17);

        propo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                propoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                propoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                propoMousePressed(evt);
            }
        });
        getContentPane().add(propo);
        propo.setBounds(50, 100, 140, 17);

        propo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(propo1);
        propo1.setBounds(50, 100, 140, 17);

        aide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aideMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aideMousePressed(evt);
            }
        });
        getContentPane().add(aide);
        aide.setBounds(50, 128, 140, 17);

        aide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(aide1);
        aide1.setBounds(50, 128, 140, 17);

        reduire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reduireMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reduireMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reduireMousePressed(evt);
            }
        });
        getContentPane().add(reduire);
        reduire.setBounds(50, 152, 140, 17);

        reduire1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(reduire1);
        reduire1.setBounds(50, 152, 140, 17);

        cadr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadrMousePressed(evt);
            }
        });
        getContentPane().add(cadr);
        cadr.setBounds(150, 330, 169, 197);

        cadr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadr1MousePressed(evt);
            }
        });
        getContentPane().add(cadr1);
        cadr1.setBounds(150, 330, 169, 197);
        getContentPane().add(ferm3);
        ferm3.setBounds(961, 7, 19, 19);

        ferm4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferm4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferm4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferm4MousePressed(evt);
            }
        });
        getContentPane().add(ferm4);
        ferm4.setBounds(965, 8, 19, 19);

        SousM.setBackground(new java.awt.Color(204, 0, 0));
        SousM.setForeground(new java.awt.Color(204, 0, 0));
        SousM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/ListeMenu-Menu3333.jpg"))); // NOI18N
        SousM.setText("jLabel1");
        getContentPane().add(SousM);
        SousM.setBounds(49, 35, 140, 199);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Blanc.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(580, 2, 70, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fond-Accueil.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setFocusable(false);
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 600);

        Bretour.setText("jLabel4");
        Bretour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BretourMousePressed(evt);
            }
        });
        getContentPane().add(Bretour);
        Bretour.setBounds(10, 320, 34, 14);

        Aide.setText("jLabel4");
        getContentPane().add(Aide);
        Aide.setBounds(48, 35, 952, 534);

        Baide.setText("jLabel4");
        Baide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BaideMousePressed(evt);
            }
        });
        getContentPane().add(Baide);
        Baide.setBounds(10, 270, 34, 14);

        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 0, 460, 330);

        Blivre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btab1.png"))); // NOI18N
        Blivre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Blivre1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Blivre1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Blivre1MousePressed(evt);
            }
        });
        getContentPane().add(Blivre1);
        Blivre1.setBounds(960, 180, 16, 16);

        Bcalendrier1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btab1.png"))); // NOI18N
        Bcalendrier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bcalendrier1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bcalendrier1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bcalendrier1MousePressed(evt);
            }
        });
        getContentPane().add(Bcalendrier1);
        Bcalendrier1.setBounds(880, 180, 16, 16);

        Bstock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btab1.png"))); // NOI18N
        Bstock1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bstock1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bstock1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bstock1MousePressed(evt);
            }
        });
        getContentPane().add(Bstock1);
        Bstock1.setBounds(920, 180, 16, 16);

        jLabel5.setBackground(new java.awt.Color(12, 46, 73));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Takona1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 70, 510, 160);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(49, 1, 490, 330);

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
         int x = evt.getXOnScreen();
         int y = evt.getYOnScreen();
         Menu.this.setLocation(x - xMouse, y - yMouse);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseDragged

    private void BstockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BstockMousePressed
        TestPersonnel testpers = new TestPersonnel();
        this.setVisible(false);
        testpers.setVisible(true);// TODO add your handling code here
        //s.choixpers();
    }//GEN-LAST:event_BstockMousePressed

    private void BstockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BstockMouseEntered
     jLabel7.setIcon(new ImageIcon(getClass().getResource("/image/NextBoutonMenu.png")));
       jLabel7.setBounds(381,330,95,95);         
       jLabel1.add(jLabel7);
      jLabel7.setVisible(true);        // TODO add your handling code here:
        // stock.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BstockMouseEntered

    private void NextAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextAdminMouseEntered
      // TODO add your handling code here:
    }//GEN-LAST:event_NextAdminMouseEntered

    private void NextAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextAdminMouseExited
    //    NextAdmin.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_NextAdminMouseExited

    private void BcalendrierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcalendrierMouseEntered
       jLabel7.setIcon(new ImageIcon(getClass().getResource("/image/NextBoutonMenu.png")));
       jLabel7.setBounds(189,330,95,95);         
       jLabel1.add(jLabel7);
      jLabel7.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BcalendrierMouseEntered

    private void BcalendrierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcalendrierMousePressed
    Plannig p =new Plannig();
    p.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_BcalendrierMousePressed

    private void BadminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BadminMousePressed
        TestAdmin testadmin= new TestAdmin();
        testadmin.setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
        
    }//GEN-LAST:event_BadminMousePressed

    private void barreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barreMouseDragged

    private void barreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_barreMousePressed

    private void ferm1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseEntered
        // TODO add your handling code here:
        ferm2.setVisible(true);
        jLabel1.add(ferm2);
        ferm2.setIcon(new ImageIcon(getClass().getResource("/image/ferme.jpg")));
        ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_ferm1MouseEntered

    private void ferm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseExited
        // TODO add your handling code here:
        ferm2.setVisible(false);
    }//GEN-LAST:event_ferm1MouseExited

    private void ferm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferm1MousePressed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MousePressed

    private void BcalendrierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcalendrierMouseExited
    jLabel7.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BcalendrierMouseExited

    private void BstockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BstockMouseExited
    jLabel7.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BstockMouseExited

    private void BaideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaideMousePressed
    Aide.setVisible(true);
    Aide.setIcon(new ImageIcon(getClass().getResource("/image/True-Aide-calendrier.jpg")));
    Bstock.setVisible(false);
    Bcalendrier.setVisible(false);
    FbuttonT.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
    FbuttonT.setBounds(880,180,16, 16);
    FbuttonT.setVisible(true);
        
    jLabel1.add(Aide);
    
    Bcalendrier1.setVisible(true);
    Bstock1.setVisible(true);
    Blivre1.setVisible(true);
    }//GEN-LAST:event_BaideMousePressed

    private void BretourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BretourMousePressed
      jLabel1.setVisible(true);
      jLabel1.setIcon(new ImageIcon(getClass().getResource("/image/Fond-Accueil.jpg"))); 
      Bstock.setVisible(true);
      Bcalendrier.setVisible(true);
      Aide.setVisible(false);
      
    FbuttonT.setVisible(false);
    FbuttonT1.setVisible(false);
    Bcalendrier1.setVisible(false);
    Bstock1.setVisible(false);
    Blivre1.setVisible(false);
    }//GEN-LAST:event_BretourMousePressed

    private void Bcalendrier1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bcalendrier1MouseEntered
        // TODO add your handling code here:
        FbuttonT1.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
        FbuttonT1.setBounds(880,180,16, 16);
        FbuttonT1.setVisible(true);
    }//GEN-LAST:event_Bcalendrier1MouseEntered

    private void Bcalendrier1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bcalendrier1MouseExited
        // TODO add your handling code here:
        FbuttonT1.setVisible(false);
    }//GEN-LAST:event_Bcalendrier1MouseExited

    private void Bcalendrier1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bcalendrier1MousePressed
        // TODO add your handling code here:
       Aide1.setBounds(48,35,952,534);
       Aide1.setVisible(true);
       Aide1.add(Bcalendrier1);
       Aide1.add(Bstock1);
       Bcalendrier1.setVisible(true);
       Bstock1.setVisible(true);
       Aide2.setVisible(false);
       
      /*  FbuttonT.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
        FbuttonT.setBounds(880,180,16, 16);
        FbuttonT.setVisible(true);
        
    Aide.setVisible(true);
    Aide.setIcon(new ImageIcon(getClass().getResource("/image/True-Aide-calendrier.jpg")));
    Bstock.setVisible(false);
    Bcalendrier.setVisible(false);
    
        
    jLabel1.add(Aide);
    
    Bcalendrier1.setVisible(true);
    Bstock1.setVisible(true);
    //Blivre1.setVisible(true);
//        Actualiser();
        // FbuttonT.setVisible(true);*/
    }//GEN-LAST:event_Bcalendrier1MousePressed

    private void Bstock1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bstock1MouseEntered
        // TODO add your handling code here:
        FbuttonT1.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
        FbuttonT1.setBounds(920,180,16, 16);
        FbuttonT1.setVisible(true);
    }//GEN-LAST:event_Bstock1MouseEntered

    private void Bstock1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bstock1MouseExited
        // TODO add your handling code here:
        FbuttonT1.setVisible(false);
    }//GEN-LAST:event_Bstock1MouseExited

    private void Bstock1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bstock1MousePressed
        // TODO add your handling code here:
       Aide2.setBounds(48,35,952,534);
       Aide2.setVisible(true);
       Aide2.add(Bcalendrier1);
       Aide2.add(Bstock1);
       Bcalendrier1.setVisible(true);
       Bstock1.setVisible(true);
       Aide1.setVisible(false);
        
        /*  FbuttonT.setBounds(920,180,16, 16);
        FbuttonT.setVisible(true);

       Aide.setVisible(true);
    Aide.setIcon(new ImageIcon(getClass().getResource("/image/Aide-stock.jpg")));
    Bstock.setVisible(false);
    Bcalendrier.setVisible(false);
    
        
    jLabel1.add(Aide);
    
    Bcalendrier1.setVisible(true);
    Bstock1.setVisible(true);
    Blivre1.setVisible(true);*/
    }//GEN-LAST:event_Bstock1MousePressed

    private void Blivre1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Blivre1MouseEntered
        // TODO add your handling code here:
        FbuttonT1.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
        FbuttonT1.setBounds(960,180,16, 16);
        FbuttonT1.setVisible(true);
    }//GEN-LAST:event_Blivre1MouseEntered

    private void Blivre1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Blivre1MouseExited
        // TODO add your handling code here:
        FbuttonT1.setVisible(false);
    }//GEN-LAST:event_Blivre1MouseExited

    private void Blivre1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Blivre1MousePressed
        // TODO add your handling code here:

        FbuttonT.setBounds(960,180,16, 16);
        FbuttonT.setVisible(true);

    }//GEN-LAST:event_Blivre1MousePressed

    private void BcompteRendueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcompteRendueMouseEntered
     jLabel7.setIcon(new ImageIcon(getClass().getResource("/image/NextBoutonMenu.png")));
       jLabel7.setBounds(558,330,95,95);         
       jLabel1.add(jLabel7);
      jLabel7.setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BcompteRendueMouseEntered

    private void BcompteRendueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcompteRendueMouseExited
    jLabel7.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BcompteRendueMouseExited

    private void BcompteRendueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcompteRendueMousePressed
    Livre l=new Livre();
    l.setVisible(true);
    this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BcompteRendueMousePressed

    private void BbaideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BbaideMouseEntered
     jLabel7.setIcon(new ImageIcon(getClass().getResource("/image/NextBoutonMenu.png")));
       jLabel7.setBounds(758,330,95,95);         
       jLabel1.add(jLabel7);
      jLabel7.setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BbaideMouseEntered

    private void BbaideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BbaideMouseExited
      jLabel7.setVisible(false);
    }//GEN-LAST:event_BbaideMouseExited

    private void BbaideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BbaideMousePressed
        jLabel1.add(Aide1);
        Aide1.setBounds(48,35,952,534);
        Aide1.setVisible(true);
        jLabel8.setBounds(880,180,16,16);
        jLabel9.setBounds(920,180,16,16);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);

       Bcalendrier.setVisible(false);
       Bstock.setVisible(false);
       BcompteRendue.setVisible(false);
       Bbaide.setVisible(false);
       jLabel5.setVisible(false);
       jLabel6.setVisible(true);
       Aide3.setVisible(false);

    FbuttonT.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
    FbuttonT.setBounds(880,180,16, 16);
    FbuttonT.setVisible(true);
 
    SousM.setVisible(false);
        menu.setVisible(true);
        miala.setVisible(false);
        adm.setVisible(false);
        adm1.setVisible(false);
        propo.setVisible(false);
        propo1.setVisible(false);
        reduire.setVisible(false);
        reduire1.setVisible(false);
        note.setVisible(false);
        note1.setVisible(false);
        aide.setVisible(false);
        aide1.setVisible(false);
        fer.setVisible(false);
        fer1.setVisible(false);
        jLabel5.setVisible(false);
        
        /*    Aide.setVisible(true);
    Aide.setIcon(new ImageIcon(getClass().getResource("/image/True-Aide-calendrier.jpg")));
    Bstock.setVisible(false);
    Bcalendrier.setVisible(false);
    FbuttonT.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
    FbuttonT.setBounds(880,180,16, 16);
    FbuttonT.setVisible(true);
    jLabel7.setVisible(false);    
    jLabel1.add(Aide);
    
    Bcalendrier1.setVisible(true);
    Bstock1.setVisible(true);
    Blivre1.setVisible(true);*/        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BbaideMousePressed

    private void BadminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BadminMouseEntered
       NextAdmin.setIcon(new ImageIcon(getClass().getResource("/image/admin2.jpg")));
       NextAdmin.setBounds(727,0,140,35);         
       jLabel1.add(NextAdmin);
       NextAdmin.setVisible(true); 
       // TODO add your handling code here:
    }//GEN-LAST:event_BadminMouseEntered

    private void BadminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BadminMouseExited
NextAdmin.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BadminMouseExited

    private void NextAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextAdminMousePressed
    }//GEN-LAST:event_NextAdminMousePressed

    private void admMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMouseEntered
        // TODO add your handling code here:
        adm1.setVisible(true);
        //adm1.setVisible(true);
    }//GEN-LAST:event_admMouseEntered

    private void admMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMouseExited
        // TODO add your handling code here:
        adm1.setVisible(false);
    }//GEN-LAST:event_admMouseExited

    private void admMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMousePressed
jLabel6.setVisible(false);
Aide1.setVisible(false);
Aide2.setVisible(false);
jLabel8.setVisible(false);
jLabel9.setVisible(false);
Aide3.setVisible(false);

// TODO add your handling code here:
        SousM.setVisible(false);
        menu.setVisible(true);
        miala.setVisible(false);
        adm.setVisible(false);
        adm1.setVisible(false);
        propo.setVisible(false);
        propo1.setVisible(false);
        reduire.setVisible(false);
        reduire1.setVisible(false);
        note.setVisible(false);
        note1.setVisible(false);
        aide.setVisible(false);
        aide1.setVisible(false);
        fer.setVisible(false);
        fer1.setVisible(false);
        jLabel5.setVisible(false);
              jLabel1.setVisible(true);
      jLabel1.setIcon(new ImageIcon(getClass().getResource("/image/Fond-Accueil.jpg"))); 
      Bstock.setVisible(true);
      Bcalendrier.setVisible(true);
      BcompteRendue.setVisible(true);
      Bbaide.setVisible(true);
      jLabel7.setVisible(true);
      Aide.setVisible(false);
///      propos.setVisible(false);
    FbuttonT.setVisible(false);
    FbuttonT1.setVisible(false);
    Bcalendrier1.setVisible(false);
    Bstock1.setVisible(false);
    Blivre1.setVisible(false);
    }//GEN-LAST:event_admMousePressed

    private void ferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferMouseEntered
        // TODO add your handling code here:
        fer1.setVisible(true);
    }//GEN-LAST:event_ferMouseEntered

    private void ferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferMouseExited
        // TODO add your handling code here:
        fer1.setVisible(false);
    }//GEN-LAST:event_ferMouseExited

    private void ferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferMousePressed

    private void noteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noteMouseEntered
        // TODO add your handling code here:
        note1.setVisible(true);
    }//GEN-LAST:event_noteMouseEntered

    private void noteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noteMouseExited
        // TODO add your handling code here:
        note1.setVisible(false);
    }//GEN-LAST:event_noteMouseExited

    private void propoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propoMouseEntered
        // TODO add your handling code here:
        propo1.setVisible(true);
    }//GEN-LAST:event_propoMouseEntered

    private void propoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propoMouseExited
        // TODO add your handling code here:
        propo1.setVisible(false);
    }//GEN-LAST:event_propoMouseExited

    private void aideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aideMouseEntered
        // TODO add your handling code here:
        aide1.setVisible(true);
    }//GEN-LAST:event_aideMouseEntered

    private void aideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aideMouseExited
        // TODO add your handling code here:
        aide1.setVisible(false);
    }//GEN-LAST:event_aideMouseExited

    private void reduireMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduireMouseEntered
        // TODO add your handling code here:
        reduire1.setVisible(true);
    }//GEN-LAST:event_reduireMouseEntered

    private void reduireMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduireMouseExited
        // TODO add your handling code here:
        reduire1.setVisible(false);
    }//GEN-LAST:event_reduireMouseExited

    private void reduireMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduireMousePressed
        // TODO add your handling code here:
        setState(Accueil.ICONIFIED);
    }//GEN-LAST:event_reduireMousePressed

    private void cadrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadrMouseEntered
        // TODO add your handling code here:
        cadr1.setVisible(true);
        jLabel1.add(cadr1);
        cadr1.setIcon(new ImageIcon(getClass().getResource("/sary/cadre.png")));
        cadr1.setBounds(150,330,169, 197);
    }//GEN-LAST:event_cadrMouseEntered

    private void cadrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadrMouseExited
        // TODO add your handling code here:
        cadr1.setVisible(false);
    }//GEN-LAST:event_cadrMouseExited

    private void cadrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadrMousePressed
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(this, "okkkkkkk");
        Plannig p=new Plannig();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cadrMousePressed

    private void cadr1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadr1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadr1MousePressed

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        // TODO add your handling code here:

        /*if(x==210){
            sousM.setSize(130, 190);
            Thread th = new Thread();

            @Override
            public void run(){
                try{
                    for(int i=210;i>=0;i--)
                    {
                        Thread.sleep(1);
                        sousM.setSize(130,190);
                    }
                }
                catch(Exception e){}

            };
            th.start();
            x=0;
        }*/
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseExited

    private void menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMousePressed
        // TODO add your handling code here:
        SousM.setVisible(true);
        menu.setVisible(false);
        miala.setVisible(true);
      //  jLabel5.setVisible(true);
        //****
        adm.setVisible(true);
        propo.setVisible(true);
        reduire.setVisible(true);
        note.setVisible(true);
        aide.setVisible(true);
        fer.setVisible(true);
    }//GEN-LAST:event_menuMousePressed

    private void menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseReleased

    private void mialaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mialaMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_mialaMouseExited

    private void mialaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mialaMousePressed
        // TODO add your handling code here:
        jLabel5.setVisible(false);
        SousM.setVisible(false);
        menu.setVisible(true);
        miala.setVisible(false);
        adm.setVisible(false);
        adm1.setVisible(false);
        propo.setVisible(false);
        propo1.setVisible(false);
        reduire.setVisible(false);
        reduire1.setVisible(false);
        note.setVisible(false);
        note1.setVisible(false);
        aide.setVisible(false);
        aide1.setVisible(false);
        fer.setVisible(false);
        fer1.setVisible(false);
    }//GEN-LAST:event_mialaMousePressed

    private void ferm4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm4MouseEntered
        // TODO add your handling code here:
        ferm2.setVisible(true);
        jLabel1.add(ferm2);
        ferm2.setIcon(new ImageIcon(getClass().getResource("/sary/ferme1.jpg")));
        ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_ferm4MouseEntered

    private void ferm4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm4MouseExited
        // TODO add your handling code here:
        ferm2.setVisible(false);
    }//GEN-LAST:event_ferm4MouseExited

    private void ferm4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm4MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferm4MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        SousM.setVisible(false);
        menu.setVisible(true);
        miala.setVisible(false);
        adm.setVisible(false);
        adm1.setVisible(false);
        propo.setVisible(false);
        propo1.setVisible(false);
        reduire.setVisible(false);
        reduire1.setVisible(false);
        note.setVisible(false);
        note1.setVisible(false);
        aide.setVisible(false);
        aide1.setVisible(false);
        fer.setVisible(false);
        fer1.setVisible(false);
    }//GEN-LAST:event_jLabel4MousePressed

    private void aideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aideMousePressed
        jLabel1.add(Aide1);
        Aide1.setBounds(48,35,952,534);
        Aide1.setVisible(true);
        jLabel8.setBounds(880,180,16,16);
        jLabel9.setBounds(920,180,16,16);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);

       Bcalendrier.setVisible(false);
       Bstock.setVisible(false);
       BcompteRendue.setVisible(false);
       Bbaide.setVisible(false);
       
       jLabel5.setVisible(false);
       jLabel6.setVisible(true);
       Aide3.setVisible(false);

    FbuttonT.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
    FbuttonT.setBounds(880,180,16, 16);
    FbuttonT.setVisible(true);
 
    SousM.setVisible(false);
        menu.setVisible(true);
        miala.setVisible(false);
        adm.setVisible(false);
        adm1.setVisible(false);
        propo.setVisible(false);
        propo1.setVisible(false);
        reduire.setVisible(false);
        reduire1.setVisible(false);
        note.setVisible(false);
        note1.setVisible(false);
        aide.setVisible(false);
        aide1.setVisible(false);
        fer.setVisible(false);
        fer1.setVisible(false);
        jLabel5.setVisible(false);
        /*//jLabel6.setVisible(true);
Aide.setVisible(true);
    Aide.setIcon(new ImageIcon(getClass().getResource("/image/True-Aide-calendrier.jpg")));
        
        
    Bstock.setVisible(false);
    Bcalendrier.setVisible(false);
    FbuttonT.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
    FbuttonT.setBounds(880,180,16, 16);
    FbuttonT.setVisible(true);
    jLabel7.setVisible(false);    
    jLabel1.add(Aide);
    jLabel5.setVisible(false);
    
    Bcalendrier1.setVisible(true);
    Bstock1.setVisible(true);
    Blivre1.setVisible(true);*/
        // TODO add your handling code here:
    }//GEN-LAST:event_aideMousePressed

    private void noteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noteMousePressed
jLabel6.setVisible(false);
Aide1.setVisible(false);
Aide2.setVisible(false);
jLabel8.setVisible(false);
jLabel9.setVisible(false);
Aide3.setVisible(false);
//        propos.setVisible(false);     
    Note n= new Note();
    n.setVisible(true);
    this.setVisible(false);
        
        jLabel1.setVisible(true);
      jLabel1.setIcon(new ImageIcon(getClass().getResource("/image/Fond-Accueil.jpg"))); 
      Bstock.setVisible(true);
      Bcalendrier.setVisible(true);
      Aide.setVisible(false);
      
    FbuttonT.setVisible(false);
    FbuttonT1.setVisible(false);
    Bcalendrier1.setVisible(false);
    Bstock1.setVisible(false);
    Blivre1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_noteMousePressed

    private void propoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propoMousePressed
jLabel6.setVisible(true);
Aide1.setVisible(false);
Aide2.setVisible(false);
jLabel8.setVisible(false);
jLabel9.setVisible(false);
FbuttonT.setVisible(false);
FbuttonT1.setVisible(false);
//jLabel6.setVisible(true);
        SousM.setVisible(false);
        menu.setVisible(true);
        miala.setVisible(false);
        adm.setVisible(false);
        adm1.setVisible(false);
        propo.setVisible(false);
        propo1.setVisible(false);
        reduire.setVisible(false);
        reduire1.setVisible(false);
        note.setVisible(false);
        note1.setVisible(false);
        aide.setVisible(false);
        aide1.setVisible(false);
        fer.setVisible(false);
        fer1.setVisible(false);
        jLabel5.setVisible(false);
       
       Bcalendrier.setVisible(false);
       Bstock.setVisible(false);
       BcompteRendue.setVisible(false);
       Bbaide.setVisible(false);
       
    jLabel1.add(Aide3);    
    Aide3.setVisible(true);
    Aide3.setBounds(48,35,952,534);
 //       propos.setVisible(true);
 //   Aide.setIcon(new ImageIcon(getClass().getResource("/image/Fond-Propos.jpg")));
    Bstock.setVisible(false);
    Bcalendrier.setVisible(false);
    jLabel7.setVisible(false);    
 //   jLabel1.add(Aide);
    jLabel5.setVisible(false);
    
    // TODO add your handling code here:
    }//GEN-LAST:event_propoMousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        jLabel1.add(Aide1);
        Aide1.setBounds(48,35,952,534);
        Aide1.setVisible(true);
        Aide2.setVisible(false);
        
        FbuttonT.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
        FbuttonT.setBounds(880,180,16, 16);
        FbuttonT.setVisible(true);
        
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        jLabel1.add(Aide2);
        Aide2.setBounds(48,35,952,534);
        Aide2.setVisible(true);
        Aide1.setVisible(false);
        
        FbuttonT.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
        FbuttonT.setBounds(920,180,16, 16);
        FbuttonT.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        FbuttonT1.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
        FbuttonT1.setBounds(920,180,16, 16);
        FbuttonT1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        FbuttonT1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        FbuttonT1.setIcon(new ImageIcon(getClass().getResource("/image/Btab2.jpg")));
        FbuttonT1.setBounds(880,180,16, 16);
        FbuttonT1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        FbuttonT1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aide;
    private javax.swing.JLabel Aide1;
    private javax.swing.JLabel Aide2;
    private javax.swing.JLabel Aide3;
    public javax.swing.JLabel Badmin;
    private javax.swing.JLabel Baide;
    private javax.swing.JLabel Bbaide;
    private javax.swing.JLabel Bcalendrier;
    public javax.swing.JLabel Bcalendrier1;
    private javax.swing.JLabel BcompteRendue;
    public javax.swing.JLabel Blivre1;
    private javax.swing.JLabel Bretour;
    private javax.swing.JLabel Bstock;
    public javax.swing.JLabel Bstock1;
    public javax.swing.JLabel FbuttonT;
    public javax.swing.JLabel FbuttonT1;
    public javax.swing.JLabel NextAdmin;
    private javax.swing.JLabel SousM;
    private javax.swing.JLabel adm;
    private javax.swing.JLabel adm1;
    private javax.swing.JLabel aide;
    private javax.swing.JLabel aide1;
    private javax.swing.JLabel barre;
    private javax.swing.JLabel cadr;
    private javax.swing.JLabel cadr1;
    private javax.swing.JLabel fer;
    private javax.swing.JLabel fer1;
    private javax.swing.JLabel ferm1;
    private javax.swing.JLabel ferm2;
    private javax.swing.JLabel ferm3;
    private javax.swing.JLabel ferm4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel miala;
    private javax.swing.JLabel note;
    private javax.swing.JLabel note1;
    private javax.swing.JLabel propo;
    private javax.swing.JLabel propo1;
    private javax.swing.JLabel reduire;
    private javax.swing.JLabel reduire1;
    // End of variables declaration//GEN-END:variables
}
