/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafaly Antoni
 */
public class page2 extends javax.swing.JFrame {
int xMouse,yMouse;
String strDate;
JTable tab1=new JTable();
JScrollPane scroll;
String []personne={"fefef","efefef","efef"};
String[]colonneTab={"Journalier","ezezez"};
Connection connex;
StringBuffer sql;
ResultSet res;
Statement etat;
   public void connexionBase(){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    connex=DriverManager.getConnection("jdbc:mysql://localhost/asecna","root","");
    etat=connex.createStatement();
    }
    catch(ClassNotFoundException e){
        JOptionPane.showMessageDialog(this, "pilote non configurer");
        
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(this, "BDD introuvalable");
    }
    
    }
  
   //************************
    public void afficheJour(){
         
            connexionBase();
    String req=" select * from journalier ";
    try{
        sql.append(req);
        res=etat.executeQuery(sql.toString());
        int i=0;
        while(res.next()){
        
      
        i++;
        }
    }
    catch(SQLException e){
         JOptionPane.showMessageDialog(this, "Erreur de syntax "+e.getMessage());
    }
    } 
    /**
     * Creates new form page2
     */
    public page2() {
         
        initComponents();
        setBounds(200, 75, WIDTH, WIDTH);
       
     // afficheJour();
        
        Date date=new Date();    
        DateFormat dateFormat=new SimpleDateFormat("dd/MM/yyyy");
        strDate=dateFormat.format(date);
        Date1.setText(strDate);
        tab1.setModel(new DefaultTableModel(personne,5));
        scroll=new JScrollPane(tab1);
        scroll.setBounds(15, 64, 50, 100);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ferm2 = new javax.swing.JLabel();
        ferm1 = new javax.swing.JLabel();
        barre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Date1 = new javax.swing.JLabel();
        texteT = new javax.swing.JLabel();
        texteT1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ohatra = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        ohatra1 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        ohatra2 = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable15 = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable16 = new javax.swing.JTable();
        fond2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(200, 75, 75, 75));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(ferm2);
        ferm2.setBounds(961, 7, 19, 19);

        ferm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferm1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferm1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferm1MousePressed(evt);
            }
        });
        getContentPane().add(ferm1);
        ferm1.setBounds(965, 8, 19, 19);

        barre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barreMouseDragged(evt);
            }
        });
        barre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barreMousePressed(evt);
            }
        });
        getContentPane().add(barre);
        barre.setBounds(0, 0, 50, 600);

        jTable1.setForeground(new java.awt.Color(0, 102, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Titres", "Types"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 450, 890, 110);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(350, 410, 220, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(70, 410, 220, 30);

        jButton1.setText("P.V");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(820, 100, 140, 30);

        jButton2.setText("Recherche");
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 410, 140, 30);

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 115, 197));
        jLabel1.setText("Maintenance Préventive ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 94, 360, 40);

        Date1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        Date1.setForeground(new java.awt.Color(2, 115, 197));
        Date1.setText("Date");
        getContentPane().add(Date1);
        Date1.setBounds(400, 100, 210, 30);

        texteT.setText("Mois :");
        getContentPane().add(texteT);
        texteT.setBounds(350, 390, 70, 14);

        texteT1.setText("Semaine :");
        getContentPane().add(texteT1);
        texteT1.setBounds(70, 390, 70, 14);

        jScrollPane3.setBackground(new java.awt.Color(255, 0, 0));
        jScrollPane3.setBorder(null);

        ohatra.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ohatra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ohatra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Janvier"
            }
        ));
        jScrollPane3.setViewportView(ohatra);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(70, 230, 320, 30);

        jScrollPane6.setBorder(null);

        jTable6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(70, 260, 70, 110);

        jScrollPane4.setBorder(null);

        jTable4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(140, 260, 70, 110);

        jScrollPane5.setBorder(null);

        jTable5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(280, 260, 70, 110);

        jScrollPane7.setBorder(null);

        jTable7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(210, 260, 70, 110);

        jScrollPane8.setBorder(null);

        ohatra1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ohatra1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ohatra1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Janvier"
            }
        ));
        jScrollPane8.setViewportView(ohatra1);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(390, 230, 310, 30);

        jScrollPane9.setBorder(null);

        jTable8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane9.setViewportView(jTable8);

        getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(420, 260, 70, 110);

        jScrollPane10.setBorder(null);

        jTable9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane10.setViewportView(jTable9);

        getContentPane().add(jScrollPane10);
        jScrollPane10.setBounds(490, 260, 70, 110);

        jScrollPane11.setBorder(null);

        jTable10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane11.setViewportView(jTable10);

        getContentPane().add(jScrollPane11);
        jScrollPane11.setBounds(560, 260, 70, 110);

        jScrollPane12.setBorder(null);

        jTable11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane12.setViewportView(jTable11);

        getContentPane().add(jScrollPane12);
        jScrollPane12.setBounds(630, 260, 70, 110);

        jScrollPane13.setBorder(null);

        ohatra2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ohatra2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ohatra2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Janvier"
            }
        ));
        jScrollPane13.setViewportView(ohatra2);

        getContentPane().add(jScrollPane13);
        jScrollPane13.setBounds(700, 230, 280, 30);

        jScrollPane14.setBorder(null);

        jTable12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane14.setViewportView(jTable12);

        getContentPane().add(jScrollPane14);
        jScrollPane14.setBounds(700, 260, 70, 110);

        jScrollPane15.setBorder(null);

        jTable13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane15.setViewportView(jTable13);

        getContentPane().add(jScrollPane15);
        jScrollPane15.setBounds(770, 260, 70, 110);

        jScrollPane16.setBorder(null);

        jTable14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane16.setViewportView(jTable14);

        getContentPane().add(jScrollPane16);
        jScrollPane16.setBounds(840, 260, 70, 110);

        jScrollPane17.setBorder(null);

        jTable15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane17.setViewportView(jTable15);

        getContentPane().add(jScrollPane17);
        jScrollPane17.setBounds(910, 260, 70, 110);

        jScrollPane18.setBorder(null);

        jTable16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable16.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane18.setViewportView(jTable16);

        getContentPane().add(jScrollPane18);
        jScrollPane18.setBounds(350, 260, 70, 110);

        fond2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/fond2.jpg"))); // NOI18N
        fond2.setText("fond2");
        getContentPane().add(fond2);
        fond2.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ferm1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseEntered
        // TODO add your handling code here:
        ferm2.setVisible(true);
        fond2.add(ferm2);
        ferm2.setIcon(new ImageIcon(getClass().getResource("/sary/ferme1.jpg")));
        ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_ferm1MouseEntered

    private void ferm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseExited
        // TODO add your handling code here:
        ferm2.setVisible(false);
    }//GEN-LAST:event_ferm1MouseExited

    private void ferm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferm1MousePressed

    private void barreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barreMouseDragged

    private void barreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_barreMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        fond2.add(scroll);
        scroll.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date1;
    private javax.swing.JLabel barre;
    private javax.swing.JLabel ferm1;
    private javax.swing.JLabel ferm2;
    private javax.swing.JLabel fond2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    public javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable14;
    private javax.swing.JTable jTable15;
    public javax.swing.JTable jTable16;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTable ohatra;
    private javax.swing.JTable ohatra1;
    private javax.swing.JTable ohatra2;
    private javax.swing.JLabel texteT;
    private javax.swing.JLabel texteT1;
    // End of variables declaration//GEN-END:variables
}
