/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class pageT extends javax.swing.JFrame {

    /**
     * Creates new form pageT
     */
    Connection connex;
    StringBuffer sql;
    ResultSet res;
    Statement etat; 
    
    public pageT() {
        initComponents();
    }
    
    public void connexionBase()
            {
                sql=new StringBuffer();
                connex=null;
                etat=null;
                try
                {
                    Class.forName("com.mysql.jdbc.Driver");
                    connex=DriverManager.getConnection("jdbc:mysql://localhost/asecna","root","");
                    etat=connex.createStatement();
                }
                catch(ClassNotFoundException e){
                    JOptionPane.showMessageDialog(null, "pilote non configurer");

                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "BDD introuvalable");
                }
    
            }
    public int compterS1M1(String semaine,String mois,String type)
            {
                int i=0;
                connexionBase();
                String req=" select NomTri from trisem where Semaine='"+semaine+"'and Mois='"+mois+"'and Type='"+type+"'  ";
                try
                {
                    sql.append(req);
                    res=etat.executeQuery(sql.toString());
                    while(res.next())
                     {
                         i++;
                     }
                }
                catch(SQLException e)
                {
                        JOptionPane.showMessageDialog(null, "Erreur de syntax "+e.getMessage());
                }
                        return i;
            }
    public void afficheS1M1(String semaine,String mois,String type, JTable table,String []semain){
        int n=compterS1M1(semaine,mois,type);
        if(n<=3)
            table.setModel(new DefaultTableModel(semain,4));
        else
           table.setModel(new DefaultTableModel(semain,n));
    connexionBase();
    String req=" select NomTri from trisem where Semaine='"+semaine+"'and Mois='"+mois+"'and Type='"+type+"' ";
    try{
        sql.append(req);
        res=etat.executeQuery(sql.toString());
        int i=0;
        while(res.next()){
        table.setValueAt(res.getString(1), i, 0);
        
        i++;
        }
    }
    catch(SQLException e){
         JOptionPane.showMessageDialog(null, "Erreur de syntax "+e.getMessage());
    }
   // tailleLigneTableau();
    
    
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pmois = new javax.swing.JScrollPane();
        mois1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        sem1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        sem2 = new javax.swing.JTable();
        pmois2 = new javax.swing.JScrollPane();
        sem3 = new javax.swing.JTable();
        pmois22 = new javax.swing.JScrollPane();
        sem4 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        sem5 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        sem6 = new javax.swing.JTable();
        pmois3 = new javax.swing.JScrollPane();
        sem7 = new javax.swing.JTable();
        pmois6 = new javax.swing.JScrollPane();
        sem8 = new javax.swing.JTable();
        Pmois1 = new javax.swing.JScrollPane();
        mois2 = new javax.swing.JTable();
        Pmois2 = new javax.swing.JScrollPane();
        mois3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        sem9 = new javax.swing.JTable();
        PanMois2 = new javax.swing.JScrollPane();
        sem10 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        sem11 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        sem13 = new javax.swing.JTable();
        Ptmois = new javax.swing.JScrollPane();
        tmois = new javax.swing.JTable();
        Ptmois2 = new javax.swing.JScrollPane();
        tmois2 = new javax.swing.JTable();
        Ptmois1 = new javax.swing.JScrollPane();
        tmois1 = new javax.swing.JTable();
        Ptmois3 = new javax.swing.JScrollPane();
        tmois3 = new javax.swing.JTable();
        Ptmois4 = new javax.swing.JScrollPane();
        tmois4 = new javax.swing.JTable();
        Ptmois5 = new javax.swing.JScrollPane();
        tmois5 = new javax.swing.JTable();
        Ptmois6 = new javax.swing.JScrollPane();
        tmois6 = new javax.swing.JTable();
        Ptmois7 = new javax.swing.JScrollPane();
        tmois7 = new javax.swing.JTable();
        Ptmois8 = new javax.swing.JScrollPane();
        tmois8 = new javax.swing.JTable();
        Ptmois9 = new javax.swing.JScrollPane();
        tmois9 = new javax.swing.JTable();
        Ptmois10 = new javax.swing.JScrollPane();
        tmois10 = new javax.swing.JTable();
        Ptmois11 = new javax.swing.JScrollPane();
        tmois11 = new javax.swing.JTable();
        Ptmois12 = new javax.swing.JScrollPane();
        tmois12 = new javax.swing.JTable();
        Ptmois13 = new javax.swing.JScrollPane();
        tmois13 = new javax.swing.JTable();
        Ptmois14 = new javax.swing.JScrollPane();
        tmois14 = new javax.swing.JTable();
        pmois23 = new javax.swing.JScrollPane();
        sem12 = new javax.swing.JTable();
        Ptmois15 = new javax.swing.JScrollPane();
        tmois15 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Pmois.setBackground(new java.awt.Color(255, 51, 102));
        Pmois.setBorder(null);
        Pmois.setForeground(new java.awt.Color(255, 51, 51));

        mois1.setBackground(new java.awt.Color(255, 0, 0));
        mois1.setForeground(new java.awt.Color(255, 0, 0));
        mois1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        Pmois.setViewportView(mois1);

        getContentPane().add(Pmois);
        Pmois.setBounds(60, 140, 350, 22);
        Pmois.getAccessibleContext().setAccessibleName("");

        jScrollPane2.setBorder(null);

        sem1.setForeground(new java.awt.Color(0, 102, 255));
        sem1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(sem1);
        if (sem1.getColumnModel().getColumnCount() > 0) {
            sem1.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 163, 70, 110);
        jScrollPane2.getAccessibleContext().setAccessibleName("");

        jScrollPane1.setBorder(null);

        sem2.setForeground(new java.awt.Color(0, 102, 255));
        sem2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 2"
            }
        ));
        jScrollPane1.setViewportView(sem2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 163, 70, 110);
        jScrollPane1.getAccessibleContext().setAccessibleName("");

        pmois2.setBorder(null);

        sem3.setForeground(new java.awt.Color(0, 102, 255));
        sem3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pmois2.setViewportView(sem3);
        if (sem3.getColumnModel().getColumnCount() > 0) {
            sem3.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(pmois2);
        pmois2.setBounds(200, 163, 70, 110);
        pmois2.getAccessibleContext().setAccessibleName("");

        pmois22.setBorder(null);

        sem4.setForeground(new java.awt.Color(0, 102, 255));
        sem4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 4"
            }
        ));
        pmois22.setViewportView(sem4);

        getContentPane().add(pmois22);
        pmois22.setBounds(270, 163, 70, 110);
        pmois22.getAccessibleContext().setAccessibleName("");

        jScrollPane3.setBorder(null);

        sem5.setForeground(new java.awt.Color(0, 102, 255));
        sem5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ));
        jScrollPane3.setViewportView(sem5);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(410, 163, 70, 110);
        jScrollPane3.getAccessibleContext().setAccessibleName("");

        jScrollPane4.setBorder(null);

        sem6.setForeground(new java.awt.Color(0, 102, 255));
        sem6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane4.setViewportView(sem6);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(480, 163, 70, 110);
        jScrollPane4.getAccessibleContext().setAccessibleName("");

        pmois3.setBorder(null);

        sem7.setForeground(new java.awt.Color(0, 102, 255));
        sem7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        pmois3.setViewportView(sem7);

        getContentPane().add(pmois3);
        pmois3.setBounds(550, 163, 70, 110);
        pmois3.getAccessibleContext().setAccessibleName("");

        pmois6.setBorder(null);

        sem8.setForeground(new java.awt.Color(0, 102, 255));
        sem8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        pmois6.setViewportView(sem8);

        getContentPane().add(pmois6);
        pmois6.setBounds(620, 163, 70, 110);
        pmois6.getAccessibleContext().setAccessibleName("");

        Pmois1.setBorder(null);

        mois2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        Pmois1.setViewportView(mois2);

        getContentPane().add(Pmois1);
        Pmois1.setBounds(410, 140, 280, 22);
        Pmois1.getAccessibleContext().setAccessibleName("");

        Pmois2.setBorder(null);

        mois3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        Pmois2.setViewportView(mois3);

        getContentPane().add(Pmois2);
        Pmois2.setBounds(690, 140, 280, 22);
        Pmois2.getAccessibleContext().setAccessibleName("");

        jScrollPane5.setBorder(null);

        sem9.setForeground(new java.awt.Color(0, 102, 255));
        sem9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane5.setViewportView(sem9);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(690, 163, 70, 110);
        jScrollPane5.getAccessibleContext().setAccessibleName("");

        PanMois2.setBorder(null);

        sem10.setForeground(new java.awt.Color(0, 102, 255));
        sem10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        PanMois2.setViewportView(sem10);

        getContentPane().add(PanMois2);
        PanMois2.setBounds(760, 163, 70, 110);
        PanMois2.getAccessibleContext().setAccessibleName("");

        jScrollPane6.setBorder(null);

        sem11.setForeground(new java.awt.Color(0, 102, 255));
        sem11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane6.setViewportView(sem11);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(900, 163, 70, 110);
        jScrollPane6.getAccessibleContext().setAccessibleName("");

        jScrollPane7.setBorder(null);

        sem13.setForeground(new java.awt.Color(0, 102, 255));
        sem13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane7.setViewportView(sem13);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(830, 163, 70, 110);
        jScrollPane7.getAccessibleContext().setAccessibleName("");

        Ptmois.setBorder(null);

        tmois.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        Ptmois.setViewportView(tmois);

        getContentPane().add(Ptmois);
        Ptmois.setBounds(60, 275, 350, 22);

        Ptmois2.setBorder(null);

        tmois2.setForeground(new java.awt.Color(0, 102, 255));
        tmois2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois2.setViewportView(tmois2);
        if (tmois2.getColumnModel().getColumnCount() > 0) {
            tmois2.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois2);
        Ptmois2.setBounds(170, 240, 70, 110);

        Ptmois1.setBorder(null);

        tmois1.setForeground(new java.awt.Color(0, 102, 255));
        tmois1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois1.setViewportView(tmois1);
        if (tmois1.getColumnModel().getColumnCount() > 0) {
            tmois1.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois1);
        Ptmois1.setBounds(60, 300, 70, 110);

        Ptmois3.setBorder(null);

        tmois3.setForeground(new java.awt.Color(0, 102, 255));
        tmois3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois3.setViewportView(tmois3);
        if (tmois3.getColumnModel().getColumnCount() > 0) {
            tmois3.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois3);
        Ptmois3.setBounds(200, 300, 70, 110);

        Ptmois4.setBorder(null);

        tmois4.setForeground(new java.awt.Color(0, 102, 255));
        tmois4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois4.setViewportView(tmois4);
        if (tmois4.getColumnModel().getColumnCount() > 0) {
            tmois4.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois4);
        Ptmois4.setBounds(270, 300, 70, 110);

        Ptmois5.setBorder(null);

        tmois5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        Ptmois5.setViewportView(tmois5);

        getContentPane().add(Ptmois5);
        Ptmois5.setBounds(410, 275, 280, 22);

        Ptmois6.setBorder(null);

        tmois6.setForeground(new java.awt.Color(0, 102, 255));
        tmois6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois6.setViewportView(tmois6);
        if (tmois6.getColumnModel().getColumnCount() > 0) {
            tmois6.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois6);
        Ptmois6.setBounds(410, 300, 70, 110);

        Ptmois7.setBorder(null);

        tmois7.setForeground(new java.awt.Color(0, 102, 255));
        tmois7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois7.setViewportView(tmois7);
        if (tmois7.getColumnModel().getColumnCount() > 0) {
            tmois7.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois7);
        Ptmois7.setBounds(480, 300, 70, 110);

        Ptmois8.setBorder(null);

        tmois8.setForeground(new java.awt.Color(0, 102, 255));
        tmois8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois8.setViewportView(tmois8);
        if (tmois8.getColumnModel().getColumnCount() > 0) {
            tmois8.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois8);
        Ptmois8.setBounds(550, 300, 70, 110);

        Ptmois9.setBorder(null);

        tmois9.setForeground(new java.awt.Color(0, 102, 255));
        tmois9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois9.setViewportView(tmois9);
        if (tmois9.getColumnModel().getColumnCount() > 0) {
            tmois9.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois9);
        Ptmois9.setBounds(620, 300, 70, 110);

        Ptmois10.setBorder(null);

        tmois10.setForeground(new java.awt.Color(0, 102, 255));
        tmois10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois10.setViewportView(tmois10);
        if (tmois10.getColumnModel().getColumnCount() > 0) {
            tmois10.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois10);
        Ptmois10.setBounds(690, 300, 70, 110);

        Ptmois11.setBorder(null);

        tmois11.setForeground(new java.awt.Color(0, 102, 255));
        tmois11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois11.setViewportView(tmois11);
        if (tmois11.getColumnModel().getColumnCount() > 0) {
            tmois11.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois11);
        Ptmois11.setBounds(760, 300, 70, 110);

        Ptmois12.setBorder(null);

        tmois12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        Ptmois12.setViewportView(tmois12);

        getContentPane().add(Ptmois12);
        Ptmois12.setBounds(690, 275, 280, 22);

        Ptmois13.setBorder(null);

        tmois13.setForeground(new java.awt.Color(0, 102, 255));
        tmois13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois13.setViewportView(tmois13);
        if (tmois13.getColumnModel().getColumnCount() > 0) {
            tmois13.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois13);
        Ptmois13.setBounds(900, 300, 70, 110);

        Ptmois14.setBorder(null);

        tmois14.setForeground(new java.awt.Color(0, 102, 255));
        tmois14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois14.setViewportView(tmois14);
        if (tmois14.getColumnModel().getColumnCount() > 0) {
            tmois14.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois14);
        Ptmois14.setBounds(830, 300, 70, 110);

        pmois23.setBorder(null);

        sem12.setForeground(new java.awt.Color(0, 102, 255));
        sem12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 5"
            }
        ));
        pmois23.setViewportView(sem12);

        getContentPane().add(pmois23);
        pmois23.setBounds(340, 163, 70, 110);

        Ptmois15.setBorder(null);

        tmois15.setForeground(new java.awt.Color(0, 102, 255));
        tmois15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semaine 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ptmois15.setViewportView(tmois15);
        if (tmois15.getColumnModel().getColumnCount() > 0) {
            tmois15.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(Ptmois15);
        Ptmois15.setBounds(340, 300, 70, 110);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane PanMois2;
    public javax.swing.JScrollPane Pmois;
    public javax.swing.JScrollPane Pmois1;
    public javax.swing.JScrollPane Pmois2;
    public javax.swing.JScrollPane Ptmois;
    public javax.swing.JScrollPane Ptmois1;
    public javax.swing.JScrollPane Ptmois10;
    public javax.swing.JScrollPane Ptmois11;
    public javax.swing.JScrollPane Ptmois12;
    public javax.swing.JScrollPane Ptmois13;
    public javax.swing.JScrollPane Ptmois14;
    public javax.swing.JScrollPane Ptmois15;
    public javax.swing.JScrollPane Ptmois2;
    public javax.swing.JScrollPane Ptmois3;
    public javax.swing.JScrollPane Ptmois4;
    public javax.swing.JScrollPane Ptmois5;
    public javax.swing.JScrollPane Ptmois6;
    public javax.swing.JScrollPane Ptmois7;
    public javax.swing.JScrollPane Ptmois8;
    public javax.swing.JScrollPane Ptmois9;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JTable mois1;
    public javax.swing.JTable mois2;
    public javax.swing.JTable mois3;
    public javax.swing.JScrollPane pmois2;
    public javax.swing.JScrollPane pmois22;
    public javax.swing.JScrollPane pmois23;
    public javax.swing.JScrollPane pmois3;
    public javax.swing.JScrollPane pmois6;
    public javax.swing.JTable sem1;
    public javax.swing.JTable sem10;
    public javax.swing.JTable sem11;
    public javax.swing.JTable sem12;
    public javax.swing.JTable sem13;
    public javax.swing.JTable sem2;
    public javax.swing.JTable sem3;
    public javax.swing.JTable sem4;
    public javax.swing.JTable sem5;
    public javax.swing.JTable sem6;
    public javax.swing.JTable sem7;
    public javax.swing.JTable sem8;
    public javax.swing.JTable sem9;
    public javax.swing.JTable tmois;
    public javax.swing.JTable tmois1;
    public javax.swing.JTable tmois10;
    public javax.swing.JTable tmois11;
    public javax.swing.JTable tmois12;
    public javax.swing.JTable tmois13;
    public javax.swing.JTable tmois14;
    public javax.swing.JTable tmois15;
    public javax.swing.JTable tmois2;
    public javax.swing.JTable tmois3;
    public javax.swing.JTable tmois4;
    public javax.swing.JTable tmois5;
    public javax.swing.JTable tmois6;
    public javax.swing.JTable tmois7;
    public javax.swing.JTable tmois8;
    public javax.swing.JTable tmois9;
    // End of variables declaration//GEN-END:variables
}
