/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.Database;
import controler.IDatabase;
import com.caucho.hessian.client.HessianProxyFactory;
import com.toedter.calendar.JTextFieldDateEditor;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.*;


/**
 *
 * @author Rafaly Antoni
 */
public class Pv extends javax.swing.JFrame {
int n=0,j=0;
 //IDataBase crud = new DataBase();
 int xMouse,yMouse;
    JTextFieldDateEditor dateD;
     String theDate;
    /**
     * Creates new form Pv
     */
     private IDatabase crud = null;
  static private String hoteDist = "http://DESKTOP-VLD2HGD:8080/appView/rpc";  //DESKTOP-VLD2HGD
	static private IDatabase getConnection(String url)
	{
		try 
		{
			HessianProxyFactory factory = new com.caucho.hessian.client.HessianProxyFactory();
			return (IDatabase)factory.create(IDatabase.class,url); 
		}
		catch(Exception e)
		{
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    
			return null;
		}
	}
    public Pv() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Sary/index.png")).getImage());
        Date date=new Date(); 
        DateFormat dateFormat=new SimpleDateFormat("HH:mm");
        heur.setText(dateFormat.format(date));
        crud = getConnection(hoteDist);
        //crud = new DataBase();
         miala.setVisible(false);
     SousM.setVisible(false);
        menu.setVisible(true);
        miala.setVisible(false);
        adm.setVisible(false);
        adm1.setVisible(false);
        propo.setVisible(false);
        propo1.setVisible(false);
        reduire.setVisible(false);
        reduire1.setVisible(false);
        note.setVisible(false);
        note1.setVisible(false);
        aide.setVisible(false);
        aide1.setVisible(false);
        fer.setVisible(false);
        fer1.setVisible(false);
     //fer1.setVisible(false);
     //afficher acteur
     try{
     for(int i = 0;i<= crud.affichePers().size();i++){
                    acteur.addItem(crud.affichePers().get(i).getNomJour());
                }
     }
     catch(Exception e){}
       
        
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        Badmin = new javax.swing.JLabel();
        NextAdmin = new javax.swing.JLabel();
        ferm1 = new javax.swing.JLabel();
        ferm2 = new javax.swing.JLabel();
        retour = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        line4 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        type = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        heur = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        observe = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        datte = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        acteur = new javax.swing.JComboBox();
        equip = new javax.swing.JComboBox();
        boxe1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        barre = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();
        propo = new javax.swing.JLabel();
        fer1 = new javax.swing.JLabel();
        fer = new javax.swing.JLabel();
        note1 = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        propo1 = new javax.swing.JLabel();
        aide = new javax.swing.JLabel();
        aide1 = new javax.swing.JLabel();
        reduire = new javax.swing.JLabel();
        reduire1 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        miala = new javax.swing.JLabel();
        SousM = new javax.swing.JLabel();
        adm = new javax.swing.JLabel();
        adm1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Badmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Badmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BadminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BadminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BadminMousePressed(evt);
            }
        });
        getContentPane().add(Badmin);
        Badmin.setBounds(730, 10, 130, 20);

        NextAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NextAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NextAdminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NextAdminMousePressed(evt);
            }
        });
        getContentPane().add(NextAdmin);
        NextAdmin.setBounds(360, 0, 140, 35);

        ferm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferm1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferm1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferm1MousePressed(evt);
            }
        });
        getContentPane().add(ferm1);
        ferm1.setBounds(965, 8, 19, 19);
        getContentPane().add(ferm2);
        ferm2.setBounds(961, 7, 19, 19);

        retour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(10, 10, 30, 20);

        line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/Line.jpg"))); // NOI18N
        line.setText("jLabel2");
        getContentPane().add(line);
        line.setBounds(190, 185, 260, 2);

        line4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/Line.jpg"))); // NOI18N
        line4.setText("jLabel2");
        getContentPane().add(line4);
        line4.setBounds(190, 230, 260, 2);
        getContentPane().add(list1);
        list1.setBounds(640, 270, 220, 60);

        type.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        type.setForeground(new java.awt.Color(2, 115, 197));
        getContentPane().add(type);
        type.setBounds(640, 190, 220, 30);

        jButton3.setBackground(new java.awt.Color(12, 46, 73));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(770, 340, 90, 30);

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(67, 68, 70));
        jLabel9.setText("Types");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 190, 120, 30);

        heur.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        heur.setForeground(new java.awt.Color(2, 115, 197));
        heur.setBorder(null);
        getContentPane().add(heur);
        heur.setBounds(190, 160, 260, 30);

        observe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        observe.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        observe.setForeground(new java.awt.Color(2, 115, 197));
        jScrollPane4.setViewportView(observe);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(190, 260, 260, 70);

        jButton1.setBackground(new java.awt.Color(12, 46, 73));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 390, 100, 30);

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(67, 68, 70));
        jLabel7.setText("Equipements");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 150, 120, 30);

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 68, 70));
        jLabel6.setText("Périodicités");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 110, 100, 30);

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(67, 68, 70));
        jLabel8.setText("Acteurs");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(490, 230, 100, 30);

        datte.setBackground(new java.awt.Color(255, 255, 255));
        datte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        datte.setForeground(new java.awt.Color(2, 115, 197));
        datte.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        getContentPane().add(datte);
        datte.setBounds(190, 110, 260, 30);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 68, 70));
        jLabel1.setText("Observation");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 280, 110, 30);

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(67, 68, 70));
        jLabel3.setText("Heure");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 160, 70, 30);

        sem.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        sem.setForeground(new java.awt.Color(2, 115, 197));
        sem.setBorder(null);
        getContentPane().add(sem);
        sem.setBounds(190, 205, 260, 30);

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 68, 70));
        jLabel4.setText("Semaine prévue");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 210, 120, 30);

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(67, 68, 70));
        jLabel5.setText("Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 110, 70, 30);

        acteur.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        acteur.setForeground(new java.awt.Color(2, 115, 197));
        getContentPane().add(acteur);
        acteur.setBounds(640, 230, 220, 30);

        equip.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        equip.setForeground(new java.awt.Color(2, 115, 197));
        equip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipActionPerformed(evt);
            }
        });
        getContentPane().add(equip);
        equip.setBounds(640, 150, 220, 30);

        boxe1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        boxe1.setForeground(new java.awt.Color(2, 115, 197));
        boxe1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Journalier", "Hebdomadaire", "Mensuel", "Trimestriel", "Semestriel" }));
        boxe1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        boxe1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boxe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxe1ActionPerformed(evt);
            }
        });
        getContentPane().add(boxe1);
        boxe1.setBounds(640, 110, 220, 30);

        jButton2.setBackground(new java.awt.Color(12, 46, 73));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(870, 230, 80, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Heure", "Semaines", "Observation", "Periodicité", "Equipements", "Types", "Acteurs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(70);
            table.getColumnModel().getColumn(1).setPreferredWidth(70);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(70);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(3).setPreferredWidth(300);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(4).setPreferredWidth(70);
            table.getColumnModel().getColumn(5).setPreferredWidth(100);
            table.getColumnModel().getColumn(6).setResizable(false);
            table.getColumnModel().getColumn(6).setPreferredWidth(100);
            table.getColumnModel().getColumn(7).setResizable(false);
            table.getColumnModel().getColumn(7).setPreferredWidth(70);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 430, 910, 120);

        barre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barreMouseDragged(evt);
            }
        });
        barre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barreMousePressed(evt);
            }
        });
        getContentPane().add(barre);
        barre.setBounds(0, 0, 50, 600);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/Fond-PV_1.jpg"))); // NOI18N
        getContentPane().add(fond);
        fond.setBounds(0, 0, 1000, 600);

        propo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                propoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                propoMouseExited(evt);
            }
        });
        getContentPane().add(propo);
        propo.setBounds(50, 95, 140, 17);

        fer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(fer1);
        fer1.setBounds(50, 173, 140, 17);

        fer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ferMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ferMousePressed(evt);
            }
        });
        getContentPane().add(fer);
        fer.setBounds(50, 173, 140, 17);

        note1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(note1);
        note1.setBounds(50, 68, 140, 17);

        note.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noteMouseExited(evt);
            }
        });
        getContentPane().add(note);
        note.setBounds(50, 68, 140, 17);

        propo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(propo1);
        propo1.setBounds(50, 95, 140, 17);

        aide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aideMouseExited(evt);
            }
        });
        getContentPane().add(aide);
        aide.setBounds(50, 121, 140, 17);

        aide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(aide1);
        aide1.setBounds(50, 121, 140, 17);

        reduire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reduireMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reduireMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reduireMousePressed(evt);
            }
        });
        getContentPane().add(reduire);
        reduire.setBounds(50, 147, 140, 17);

        reduire1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        getContentPane().add(reduire1);
        reduire1.setBounds(50, 147, 140, 17);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/tirer.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuMouseReleased(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(10, 40, 30, 20);

        miala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/retour.png"))); // NOI18N
        miala.setText("jLabel1");
        miala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mialaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mialaMousePressed(evt);
            }
        });
        getContentPane().add(miala);
        miala.setBounds(10, 40, 30, 20);

        SousM.setBackground(new java.awt.Color(204, 0, 0));
        SousM.setForeground(new java.awt.Color(204, 0, 0));
        SousM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/sousM.jpg"))); // NOI18N
        SousM.setText("jLabel1");
        getContentPane().add(SousM);
        SousM.setBounds(49, 35, 140, 199);

        adm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                admMousePressed(evt);
            }
        });
        getContentPane().add(adm);
        adm.setBounds(50, 43, 140, 17);

        adm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/backline.png"))); // NOI18N
        adm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adm1MousePressed(evt);
            }
        });
        getContentPane().add(adm1);
        adm1.setBounds(50, 43, 140, 17);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        list1.add(acteur.getSelectedItem().toString());
        n++;
         
        //dateChooserDialog1.showDialog(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       try{
        if(list1.getSelectedItem() == null)
            System.out.println("vide");
        else{
             n--;
        list1.remove(list1.getSelectedIndex());
        }}
       catch(Exception e){System.out.println(e.getMessage());}
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        try{
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            theDate = dateFormat.format(datte.getDate());
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "No Date Selected");
        }
                     
        
        list1.select(0);
         if(list1.getSelectedItem()== null /*&& observe.getText().equals("") || sem.getSelectedText().equals("") ||equip.getSelectedItem().equals("")*/){
             JOptionPane.showMessageDialog(this, "Vérifier les champs");
         list1.select(0);
         }
         else{
         int m=crud.donnePv("idJour", "journalier", "NomJour", equip.getSelectedItem().toString());
         int m1=crud.donnePv("IdTaf", "taf", "NomTaf", type.getSelectedItem().toString());
         int m2=crud.donnePv("idHebdo", "hebdomadaire", "NomHebdo", equip.getSelectedItem().toString());
         int m3=crud.donnePv("IdMen", "mensuel", "NomMen", equip.getSelectedItem().toString());
         int m4=crud.donnePv("IdTri", "trisem", "Nomtri", equip.getSelectedItem().toString());
        crud.enregistreContact(theDate, heur.getText(), Integer.valueOf(sem.getText()), observe.getText(), boxe1.getSelectedItem().toString(), m, m1,m2,m3,m4);
         
        for(int i=0; i<n;i++){
        list1.select(i);
        crud.AddActeur(crud.AddMax("pv","IdPv"), crud.donnePv("IdPers", "personnes", "NomPers", list1.getItem(i)));
        
        }
         }
         try{
             for(int i=0; i<n;i++){
                 list1.select(i);
         table.setValueAt(theDate, j, 0);
         table.setValueAt(heur.getText(), j, 1);
         table.setValueAt(sem.getText(), j, 2);
         table.setValueAt(observe.getText(), j, 3);
         table.setValueAt(boxe1.getSelectedItem(), j, 4);
         table.setValueAt(equip.getSelectedItem(), j, 5);
         table.setValueAt(type.getSelectedItem(), j, 6);
         table.setValueAt(list1.getSelectedItem(), j, 7);
             j++;}}
         catch(Exception e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}
         observe.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void equipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipActionPerformed

       if(boxe1.getSelectedItem().equals("Journalier")){
            type.removeAllItems();
       try{
            for(int i = 0;i<= crud.affiche2(1, "NomTaf", boxe1.getSelectedItem().toString(), "IdJour", "NomJour", equip.getSelectedItem().toString()).size();i++){
                type.addItem(crud.affiche2(1, "NomTaf", boxe1.getSelectedItem().toString(), "IdJour", "NomJour", equip.getSelectedItem().toString()).get(i).getNomJour());
            }
        }
        catch(Exception e){System.out.println(e.getMessage());}
       }
       //************
       if(boxe1.getSelectedItem().equals("Hebdomadaire")){
            type.removeAllItems();
       try{
            for(int i = 0;i<= crud.affiche2(1, "NomTaf", boxe1.getSelectedItem().toString(), "IdHebdo", "NomHebdo", equip.getSelectedItem().toString()).size();i++){
                type.addItem(crud.affiche2(1, "NomTaf", boxe1.getSelectedItem().toString(), "IdHebdo", "NomHebdo", equip.getSelectedItem().toString()).get(i).getNomJour());
            }
        }
        catch(Exception e){System.out.println(e.getMessage());}
       }
        //************
       if(boxe1.getSelectedItem().equals("Mensuel")){
            type.removeAllItems();
       try{
            for(int i = 0;i<= crud.affiche2(1, "NomTaf", boxe1.getSelectedItem().toString().toLowerCase(), "IdMen", "NomMen", equip.getSelectedItem().toString()).size();i++){
                type.addItem(crud.affiche2(1, "NomTaf", boxe1.getSelectedItem().toString().toLowerCase(), "IdMen", "NomMen", equip.getSelectedItem().toString()).get(i).getNomJour());
            }
        }
        catch(Exception e){System.out.println(e.getMessage());}
       }
        //************
       if(boxe1.getSelectedItem().equals("Trimestriel")||boxe1.getSelectedItem().equals("Semestriel")){
            type.removeAllItems();
       try{
            for(int i = 0;i<= crud.affiche2(1, "NomTaf", "trisem", "IdTri", "NomTri", equip.getSelectedItem().toString()).size();i++){
                type.addItem(crud.affiche2(1, "NomTaf", "trisem", "IdTri", "NomTri", equip.getSelectedItem().toString()).get(i).getNomJour());
            }
        }
        catch(Exception e){System.out.println(e.getMessage());}
       }
    }//GEN-LAST:event_equipActionPerformed

    private void barreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barreMouseDragged

    private void barreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barreMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_barreMousePressed

    private void boxe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxe1ActionPerformed
        // TODO add your handling code here:
        //
        if(boxe1.getSelectedItem().equals("Journalier"))
        {
            equip.removeAllItems();
            try
            {

                for(int i = 0;i<= crud.afficheContact("journalier").size();i++)
                {
                    equip.addItem(crud.afficheContact("journalier").get(i).getNomJour());
                }
            }
            catch(Exception e){System.out.println(e.getMessage());}
        }
        //******************************************************************************************
        if(boxe1.getSelectedItem().equals("Hebdomadaire"))
        {
            equip.removeAllItems();
            try
            {
                for(int i = 0;i<= crud.afficheContact("hebdomadaire").size();i++)
                {
                    equip.addItem(crud.afficheContact("hebdomadaire").get(i).getNomJour());
                }
            }
            catch(Exception e){System.out.println(e.getMessage());}
        }
        //*******************************************************************************************
        if(boxe1.getSelectedItem().equals("Mensuel"))
        {
            equip.removeAllItems();
            try
            {
                for(int i = 0;i<= crud.afficheContact("mensuel").size();i++)
                {
                    equip.addItem(crud.afficheContact("mensuel").get(i).getNomJour());
                }
            }
            catch(Exception e){System.out.println(e.getMessage());}
        }
        if(boxe1.getSelectedItem().equals("Trimestriel")){
            equip.removeAllItems();
            try{
                for(int i = 0;i<= crud.afficheContact("trisem").size();i++){
                    equip.addItem(crud.afficheContact("trisem").get(i).getNomJour());
                }
            }
            catch(Exception e){System.out.println(e.getMessage());}
        }
        if(boxe1.getSelectedItem().equals("Semestriel")){
            equip.removeAllItems();
            try{
                for(int i = 0;i<= crud.afficheContact("trisem").size();i++){
                    equip.addItem(crud.afficheContact("trisem").get(i).getNomJour());
                }
            }
            catch(Exception e){System.out.println(e.getMessage());}
        }
        else
        System.out.println();
    }//GEN-LAST:event_boxe1ActionPerformed

    private void propoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propoMouseEntered
        // TODO add your handling code here:
        propo1.setVisible(true);
    }//GEN-LAST:event_propoMouseEntered

    private void propoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propoMouseExited
        // TODO add your handling code here:
        propo1.setVisible(false);
    }//GEN-LAST:event_propoMouseExited

    private void ferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferMouseEntered
        // TODO add your handling code here:
        fer1.setVisible(true);
    }//GEN-LAST:event_ferMouseEntered

    private void ferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferMouseExited
        // TODO add your handling code here:
        fer1.setVisible(false);
    }//GEN-LAST:event_ferMouseExited

    private void ferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferMousePressed

    private void noteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noteMouseEntered
        // TODO add your handling code here:
        note1.setVisible(true);
    }//GEN-LAST:event_noteMouseEntered

    private void noteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noteMouseExited
        // TODO add your handling code here:
        note1.setVisible(false);
    }//GEN-LAST:event_noteMouseExited

    private void aideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aideMouseEntered
        // TODO add your handling code here:
        aide1.setVisible(true);
    }//GEN-LAST:event_aideMouseEntered

    private void aideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aideMouseExited
        // TODO add your handling code here:
        aide1.setVisible(false);
    }//GEN-LAST:event_aideMouseExited

    private void reduireMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduireMouseEntered
        // TODO add your handling code here:
        reduire1.setVisible(true);
    }//GEN-LAST:event_reduireMouseEntered

    private void reduireMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduireMouseExited
        // TODO add your handling code here:
        reduire1.setVisible(false);
        reduire.setVisible(true);
    }//GEN-LAST:event_reduireMouseExited

    private void reduireMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduireMousePressed
        // TODO add your handling code here:
        setState(Accueil.ICONIFIED);
    }//GEN-LAST:event_reduireMousePressed

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseExited

    private void menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMousePressed
        // TODO add your handling code here:
        SousM.setVisible(true);
        menu.setVisible(false);
        miala.setVisible(true);
        //****
        adm.setVisible(true);
        propo.setVisible(true);
        reduire.setVisible(true);
        note.setVisible(true);
        aide.setVisible(true);
        fer.setVisible(true);
    }//GEN-LAST:event_menuMousePressed

    private void menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseReleased

    private void mialaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mialaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_mialaMouseExited

    private void mialaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mialaMousePressed
        // TODO add your handling code here:
        SousM.setVisible(false);
        menu.setVisible(true);
        miala.setVisible(false);
        adm.setVisible(false);
        adm1.setVisible(false);
        propo.setVisible(false);
        propo1.setVisible(false);
        reduire.setVisible(false);
        reduire1.setVisible(false);
        note.setVisible(false);
        note1.setVisible(false);
        aide.setVisible(false);
        aide1.setVisible(false);
        fer.setVisible(false);
        fer1.setVisible(false);
    }//GEN-LAST:event_mialaMousePressed

    private void admMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMouseEntered
        // TODO add your handling code here:
        adm1.setVisible(true);
        //adm1.setVisible(true);
    }//GEN-LAST:event_admMouseEntered

    private void admMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMouseExited
        // TODO add your handling code here:
        adm1.setVisible(false);
    }//GEN-LAST:event_admMouseExited

    private void admMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMousePressed
        // TODO add your handling code here:
        Accueil ac = new Accueil();
        ac.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admMousePressed

    private void adm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adm1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_adm1MousePressed

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        // TODO add your handling code here:
        Plannig men = new Plannig();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourMousePressed

    private void BadminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BadminMouseEntered
        NextAdmin.setIcon(new ImageIcon(getClass().getResource("/image/admin2.jpg")));
        NextAdmin.setBounds(727,0,140,35);
        fond.add(NextAdmin);
        NextAdmin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BadminMouseEntered

    private void BadminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BadminMouseExited
        NextAdmin.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BadminMouseExited

    private void BadminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BadminMousePressed
        TestAdmin testadmin= new TestAdmin();
        testadmin.setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_BadminMousePressed

    private void NextAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NextAdminMouseEntered

    private void NextAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextAdminMouseExited
        //    NextAdmin.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_NextAdminMouseExited

    private void NextAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextAdminMousePressed

    }//GEN-LAST:event_NextAdminMousePressed

    private void ferm1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseEntered
        // TODO add your handling code here:
        ferm2.setVisible(true);
        fond.add(ferm2);
        ferm2.setIcon(new ImageIcon(getClass().getResource("/image/ferme.jpg")));
        ferm2.setBounds(961,3,30, 30);
    }//GEN-LAST:event_ferm1MouseEntered

    private void ferm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MouseExited
        // TODO add your handling code here:
        ferm2.setVisible(false);
    }//GEN-LAST:event_ferm1MouseExited

    private void ferm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferm1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ferm1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Badmin;
    private javax.swing.JLabel NextAdmin;
    private javax.swing.JLabel SousM;
    private javax.swing.JComboBox acteur;
    private javax.swing.JLabel adm;
    private javax.swing.JLabel adm1;
    private javax.swing.JLabel aide;
    private javax.swing.JLabel aide1;
    private javax.swing.JLabel barre;
    private javax.swing.JComboBox boxe1;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private com.toedter.calendar.JDateChooser datte;
    private javax.swing.JComboBox equip;
    private javax.swing.JLabel fer;
    private javax.swing.JLabel fer1;
    private javax.swing.JLabel ferm1;
    private javax.swing.JLabel ferm2;
    private javax.swing.JLabel fond;
    private javax.swing.JTextField heur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel line;
    private javax.swing.JLabel line4;
    private java.awt.List list1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel miala;
    private javax.swing.JLabel note;
    private javax.swing.JLabel note1;
    private javax.swing.JTextPane observe;
    private javax.swing.JLabel propo;
    private javax.swing.JLabel propo1;
    private javax.swing.JLabel reduire;
    private javax.swing.JLabel reduire1;
    public javax.swing.JLabel retour;
    private javax.swing.JTextField sem;
    private javax.swing.JTable table;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
