/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Snow
 */
public class stock2 extends javax.swing.JFrame {

    /**
     * Creates new form stock2
     */
    public stock2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ligne23 = new javax.swing.JLabel();
        ligne22 = new javax.swing.JLabel();
        ligne21 = new javax.swing.JLabel();
        Lnom2 = new javax.swing.JLabel();
        Tnom2 = new javax.swing.JComboBox();
        Tquantite2 = new javax.swing.JTextField();
        Ldateenregistrement2 = new javax.swing.JLabel();
        Ldatedebut2 = new javax.swing.JLabel();
        Lquantite2 = new javax.swing.JLabel();
        Bactualiser2 = new javax.swing.JButton();
        Bmodifier2 = new javax.swing.JButton();
        Lcommentaire2 = new javax.swing.JLabel();
        Tdateenregistrement2 = new javax.swing.JTextField();
        Tcommentaire22 = new javax.swing.JScrollPane();
        Tcommentaire2 = new javax.swing.JTextPane();
        Tdatedebut2 = new javax.swing.JFormattedTextField();
        Tident = new javax.swing.JTextField();
        Ltexte12 = new javax.swing.JLabel();
        Table2 = new javax.swing.JScrollPane();
        JTable2 = new javax.swing.JTable();
        FbuttonT1 = new javax.swing.JLabel();
        FbuttonT = new javax.swing.JLabel();
        Bnew2 = new javax.swing.JLabel();
        Buse2 = new javax.swing.JLabel();
        Bstock2 = new javax.swing.JLabel();
        Fond_Stock = new javax.swing.JLabel();
        Lpersonnel2 = new javax.swing.JLabel();
        Tpersonnel2 = new javax.swing.JComboBox();
        Ltexte13 = new javax.swing.JLabel();
        Table22 = new javax.swing.JScrollPane();
        JTable22 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        ligne23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        ligne23.setText("jLabel2");
        getContentPane().add(ligne23);
        ligne23.setBounds(700, 150, 230, 2);

        ligne22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        ligne22.setText("jLabel2");
        getContentPane().add(ligne22);
        ligne22.setBounds(250, 270, 230, 2);

        ligne21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ligne.jpg"))); // NOI18N
        ligne21.setText("jLabel2");
        getContentPane().add(ligne21);
        ligne21.setBounds(250, 210, 230, 2);

        Lnom2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lnom2.setForeground(new java.awt.Color(67, 68, 70));
        Lnom2.setText("Nom matériel");
        getContentPane().add(Lnom2);
        Lnom2.setBounds(90, 120, 100, 30);

        Tnom2.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        Tnom2.setForeground(new java.awt.Color(2, 115, 197));
        Tnom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tnom2ActionPerformed(evt);
            }
        });
        getContentPane().add(Tnom2);
        Tnom2.setBounds(250, 120, 230, 30);

        Tquantite2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Tquantite2.setForeground(new java.awt.Color(2, 115, 197));
        Tquantite2.setBorder(null);
        getContentPane().add(Tquantite2);
        Tquantite2.setBounds(700, 120, 230, 30);

        Ldateenregistrement2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Ldateenregistrement2.setForeground(new java.awt.Color(67, 68, 70));
        Ldateenregistrement2.setText("Date enregistrement");
        getContentPane().add(Ldateenregistrement2);
        Ldateenregistrement2.setBounds(90, 180, 140, 30);

        Ldatedebut2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Ldatedebut2.setForeground(new java.awt.Color(67, 68, 70));
        Ldatedebut2.setText("Date de mis en service");
        getContentPane().add(Ldatedebut2);
        Ldatedebut2.setBounds(90, 240, 150, 30);

        Lquantite2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lquantite2.setForeground(new java.awt.Color(67, 68, 70));
        Lquantite2.setText("Quantité");
        getContentPane().add(Lquantite2);
        Lquantite2.setBounds(540, 120, 70, 30);

        Bactualiser2.setBackground(new java.awt.Color(12, 46, 76));
        Bactualiser2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Bactualiser2.setForeground(new java.awt.Color(255, 255, 255));
        Bactualiser2.setText("Actualiser");
        Bactualiser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bactualiser2ActionPerformed(evt);
            }
        });
        getContentPane().add(Bactualiser2);
        Bactualiser2.setBounds(840, 290, 90, 30);

        Bmodifier2.setBackground(new java.awt.Color(12, 46, 76));
        Bmodifier2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        Bmodifier2.setForeground(new java.awt.Color(255, 255, 255));
        Bmodifier2.setText("Ajouter");
        Bmodifier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bmodifier2ActionPerformed(evt);
            }
        });
        getContentPane().add(Bmodifier2);
        Bmodifier2.setBounds(720, 290, 90, 30);

        Lcommentaire2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lcommentaire2.setForeground(new java.awt.Color(67, 68, 70));
        Lcommentaire2.setText("Commentaire");
        getContentPane().add(Lcommentaire2);
        Lcommentaire2.setBounds(540, 180, 120, 30);

        Tdateenregistrement2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Tdateenregistrement2.setForeground(new java.awt.Color(2, 115, 197));
        Tdateenregistrement2.setBorder(null);
        getContentPane().add(Tdateenregistrement2);
        Tdateenregistrement2.setBounds(250, 180, 230, 30);

        Tcommentaire2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tcommentaire2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        Tcommentaire2.setForeground(new java.awt.Color(2, 115, 197));
        Tcommentaire22.setViewportView(Tcommentaire2);

        getContentPane().add(Tcommentaire22);
        Tcommentaire22.setBounds(700, 180, 230, 90);

        Tdatedebut2.setBorder(null);
        Tdatedebut2.setForeground(new java.awt.Color(2, 115, 197));
        try {
            Tdatedebut2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Tdatedebut2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tdatedebut2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        getContentPane().add(Tdatedebut2);
        Tdatedebut2.setBounds(250, 240, 230, 30);
        getContentPane().add(Tident);
        Tident.setBounds(430, 350, 120, 40);

        Ltexte12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Ltexte12.setForeground(new java.awt.Color(2, 115, 197));
        Ltexte12.setText("Listes des matériels disponibles");
        getContentPane().add(Ltexte12);
        Ltexte12.setBounds(90, 360, 280, 30);

        JTable2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        JTable2.setForeground(new java.awt.Color(67, 68, 70));
        JTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Date", "Quantité", "Etat", "Emplacement", "Type", "Personnel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table2.setViewportView(JTable2);

        getContentPane().add(Table2);
        Table2.setBounds(90, 402, 880, 150);
        getContentPane().add(FbuttonT1);
        FbuttonT1.setBounds(830, 410, 16, 16);

        FbuttonT.setText("jLabel2");
        getContentPane().add(FbuttonT);
        FbuttonT.setBounds(830, 410, 16, 16);

        Bnew2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btab1.png"))); // NOI18N
        Bnew2.setText("jLabel3");
        Bnew2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bnew2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bnew2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bnew2MousePressed(evt);
            }
        });
        getContentPane().add(Bnew2);
        Bnew2.setBounds(850, 370, 16, 16);

        Buse2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btab1.png"))); // NOI18N
        Buse2.setText("jLabel2");
        Buse2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Buse2MousePressed(evt);
            }
        });
        getContentPane().add(Buse2);
        Buse2.setBounds(890, 370, 16, 16);

        Bstock2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Btab1.png"))); // NOI18N
        Bstock2.setText("jLabel2");
        Bstock2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bstock2MousePressed(evt);
            }
        });
        getContentPane().add(Bstock2);
        Bstock2.setBounds(930, 370, 16, 16);

        Fond_Stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/StockV1.jpg"))); // NOI18N
        Fond_Stock.setText("Nom");
        getContentPane().add(Fond_Stock);
        Fond_Stock.setBounds(0, 0, 1000, 600);

        Lpersonnel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        Lpersonnel2.setForeground(new java.awt.Color(67, 68, 70));
        Lpersonnel2.setText("Personnel ");
        getContentPane().add(Lpersonnel2);
        Lpersonnel2.setBounds(500, 270, 100, 30);

        Tpersonnel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tpersonnel2ActionPerformed(evt);
            }
        });
        getContentPane().add(Tpersonnel2);
        Tpersonnel2.setBounds(680, 270, 160, 30);

        Ltexte13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        Ltexte13.setForeground(new java.awt.Color(2, 115, 197));
        Ltexte13.setText("Listes des materiels en utilisation");
        getContentPane().add(Ltexte13);
        Ltexte13.setBounds(580, 110, 290, 30);
        getContentPane().add(Table22);
        Table22.setBounds(460, 140, 510, 110);

        JTable22.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom", "Date", "Nombre", "Plus", "Personnel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        getContentPane().add(JTable22);
        JTable22.setBounds(0, 0, 370, 160);
        if (JTable22.getColumnModel().getColumnCount() > 0) {
            JTable22.getColumnModel().getColumn(0).setMaxWidth(150);
            JTable22.getColumnModel().getColumn(1).setMaxWidth(150);
            JTable22.getColumnModel().getColumn(2).setMaxWidth(70);
            JTable22.getColumnModel().getColumn(3).setMaxWidth(250);
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tnom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tnom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tnom2ActionPerformed

    private void Bactualiser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bactualiser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bactualiser2ActionPerformed

    private void Bmodifier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bmodifier2ActionPerformed
        //   enregistrer();
        //  Afficher();// TODO add your handling code here:
    }//GEN-LAST:event_Bmodifier2ActionPerformed

    private void Tpersonnel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tpersonnel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tpersonnel2ActionPerformed

    private void Bnew2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bnew2MousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_Bnew2MousePressed

    private void Buse2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buse2MousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Buse2MousePressed

    private void Bstock2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bstock2MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Bstock2MousePressed

    private void Bnew2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bnew2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Bnew2MouseEntered

    private void Bnew2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bnew2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Bnew2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bactualiser2;
    public javax.swing.JButton Bmodifier2;
    public javax.swing.JLabel Bnew2;
    public javax.swing.JLabel Bstock2;
    public javax.swing.JLabel Buse2;
    public javax.swing.JLabel FbuttonT;
    public javax.swing.JLabel FbuttonT1;
    private javax.swing.JLabel Fond_Stock;
    public javax.swing.JTable JTable2;
    public javax.swing.JTable JTable22;
    public javax.swing.JLabel Lcommentaire2;
    public javax.swing.JLabel Ldatedebut2;
    public javax.swing.JLabel Ldateenregistrement2;
    public javax.swing.JLabel Lnom2;
    public javax.swing.JLabel Lpersonnel2;
    public javax.swing.JLabel Lquantite2;
    public javax.swing.JLabel Ltexte12;
    public javax.swing.JLabel Ltexte13;
    public javax.swing.JScrollPane Table2;
    public javax.swing.JScrollPane Table22;
    public javax.swing.JTextPane Tcommentaire2;
    public javax.swing.JScrollPane Tcommentaire22;
    public javax.swing.JFormattedTextField Tdatedebut2;
    public javax.swing.JTextField Tdateenregistrement2;
    public javax.swing.JTextField Tident;
    public javax.swing.JComboBox Tnom2;
    public javax.swing.JComboBox Tpersonnel2;
    public javax.swing.JTextField Tquantite2;
    public javax.swing.JLabel ligne21;
    public javax.swing.JLabel ligne22;
    public javax.swing.JLabel ligne23;
    // End of variables declaration//GEN-END:variables
}
