/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Rafaly Antoni
 */
public class Tableau extends javax.swing.JFrame {

    /**
     * Creates new form Tableau
     */
    public Tableau() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTtable = new javax.swing.JScrollPane();
        Ttable = new javax.swing.JTable();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        Ttable.setForeground(new java.awt.Color(0, 102, 255));
        Ttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Equipement", "Type", "Jour", "Semaine", "Mois"
            }
        ));
        PTtable.setViewportView(Ttable);
        if (Ttable.getColumnModel().getColumnCount() > 0) {
            Ttable.getColumnModel().getColumn(0).setResizable(false);
            Ttable.getColumnModel().getColumn(0).setPreferredWidth(30);
            Ttable.getColumnModel().getColumn(1).setResizable(false);
            Ttable.getColumnModel().getColumn(1).setPreferredWidth(30);
            Ttable.getColumnModel().getColumn(2).setResizable(false);
            Ttable.getColumnModel().getColumn(2).setPreferredWidth(50);
            Ttable.getColumnModel().getColumn(3).setResizable(false);
            Ttable.getColumnModel().getColumn(3).setPreferredWidth(30);
            Ttable.getColumnModel().getColumn(4).setResizable(false);
            Ttable.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        getContentPane().add(PTtable);
        PTtable.setBounds(70, 127, 580, 170);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sary/fond2.jpg"))); // NOI18N
        getContentPane().add(fond);
        fond.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tableau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tableau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tableau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tableau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tableau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane PTtable;
    public javax.swing.JTable Ttable;
    private javax.swing.JLabel fond;
    // End of variables declaration//GEN-END:variables
}
